<?php
declare(strict_types=1);
final class PrivateProjectFileService
{
    private const MIME_BY_EXTENSION=['pdf'=>['application/pdf'],'docx'=>['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],'zip'=>['application/zip','application/x-zip-compressed']];
    private string $root;
    public function __construct(){ $this->root=ROOT_PATH.'/storage/private/projects'; }
    public function validateUpload(array $file):array
    {
        $limits=$this->limits();$error=(int)($file['error']??UPLOAD_ERR_NO_FILE);if($error!==UPLOAD_ERR_OK)throw new InvalidArgumentException($error===UPLOAD_ERR_NO_FILE?'No se seleccionó ningún archivo.':'El archivo no se recibió correctamente (error '.$error.').');$size=(int)($file['size']??0);if($size<1||$size>$limits['max_bytes'])throw new InvalidArgumentException('El archivo está vacío o supera el límite individual de '.$limits['max_mb'].' MB.');$raw=(string)($file['name']??'');$original=basename($raw);if($raw===''||$raw!==$original||preg_match('/[\x00-\x1F\x7F]/u',$raw)||!preg_match('/^[\pL\pN _().-]+$/u',$raw))throw new InvalidArgumentException('El nombre del archivo contiene caracteres o rutas no seguras.');$extension=mb_strtolower(pathinfo($original,PATHINFO_EXTENSION));if(!in_array($extension,$limits['extensions'],true))throw new InvalidArgumentException('La extensión del archivo no está permitida.');$temporary=(string)($file['tmp_name']??'');$mime=is_file($temporary)?(new finfo(FILEINFO_MIME_TYPE))->file($temporary):'';if(!in_array($mime,self::MIME_BY_EXTENSION[$extension]??[],true))throw new InvalidArgumentException('El contenido del archivo no coincide con su formato.');return ['original_name'=>$original,'extension'=>$extension,'mime_type'=>$mime,'size_bytes'=>$size];
    }
    public function limits():array{try{$settings=(new SystemSettingModel())->all();}catch(Throwable){$settings=(new SystemSettingModel())->defaults();}$extensions=array_values(array_intersect(array_keys(self::MIME_BY_EXTENSION),$settings['file_extensions']));$mimes=[];foreach($extensions as $extension)$mimes=[...$mimes,...self::MIME_BY_EXTENSION[$extension]];$max=(int)$settings['file_max_mb'];$total=(int)$settings['file_total_max_mb'];return ['extensions'=>$extensions,'mime_types'=>array_values(array_unique($mimes)),'max_bytes'=>$max*1024*1024,'max_total_bytes'=>$total*1024*1024,'max_mb'=>$max,'max_total_mb'=>$total];}
    public function projectDirectory(int $projectId):string{if($projectId<1)throw new InvalidArgumentException('Identificador inválido.');return $this->root.DIRECTORY_SEPARATOR.$projectId;}
    public function resolveStoredFile(int $projectId,string $storageName):string{$extensions=implode('|',array_map(static fn(string $value):string=>preg_quote($value,'/'),$this->limits()['extensions']));if($extensions===''||!preg_match('/^[a-f0-9]{32,64}\.('.$extensions.')$/',$storageName))throw new InvalidArgumentException('Nombre de almacenamiento inválido.');$directory=$this->projectDirectory($projectId);$candidate=$directory.DIRECTORY_SEPARATOR.$storageName;$resolvedDirectory=realpath($directory);$resolvedFile=realpath($candidate);if($resolvedDirectory===false||$resolvedFile===false||!str_starts_with($resolvedFile,$resolvedDirectory.DIRECTORY_SEPARATOR))throw new RuntimeException('El archivo privado no existe.');return $resolvedFile;}
}
