<?php
declare(strict_types=1);
final class ThesisDefenseResultException extends InvalidArgumentException { public function __construct(string $message,private int $status=422){parent::__construct($message);} public function httpStatus():int{return $this->status;} }
final class ThesisDefenseResultService
{
 public function save(int $id,string $expected,string $result,string $notes,int $actor):array{return Database::transaction(fn(PDO $db)=>$this->saveTx($db,$id,$expected,$result,$notes,$actor));}
 private function saveTx(PDO $db,int $id,string $expected,string $result,string $notes,int $actor):array{
  $q=$db->prepare("SELECT p.id,p.status,p.code,p.title,pt.code type_code FROM projects p JOIN project_types pt ON pt.id=p.project_type_id WHERE p.id=:id AND p.deleted_at IS NULL FOR UPDATE");$q->execute(['id'=>$id]);$p=$q->fetch();if(!$p||(string)$p['type_code']!=='thesis')throw new ThesisDefenseResultException('El proyecto de Titulación solicitado no está disponible.',404);if((string)$p['status']!=='defense')throw new ThesisDefenseResultException('El resultado solo puede registrarse durante la etapa de defensa.',409);if($expected!=='defense')throw new ThesisDefenseResultException('El estado esperado no es válido.',409);if(!in_array($result,['approved','rejected'],true))throw new ThesisDefenseResultException('El resultado seleccionado no es válido.');if(mb_strlen($notes)>2000)throw new ThesisDefenseResultException('Las observaciones no pueden superar 2000 caracteres.');
  $count=$db->prepare("SELECT COUNT(DISTINCT user_id) FROM project_participants WHERE project_id=:id AND status='active' AND removed_at IS NULL AND LOWER(role_code) IN ('tribunal','jury') FOR UPDATE");$count->execute(['id'=>$id]);if(!ThesisTribunalService::isValidMemberCount((int)$count->fetchColumn()))throw new ThesisDefenseResultException('El Tribunal debe conservar entre '.ThesisTribunalService::memberRangeLabel().' miembros activos.');
  $d=$db->prepare('SELECT * FROM project_defenses WHERE project_id=:id ORDER BY attempt_number DESC LIMIT 1 FOR UPDATE');$d->execute(['id'=>$id]);$defense=$d->fetch()?:null;if($defense&&$defense['result']!==null)throw new ThesisDefenseResultException('Ya existe un resultado formal registrado para esta defensa.',409);
  if(!$defense){$i=$db->prepare('INSERT INTO project_defenses(project_id,attempt_number,result,result_notes,result_registered_by,result_registered_at) VALUES(:id,1,:result,:notes,:actor,CURRENT_TIMESTAMP)');$i->execute(['id'=>$id,'result'=>$result,'notes'=>$notes?:null,'actor'=>$actor]);$defenseId=(int)$db->lastInsertId();$attempt=1;}else{$u=$db->prepare('UPDATE project_defenses SET result=:result,result_notes=:notes,result_registered_by=:actor,result_registered_at=CURRENT_TIMESTAMP WHERE id=:id');$u->execute(['result'=>$result,'notes'=>$notes?:null,'actor'=>$actor,'id'=>$defense['id']]);$defenseId=(int)$defense['id'];$attempt=(int)$defense['attempt_number'];}
  $status=$result==='approved'?'tribunal_approved':'defense';(new ProjectAuditService($db))->record($id,$actor,'tribunal_result_registered','project_defense',$defenseId,['project_status'=>'defense','result'=>null],['project_status'=>$status,'result'=>$result,'attempt'=>$attempt,'notes'=>$notes?:null]);
  if($result==='approved')(new ProjectStatusTransitionService())->transitionInTransaction($db,$id,'defense','tribunal_approved','',$actor,'thesis_management');
  $this->notify($db,$id,(string)$p['code'],$result);return ['result'=>$result,'status'=>$status];
 }
 private function notify(PDO $db,int $id,string $code,string $result):void{$approved=$result==='approved';$title=$approved?'Proyecto aprobado por el Tribunal':'Resultado de Tribunal registrado';$message=$approved?'El Tribunal aprobó el proyecto '.$code.'. El proceso continuará hacia publicación.':'El proyecto '.$code.' no fue aprobado por el Tribunal.';$q=$db->prepare("INSERT IGNORE INTO notifications(user_id,project_id,type,title,message,action_url,action_label,metadata,deduplication_key) SELECT DISTINCT pp.user_id,:project_insert,'tribunal',:title,:message,:url,'Abrir proyecto',:metadata,CONCAT(:dedup,':',pp.user_id) FROM project_participants pp JOIN users u ON u.id=pp.user_id WHERE pp.project_id=:project_filter AND pp.status='active' AND pp.removed_at IS NULL AND LOWER(pp.role_code) IN ('student','tutor','cotutor','co_tutor','co-tutor') AND u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL");$q->execute(['project_insert'=>$id,'project_filter'=>$id,'title'=>$title,'message'=>$message,'url'=>route('project-detail').'&id='.$id,'metadata'=>json_encode(['result'=>$result,'project_code'=>$code],JSON_UNESCAPED_UNICODE),'dedup'=>'tribunal-result:'.$id.':'.$result]);}
}
