<?php
declare(strict_types=1);

final class ThesisTribunalException extends InvalidArgumentException
{
    public function __construct(string $message, private int $status = 422) { parent::__construct($message); }
    public function httpStatus(): int { return $this->status; }
}

final class ThesisTribunalService
{
    private const POSITIONS = ['president', 'member_1', 'member_2'];
    private const ACTIVE_PROJECT_STATUSES = ['development', 'under_review', 'approved', 'defense', 'tribunal_approved'];
    public static function isValidMemberCount(int $count): bool { return $count === 3; }
    public static function memberRangeLabel(): string { return '3'; }
    public static function tribunalPositions(): array { return self::POSITIONS; }
    public static function hasCompleteTribunal(PDO $db, int $projectId): bool { $q=$db->prepare("SELECT COUNT(DISTINCT user_id),COUNT(DISTINCT tribunal_position),SUM(tribunal_position='president'),SUM(tribunal_position='member_1'),SUM(tribunal_position='member_2') FROM project_participants WHERE project_id=:id AND status='active' AND removed_at IS NULL AND LOWER(role_code) IN ('tribunal','jury')");$q->execute(['id'=>$projectId]);$r=$q->fetch(PDO::FETCH_NUM);return (int)$r[0]===3&&(int)$r[1]===3&&(int)$r[2]===1&&(int)$r[3]===1&&(int)$r[4]===1; }
    public function candidates(int $id): array { $p=$this->availableProject(Database::connection(),$id);return array_map(static fn(array $c):array=>['id'=>$c['user_id'],'full_name'=>$c['name'],'email'=>$c['email'],'academic_title'=>$c['academic_title'],'institutional_code'=>$c['institutional_code']],$this->candidatesWithLoadForProject(Database::connection(),$p,[])); }
    public function suggest(int $id,int $desiredCount,array $exclusions=[],bool $replacement=false,array $loadOverrides=[],string $position=''):array {
        if($replacement){if($desiredCount!==1||!in_array($position,self::POSITIONS,true))throw new ThesisTribunalException('El cargo del Tribunal no es válido.');}elseif($desiredCount!==3)throw new ThesisTribunalException('El Tribunal requiere exactamente tres docentes.');
        $db=Database::connection();$p=$this->availableProject($db,$id);$candidates=$this->candidatesWithLoadForProject($db,$p,$this->normalizeIds($exclusions),$loadOverrides);$available=count($candidates);if($available<$desiredCount)throw new ThesisTribunalException($replacement?'No existen otros docentes disponibles para realizar el reemplazo.':'No existen suficientes docentes disponibles para conformar el Tribunal.');$groups=[];foreach($candidates as $c)$groups[(int)$c['effective_load']][]=$c;ksort($groups,SORT_NUMERIC);$ordered=[];foreach($groups as $group){if(count($group)>1)shuffle($group);array_push($ordered,...$group);}$selected=array_slice($ordered,0,$desiredCount);foreach($selected as $i=>&$c)$c['tribunal_position']=$replacement?$position:self::POSITIONS[$i];unset($c);return ['project_id'=>(int)$p['id'],'desired_count'=>$desiredCount,'available_count'=>$available,'members'=>$selected];
    }
    public function availableWithLoad(int $id):array{$db=Database::connection();return $this->candidatesWithLoadForProject($db,$this->availableProject($db,$id),[]);}
    public function save(int $id,string $expected,array $assignments,string $reason,int $actor):array{return Database::transaction(fn(PDO $db)=>$this->saveInTransaction($db,$id,$expected,$assignments,$reason,$actor));}
    public function saveInTransaction(PDO $db,int $id,string $expected,array $assignments,string $reason,int $actor):array {
        $p=$this->project($db,$id,true);$status=(string)$p['status'];if(!in_array($status,['approved','defense'],true))throw new ThesisTribunalException('El Tribunal solo puede gestionarse mientras el proyecto está aprobado o en defensa.');if($expected!==$status)throw new ThesisTribunalException('El estado del proyecto cambió. Recarga el proceso antes de continuar.',409);$assignments=$this->normalizeAssignments($assignments);$ids=array_values($assignments);
        $q=$db->prepare("SELECT pp.id,pp.user_id,LOWER(pp.role_code) role_code,pp.tribunal_position,pp.status,pp.removed_at,u.full_name FROM project_participants pp JOIN users u ON u.id=pp.user_id WHERE pp.project_id=:project AND (LOWER(pp.role_code) IN ('tutor','cotutor','co_tutor','co-tutor','tribunal','jury') OR pp.user_id=:tutor) FOR UPDATE");$q->execute(['project'=>$id,'tutor'=>(int)$p['tutor_id']]);$rows=$q->fetchAll();$current=[];$legacy=[];$blocked=[];foreach($rows as $r){$role=$r['role_code'];$uid=(int)$r['user_id'];if($uid===(int)$p['tutor_id']||in_array($role,['tutor','cotutor','co_tutor','co-tutor'],true))$blocked[]=$uid;if(in_array($role,['tribunal','jury'],true)&&$r['status']==='active'&&!$r['removed_at']){$position=(string)($r['tribunal_position']??'');if(in_array($position,self::POSITIONS,true))$current[$position]=['user_id'=>$uid,'name'=>$r['full_name'],'tribunal_position'=>$position];else$legacy[]=['user_id'=>$uid,'name'=>$r['full_name'],'tribunal_position'=>null];}}
        if(array_intersect($ids,$blocked))throw new ThesisTribunalException('El Tutor o Cotutor del proyecto no puede formar parte del Tribunal.');$marks=implode(',',array_fill(0,3,'?'));$valid=$db->prepare("SELECT DISTINCT u.id,u.full_name FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.code='teacher' JOIN teacher_profiles tp ON tp.user_id=u.id WHERE u.id IN ($marks) AND u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL FOR UPDATE");$valid->execute($ids);$names=[];foreach($valid->fetchAll() as $r)$names[(int)$r['id']]=$r['full_name'];if(count($names)!==3)throw new ThesisTribunalException('Uno o más integrantes seleccionados no son docentes activos válidos.');$next=[];foreach($assignments as $position=>$uid)$next[$position]=['user_id'=>$uid,'name'=>$names[$uid],'tribunal_position'=>$position];$changed=$legacy!==[]||$current!==$next;if(!$changed&&$status==='defense')throw new ThesisTribunalException('No se detectaron cambios en la composición del Tribunal.');$reason=trim($reason);if($status==='defense'&&(mb_strlen($reason)<5||mb_strlen($reason)>500))throw new ThesisTribunalException('Indica un motivo de entre 5 y 500 caracteres para modificar el Tribunal durante la defensa.');
        if($changed){$db->prepare("UPDATE project_participants SET status='inactive',removed_at=CURRENT_TIMESTAMP WHERE project_id=:id AND status='active' AND removed_at IS NULL AND LOWER(role_code) IN ('tribunal','jury')")->execute(['id'=>$id]);$find=$db->prepare("SELECT id FROM project_participants WHERE project_id=:p AND user_id=:u AND LOWER(role_code) IN ('tribunal','jury') ORDER BY id DESC LIMIT 1 FOR UPDATE");$reactivate=$db->prepare("UPDATE project_participants SET role_code='tribunal',tribunal_position=:position,permission_level='review',status='active',removed_at=NULL,assigned_at=CURRENT_TIMESTAMP WHERE id=:id");$insert=$db->prepare("INSERT INTO project_participants(project_id,user_id,role_code,tribunal_position,permission_level,is_leader,status) VALUES(:p,:u,'tribunal',:position,'review',0,'active')");foreach($assignments as $position=>$uid){$find->execute(['p'=>$id,'u'=>$uid]);$row=(int)$find->fetchColumn();$row?$reactivate->execute(['id'=>$row,'position'=>$position]):$insert->execute(['p'=>$id,'u'=>$uid,'position'=>$position]);}}
        $action=($current!==[]||$legacy!==[])?'tribunal_updated':'tribunal_assigned';$before=$legacy!==[]?['unassigned'=>$legacy]:$current;$auditId=(new ProjectAuditService($db))->record($id,$actor,$action,'project_participants',$id,['members'=>$before,'status'=>$status],['members'=>$next,'status'=>$status,'reason'=>$reason?:null],$reason?:null);$added=[];foreach($next as $position=>$member)if(!isset($current[$position])||$current[$position]['user_id']!==$member['user_id'])$added[]=$member;if($action==='tribunal_updated')(new ProjectAcademicNotificationService())->tribunalUpdated($db,$id,$p['code'],$p['title'],$added,$actor,$auditId);else(new ProjectAcademicNotificationService())->tribunalAssigned($db,$id,$p['code'],$p['title'],$added,$actor);if($status==='approved')$status=(new ProjectStatusTransitionService())->transitionInTransaction($db,$id,'approved','defense','',$actor,'thesis_tribunal_assignment')['status'];return ['member_count'=>3,'members'=>array_values($next),'action'=>$action,'status'=>$status];
    }
    private function normalizeAssignments(array $a):array{if(array_keys($a)!==self::POSITIONS)throw new ThesisTribunalException('La asignación debe incluir exactamente president, member_1 y member_2.');$out=[];foreach(self::POSITIONS as $position){$v=$a[$position]??null;if(filter_var($v,FILTER_VALIDATE_INT)===false||(int)$v<1)throw new ThesisTribunalException('El identificador de un integrante no es válido.');$out[$position]=(int)$v;}if(count(array_unique($out))!==3)throw new ThesisTribunalException('Los cargos del Tribunal deben pertenecer a usuarios distintos.');return $out;}
    private function normalizeIds(array $ids):array{$n=array_values(array_unique(array_filter(array_map('intval',$ids),static fn(int $id):bool=>$id>0)));sort($n);return $n;}
    private function candidatesWithLoadForProject(PDO $db,array $project,array $additionalExclusions,array $loadOverrides=[]):array{$excluded=array_values(array_unique(array_merge($this->incompatibleIds($db,(int)$project['id'],(int)$project['tutor_id']),$additionalExclusions)));$active="'".implode("','",self::ACTIVE_PROJECT_STATUSES)."'";$where="u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL";$params=['tutor_project'=>(int)$project['id'],'cotutor_project'=>(int)$project['id'],'tribunal_project'=>(int)$project['id']];if($excluded){$h=[];foreach($excluded as $i=>$uid){$k='excluded'.$i;$h[]=':'.$k;$params[$k]=$uid;}$where.=' AND u.id NOT IN ('.implode(',',$h).')';}$sql="SELECT DISTINCT u.id user_id,u.full_name name,u.email,tp.academic_title,tp.institutional_code,COALESCE(t.tutor_projects_count,0) tutor_projects_count,COALESCE(c.cotutor_projects_count,0) cotutor_projects_count,COALESCE(j.tribunal_projects_count,0) tribunal_projects_count FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.code='teacher' JOIN teacher_profiles tp ON tp.user_id=u.id LEFT JOIN (SELECT p.tutor_id user_id,COUNT(DISTINCT p.id) tutor_projects_count FROM projects p WHERE p.deleted_at IS NULL AND p.id<>:tutor_project AND p.status IN ($active) AND p.tutor_id IS NOT NULL GROUP BY p.tutor_id)t ON t.user_id=u.id LEFT JOIN (SELECT pp.user_id,COUNT(DISTINCT p.id) cotutor_projects_count FROM project_participants pp JOIN projects p ON p.id=pp.project_id WHERE pp.status='active' AND pp.removed_at IS NULL AND LOWER(pp.role_code) IN ('cotutor','co_tutor','co-tutor') AND p.deleted_at IS NULL AND p.id<>:cotutor_project AND p.status IN ($active) GROUP BY pp.user_id)c ON c.user_id=u.id LEFT JOIN (SELECT pp.user_id,COUNT(DISTINCT p.id) tribunal_projects_count FROM project_participants pp JOIN projects p ON p.id=pp.project_id WHERE pp.status='active' AND pp.removed_at IS NULL AND LOWER(pp.role_code) IN ('tribunal','jury') AND p.deleted_at IS NULL AND p.id<>:tribunal_project AND p.status IN ($active) GROUP BY pp.user_id)j ON j.user_id=u.id WHERE $where ORDER BY u.full_name";$st=$db->prepare($sql);$st->execute($params);$rows=$st->fetchAll();$overrides=[];foreach($loadOverrides as $uid=>$v)if(filter_var($uid,FILTER_VALIDATE_INT)!==false&&is_numeric($v)&&(int)$v>=0&&(int)$v<=99&&(string)(int)$v===(string)$v)$overrides[(int)$uid]=(int)$v;foreach($rows as &$r){$r['user_id']=(int)$r['user_id'];$r['tutor_projects_count']=(int)$r['tutor_projects_count'];$r['cotutor_projects_count']=(int)$r['cotutor_projects_count'];$r['tribunal_projects_count']=(int)$r['tribunal_projects_count'];$r['total_active_assignments']=$r['tutor_projects_count']+$r['cotutor_projects_count']+$r['tribunal_projects_count'];$r['calculated_load']=$r['total_active_assignments'];$r['effective_load']=$overrides[$r['user_id']]??$r['calculated_load'];$r['has_temporary_override']=array_key_exists($r['user_id'],$overrides);}unset($r);return $rows;}
    private function availableProject(PDO $db,int $id):array{$p=$this->project($db,$id);if(!in_array($p['status'],['approved','defense'],true))throw new ThesisTribunalException('El Tribunal no puede gestionarse en el estado actual del proyecto.');return $p;}
    private function project(PDO $db,int $id,bool $lock=false):array{$q=$db->prepare("SELECT p.id,p.code,p.title,p.status,p.tutor_id,pt.code type_code FROM projects p JOIN project_types pt ON pt.id=p.project_type_id WHERE p.id=:id AND p.deleted_at IS NULL".($lock?' FOR UPDATE':''));$q->execute(['id'=>$id]);$p=$q->fetch();if(!$p||$p['type_code']!=='thesis')throw new ThesisTribunalException('El proceso de Titulación solicitado no está disponible.',404);return $p;}
    private function incompatibleIds(PDO $db,int $id,int $tutor):array{$q=$db->prepare("SELECT user_id FROM project_participants WHERE project_id=:id AND status='active' AND removed_at IS NULL AND LOWER(role_code) IN ('tutor','cotutor','co_tutor','co-tutor')");$q->execute(['id'=>$id]);$out=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));if($tutor)$out[]=$tutor;return array_values(array_unique($out));}
}
