<?php
declare(strict_types=1);
final class ThesisTribunalException extends InvalidArgumentException { public function __construct(string $message,private int $status=422){parent::__construct($message);}public function httpStatus():int{return $this->status;} }
final class ThesisTribunalService
{
 private const MIN_MEMBERS=3,MAX_MEMBERS=5;
 public static function isValidMemberCount(int $count):bool{return $count>=self::MIN_MEMBERS&&$count<=self::MAX_MEMBERS;}public static function memberRangeLabel():string{return self::MIN_MEMBERS.' y '.self::MAX_MEMBERS;}
 public function candidates(int $id):array{$db=Database::connection();$p=$this->project($db,$id,false);if(!in_array($p['status'],['approved','defense'],true))throw new ThesisTribunalException('El Tribunal no puede gestionarse en el estado actual del proyecto.');$excluded=$this->incompatibleIds($db,$id,(int)$p['tutor_id']);$sql="SELECT DISTINCT u.id,u.full_name,u.email,tp.academic_title,tp.institutional_code FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.code='teacher' JOIN teacher_profiles tp ON tp.user_id=u.id WHERE u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL";$params=[];if($excluded){$sql.=' AND u.id NOT IN ('.implode(',',array_fill(0,count($excluded),'?')).')';$params=$excluded;}$q=$db->prepare($sql.' ORDER BY u.full_name');$q->execute($params);return $q->fetchAll();}
 public function save(int $id,string $expected,array $memberIds,string $reason,int $actor):array{return Database::transaction(fn(PDO $db)=>$this->saveInTransaction($db,$id,$expected,$memberIds,$reason,$actor));}
 public function saveInTransaction(PDO $db,int $id,string $expected,array $memberIds,string $reason,int $actor):array{
  $p=$this->project($db,$id,true);$status=(string)$p['status'];if(!in_array($status,['approved','defense'],true))throw new ThesisTribunalException('El Tribunal solo puede gestionarse mientras el proyecto está aprobado o en defensa.');if($expected!==$status)throw new ThesisTribunalException('El estado del proyecto cambió. Recarga el proceso antes de continuar.',409);
  $ids=array_values(array_unique(array_filter(array_map('intval',$memberIds),fn($v)=>$v>0)));sort($ids);if(!self::isValidMemberCount(count($ids)))throw new ThesisTribunalException('Selecciona entre '.self::memberRangeLabel().' docentes para conformar el Tribunal.');
  $q=$db->prepare("SELECT pp.id,pp.user_id,LOWER(pp.role_code) role_code,pp.status,pp.removed_at,u.full_name FROM project_participants pp JOIN users u ON u.id=pp.user_id WHERE pp.project_id=:project AND (LOWER(pp.role_code) IN ('tutor','cotutor','co_tutor','co-tutor','tribunal','jury') OR pp.user_id=:tutor) FOR UPDATE");$q->execute(['project'=>$id,'tutor'=>(int)$p['tutor_id']]);$rows=$q->fetchAll();$current=[];$blocked=[];foreach($rows as $r){$role=$r['role_code'];$uid=(int)$r['user_id'];if($uid===(int)$p['tutor_id']||in_array($role,['tutor','cotutor','co_tutor','co-tutor'],true))$blocked[]=$uid;if(in_array($role,['tribunal','jury'],true)&&$r['status']==='active'&&!$r['removed_at'])$current[$uid]=['user_id'=>$uid,'name'=>$r['full_name']];}if(array_intersect($ids,$blocked))throw new ThesisTribunalException('El Tutor o Cotutor del proyecto no puede formar parte del Tribunal.');
  $marks=implode(',',array_fill(0,count($ids),'?'));$valid=$db->prepare("SELECT DISTINCT u.id,u.full_name FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.code='teacher' JOIN teacher_profiles tp ON tp.user_id=u.id WHERE u.id IN ($marks) AND u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL FOR UPDATE");$valid->execute($ids);$next=[];foreach($valid->fetchAll() as $r)$next[(int)$r['id']]=['user_id'=>(int)$r['id'],'name'=>$r['full_name']];if(count($next)!==count($ids))throw new ThesisTribunalException('Uno o más integrantes seleccionados no son docentes activos válidos.');ksort($next);$currentIds=array_keys($current);sort($currentIds);$changed=$currentIds!==$ids;if(!$changed&&$status==='defense')throw new ThesisTribunalException('No se detectaron cambios en la composición del Tribunal.');$reason=trim($reason);if($status==='defense'&&(mb_strlen($reason)<5||mb_strlen($reason)>500))throw new ThesisTribunalException('Indica un motivo de entre 5 y 500 caracteres para modificar el Tribunal durante la defensa.');
  if($changed){if($current)$db->prepare("UPDATE project_participants SET status='inactive',removed_at=CURRENT_TIMESTAMP WHERE project_id=:id AND status='active' AND removed_at IS NULL AND LOWER(role_code) IN ('tribunal','jury')")->execute(['id'=>$id]);$find=$db->prepare("SELECT id FROM project_participants WHERE project_id=:p AND user_id=:u AND LOWER(role_code) IN ('tribunal','jury') ORDER BY id DESC LIMIT 1 FOR UPDATE");$reactivate=$db->prepare("UPDATE project_participants SET role_code='tribunal',permission_level='review',status='active',removed_at=NULL,assigned_at=CURRENT_TIMESTAMP WHERE id=:id");$insert=$db->prepare("INSERT INTO project_participants(project_id,user_id,role_code,permission_level,is_leader,status) VALUES(:p,:u,'tribunal','review',0,'active')");foreach($ids as $uid){$find->execute(['p'=>$id,'u'=>$uid]);$row=(int)$find->fetchColumn();$row?$reactivate->execute(['id'=>$row]):$insert->execute(['p'=>$id,'u'=>$uid]);}}
  $action=$current?'tribunal_updated':'tribunal_assigned';(new ProjectAuditService($db))->record($id,$actor,$action,'project_participants',$id,['members'=>array_values($current),'status'=>$status],['members'=>array_values($next),'status'=>$status,'reason'=>$reason?:null],$reason?:null);(new ProjectAcademicNotificationService())->tribunalAssigned($db,$id,$p['code'],$p['title'],array_values(array_diff_key($next,$current)),$actor);
  if($status==='approved')$status=(new ProjectStatusTransitionService())->transitionInTransaction($db,$id,'approved','defense','',$actor,'thesis_management')['status'];return ['member_count'=>count($ids),'members'=>array_values($next),'action'=>$action,'status'=>$status];
 }
 private function project(PDO $db,int $id,bool $lock):array{$q=$db->prepare("SELECT p.id,p.code,p.title,p.status,p.tutor_id,pt.code type_code FROM projects p JOIN project_types pt ON pt.id=p.project_type_id WHERE p.id=:id AND p.deleted_at IS NULL".($lock?' FOR UPDATE':''));$q->execute(['id'=>$id]);$p=$q->fetch();if(!$p||$p['type_code']!=='thesis')throw new ThesisTribunalException('El proceso de Titulación solicitado no está disponible.',404);return $p;}
 private function incompatibleIds(PDO $db,int $id,int $tutor):array{$q=$db->prepare("SELECT user_id FROM project_participants WHERE project_id=:id AND status='active' AND removed_at IS NULL AND LOWER(role_code) IN ('tutor','cotutor','co_tutor','co-tutor')");$q->execute(['id'=>$id]);$out=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));if($tutor)$out[]=$tutor;return array_values(array_unique($out));}
}
