<?php
$report = is_array($currentReport ?? null) ? $currentReport : [];
$studentProjects = is_array($studentProjects ?? null) ? $studentProjects : [];
$studentUpcoming = is_array($studentUpcoming ?? null) ? $studentUpcoming : [];
$studentNotifications = is_array($studentNotifications ?? null) ? array_slice($studentNotifications, 0, 4) : [];
$studentResources = is_array($studentResources ?? null) ? array_slice($studentResources, 0, 7) : [];
$hasProject = !empty($report['id']) || trim((string) ($report['title'] ?? '')) !== '';
$status = strtolower(trim((string) ($report['status'] ?? '')));
$labels = ['development'=>'En preparación','under_review'=>'En revisión','corrections_requested'=>'Cambios solicitados','changes_required'=>'Cambios solicitados','approved'=>'Aprobado','defense'=>'En tribunal','tribunal_approved'=>'Aprobado por el Tribunal','published'=>'Proyecto publicado'];
$statusLabel = $labels[$status] ?? trim((string) ($report['status_label'] ?? 'Estado no disponible'));
$tone = match ($status) { 'corrections_requested','changes_required' => 'is-warning', 'approved','tribunal_approved','published' => 'is-success', 'defense' => 'is-violet', default => 'is-info' };
$observationItems = is_array($observations ?? null) ? $observations : [];
$pending = count(array_filter($observationItems, static fn(array $item): bool => strtolower((string) ($item['status'] ?? '')) === 'pending'));
$addressed = count(array_filter($observationItems, static fn(array $item): bool => strtolower((string) ($item['status'] ?? '')) === 'addressed'));
// El resumen del Dashboard sólo presenta pendientes y atendidas; el detalle conserva los resueltos.
$needsAction = in_array($status, ['corrections_requested','changes_required'], true) || $pending > 0;
$projectType = trim((string) ($report['type_code'] ?? $report['type'] ?? $report['type_name'] ?? ''));
$isThesis = strtolower($projectType) === 'thesis' || str_contains(strtolower($projectType), 'tesis') || str_contains(strtolower($projectType), 'titulación');
$processSteps = $isThesis ? ['development'=>'Desarrollo','under_review'=>'Revisión','approved'=>'Aprobación','defense'=>'Tribunal','published'=>'Publicación'] : ['development'=>'Desarrollo','under_review'=>'Revisión','approved'=>'Aprobación','published'=>'Publicación'];
$stepOrder = array_keys($processSteps);
$currentStep = $status === 'tribunal_approved' ? 'approved' : ($status === 'corrections_requested' || $status === 'changes_required' ? 'under_review' : $status);
$currentIndex = array_search($currentStep, $stepOrder, true);
$currentIndex = $currentIndex === false ? 0 : $currentIndex;
$review = match (true) {
    $status === 'published' => ['icon'=>'fa-circle-check','eyebrow'=>'Proceso finalizado','title'=>'Proyecto publicado','text'=>'El proceso académico de este proyecto ha finalizado.','action'=>'Ver en repositorio','url'=>route('repository')],
    $status === 'defense' => ['icon'=>'fa-scale-balanced','eyebrow'=>'Etapa académica','title'=>'En tribunal','text'=>'El proyecto se encuentra en la etapa de evaluación por Tribunal.','action'=>'Revisar proyecto','url'=>$projectUrls['summary'] ?? route('projects')],
    $needsAction => ['icon'=>'fa-pen-to-square','eyebrow'=>'Requiere tu atención','title'=>'Cambios solicitados','text'=>$pending > 0 ? $pending . ($pending === 1 ? ' observación requiere corrección.' : ' observaciones requieren corrección.') : 'Revisa los comentarios del docente y actualiza el documento correspondiente.','action'=>'Ver observaciones','url'=>$projectUrls['observations'] ?? route('projects')],
    $status === 'under_review' => ['icon'=>'fa-magnifying-glass','eyebrow'=>'Revisión en curso','title'=>'Esperando revisión docente','text'=>'Tu entrega está siendo revisada. No hay una acción pendiente por ahora.','action'=>'Revisar proyecto','url'=>$projectUrls['summary'] ?? route('projects')],
    in_array($status, ['approved','tribunal_approved'], true) => ['icon'=>'fa-circle-check','eyebrow'=>'Revisión completada','title'=>$statusLabel,'text'=>'La revisión académica fue aprobada. Consulta el proyecto para conocer el siguiente paso.','action'=>'Revisar proyecto','url'=>$projectUrls['summary'] ?? route('projects')],
    default => ['icon'=>'fa-file-pen','eyebrow'=>'Trabajo en curso','title'=>'En preparación','text'=>'Continúa preparando la información y los documentos de tu proyecto.','action'=>'Abrir proyecto','url'=>$projectUrls['summary'] ?? route('projects')],
};
$projectUrl = (string) ($projectUrls['summary'] ?? route('projects'));
?>
<main class="student-dashboard" aria-labelledby="studentDashboardTitle">
    <header class="student-context">
        <div><span class="student-context__eyebrow">Panel del estudiante</span><h1 id="studentDashboardTitle">Seguimiento de tu proceso académico</h1></div>
        <div class="student-context__period"><i class="fa-regular fa-calendar" aria-hidden="true"></i><div><span>Período académico</span><strong><?= e((string) ($report['semester'] ?? 'Período no disponible')) ?></strong></div></div>
    </header>

    <div class="student-dashboard-main">
        <?php if (!$hasProject): ?>
            <section class="student-empty student-project-empty"><span class="student-empty__icon"><i class="fa-regular fa-folder-open" aria-hidden="true"></i></span><p class="student-section-label">Proyecto del período</p><h2>Aún no tienes proyectos en este período</h2><p>Registra un nuevo proyecto para iniciar su proceso de revisión académica.</p><a class="student-button is-primary" href="<?= e(route('new-project')) ?>"><i class="fa-solid fa-plus" aria-hidden="true"></i> Registrar nuevo proyecto</a></section>
        <?php else: ?>
            <section class="student-project-focus <?= e($tone) ?>" aria-labelledby="studentProjectTitle">
                <?php if (count($studentProjects) > 1): ?><div class="student-project-pager"><span>Proyecto 1 de <?= count($studentProjects) ?></span><button type="button" aria-label="Proyecto anterior" disabled><i class="fa-solid fa-chevron-left" aria-hidden="true"></i></button><button type="button" aria-label="Proyecto siguiente"><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></button></div><?php endif; ?>
                <div class="student-project-focus__identity"><div class="student-project-focus__topline"><span class="student-project-type"><?= e(mb_strtoupper($projectType !== '' ? $projectType : 'PROYECTO ACADÉMICO', 'UTF-8')) ?></span><span class="student-status"><i class="fa-solid fa-circle" aria-hidden="true"></i><?= e($statusLabel) ?></span></div><h2 id="studentProjectTitle"><?= e((string) ($report['title'] ?? 'Proyecto sin título')) ?></h2><div class="student-project-meta"><?php if (!empty($report['code'])): ?><span><?= e((string) $report['code']) ?></span><?php endif; ?><?php if (!empty($report['tutor'])): ?><span><i class="fa-solid fa-user-tie" aria-hidden="true"></i><?= e((string) $report['tutor']) ?></span><?php endif; ?></div></div>
                <div class="student-review-state"><span class="student-review-state__icon"><i class="fa-solid <?= e($review['icon']) ?>" aria-hidden="true"></i></span><div><p class="student-section-label"><?= e($review['eyebrow']) ?></p><h3><?= e($review['title']) ?></h3><p><?= e($review['text']) ?></p><div class="student-actions"><a class="student-button is-primary" href="<?= e((string) $review['url']) ?>"><?= e($review['action']) ?><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><?php if (($review['url'] ?? '') !== $projectUrl): ?><a class="student-button is-secondary" href="<?= e($projectUrl) ?>">Revisar proyecto</a><?php endif; ?></div></div></div>
            </section>
        <?php endif; ?>

    <?php if ($hasProject): ?><section class="student-follow-up" aria-label="Seguimiento del proyecto">
        <article class="student-observations"><header class="student-card-heading"><div><p class="student-section-label">Seguimiento</p><h2>Observaciones</h2></div><span class="student-card-icon"><i class="fa-regular fa-comments" aria-hidden="true"></i></span></header><?php if ($pending || $addressed): ?><div class="student-observation-counts"><div class="is-pending"><strong><?= $pending ?></strong><span>pendientes</span></div><div><strong><?= $addressed ?></strong><span>atendidas</span></div></div><p class="student-observation-message"><?= $pending ? 'Requieren tu atención.' : 'No tienes observaciones pendientes.' ?></p><a class="student-inline-link" href="<?= e((string) ($projectUrls['observations'] ?? $projectUrl)) ?>">Ver observaciones <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><?php else: ?><div class="student-compact-empty is-inline"><i class="fa-regular fa-circle-check" aria-hidden="true"></i><p>Sin observaciones pendientes.</p></div><?php endif; ?></article>
        <article class="student-delivery"><header class="student-card-heading"><div><p class="student-section-label">Documento enviado</p><h2>Última entrega</h2></div><span class="student-card-icon"><i class="fa-regular fa-file-lines" aria-hidden="true"></i></span></header><?php if (!empty($report['lastDelivery']) || !empty($report['document'])): ?><div class="student-delivery__summary"><div><span>Estado</span><strong><?= e($status === 'under_review' ? 'En revisión' : $statusLabel) ?></strong></div><div><span>Fecha</span><strong><?= e((string) ($report['lastDelivery'] ?? 'Fecha no disponible')) ?></strong></div></div><p class="student-delivery__situation"><?= e($status === 'under_review' ? 'Esperando revisión docente' : ($needsAction ? 'Requiere correcciones' : 'Situación disponible en el proyecto')) ?></p><a class="student-inline-link" href="<?= e((string) ($projectUrls['deliveries'] ?? $projectUrl)) ?>">Ver entregas <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><?php else: ?><div class="student-compact-empty is-inline"><i class="fa-regular fa-file" aria-hidden="true"></i><p>Aún no has realizado entregas.</p></div><?php endif; ?></article>
        <article class="student-process"><header class="student-card-heading"><div><p class="student-section-label">Ruta académica</p><h2>Estado del proceso</h2></div><span class="student-card-icon"><i class="fa-solid fa-route" aria-hidden="true"></i></span></header><ol class="student-process__steps"><?php foreach ($processSteps as $stepKey => $stepLabel): $stepIndex = array_search($stepKey, $stepOrder, true); $stepClass = $stepIndex < $currentIndex ? 'is-complete' : ($stepIndex === $currentIndex ? 'is-current' : ''); ?><li class="<?= e($stepClass) ?>"><span><?= $stepIndex < $currentIndex ? '✓' : ($stepIndex === $currentIndex ? '●' : '○') ?></span><strong><?= e($stepLabel) ?></strong></li><?php endforeach; ?></ol></article>
    </section><?php endif; ?>

    <aside class="student-upcoming" aria-labelledby="studentUpcomingTitle"><header class="student-card-heading"><div><p class="student-section-label">Agenda</p><h2 id="studentUpcomingTitle">Próximas fechas</h2></div><a href="<?= e(route('calendar')) ?>" aria-label="Abrir calendario"><i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i></a></header><?php if ($studentUpcoming === []): ?><div class="student-compact-empty"><i class="fa-regular fa-calendar-xmark" aria-hidden="true"></i><p>No tienes próximas fechas.</p><span>Agrega recordatorios para organizar tus entregas y actividades.</span><a class="student-inline-link" href="<?= e(route('calendar')) ?>">Agregar evento <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div><?php else: ?><div class="student-upcoming__list"><?php foreach (array_slice($studentUpcoming, 0, 3) as $date): ?><article><time><?= e((string) ($date['date'] ?? '—')) ?></time><div><strong><?= e((string) ($date['title'] ?? 'Fecha académica')) ?></strong><?php if (!empty($date['context'])): ?><span><?= e((string) $date['context']) ?></span><?php endif; ?></div></article><?php endforeach; ?></div><a class="student-inline-link student-calendar-link" href="<?= e(route('calendar')) ?>">Abrir calendario <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><?php endif; ?></aside>

    <section class="student-notifications" aria-labelledby="studentNotificationsTitle"><header class="student-section-header"><div><p class="student-section-label">Actualidad</p><h2 id="studentNotificationsTitle">Notificaciones recientes</h2></div><a class="student-inline-link" href="<?= e(route('notifications')) ?>">Ver todas <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></header><?php if ($studentNotifications === []): ?><div class="student-inline-empty"><i class="fa-regular fa-bell-slash" aria-hidden="true"></i><div><strong>Todo al día</strong><span>No tienes notificaciones nuevas.</span></div></div><?php else: ?><div class="student-notification-list"><?php foreach ($studentNotifications as $notification): ?><a class="student-notification <?= empty($notification['is_read']) ? 'is-unread' : '' ?>" href="<?= e((string) ($notification['action_url'] ?? route('notifications'))) ?>"><span class="student-notification__icon"><i class="fa-regular fa-bell" aria-hidden="true"></i></span><span><strong><?= e((string) ($notification['title'] ?? 'Notificación')) ?></strong><small><?= e((string) ($notification['message'] ?? '')) ?></small></span><time><?= e((string) ($notification['created_at'] ?? '')) ?></time></a><?php endforeach; ?></div><?php endif; ?></section>

    <section class="student-resources" aria-labelledby="studentResourcesTitle"><header class="student-section-header"><div><p class="student-section-label">Biblioteca institucional</p><h2 id="studentResourcesTitle">Recursos para ti</h2><p>Explora material de apoyo y proyectos académicos disponibles en el repositorio.</p></div><a class="student-inline-link" href="<?= e(route('repository')) ?>">Explorar repositorio <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></header><?php if ($studentResources === []): ?><div class="student-resource-empty"><i class="fa-regular fa-folder-open" aria-hidden="true"></i><strong>Aún no hay recursos disponibles.</strong><span>Los proyectos académicos y materiales de apoyo publicados aparecerán aquí cuando estén disponibles.</span></div><?php else: ?><div class="student-carousel" data-student-carousel><button class="student-carousel__control is-prev" type="button" data-carousel-prev aria-label="Recursos anteriores"><i class="fa-solid fa-chevron-left" aria-hidden="true"></i></button><div class="student-carousel__viewport"><div class="student-carousel__track"><?php foreach ($studentResources as $resource): ?><a class="student-resource-card" href="<?= e((string) ($resource['route'] ?? route('repository'))) ?>"><div class="student-resource-card__visual"><span><?= e((string) ($resource['badge'] ?? 'Recurso')) ?></span><i class="fa-solid <?= e((string) ($resource['icon'] ?? 'fa-book-open')) ?>" aria-hidden="true"></i></div><h3><?= e((string) ($resource['title'] ?? 'Recurso académico')) ?></h3><p><?= e((string) ($resource['description'] ?? '')) ?></p><small><?= e((string) ($resource['meta'] ?? '')) ?></small><strong>Ver recurso <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></strong></a><?php endforeach; ?><?php if (count($studentResources) > 6): ?><a class="student-resource-card is-more" href="<?= e(route('repository')) ?>"><div class="student-resource-card__visual"><span>Más contenido</span><i class="fa-solid fa-compass" aria-hidden="true"></i></div><h3>Ver más recursos</h3><p>Explora todos los proyectos académicos y materiales del repositorio.</p><strong>Explorar repositorio <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></strong></a><?php endif; ?></div></div><button class="student-carousel__control is-next" type="button" data-carousel-next aria-label="Recursos siguientes"><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></button></div><?php endif; ?></section>
    </div>
</main>
