INSERT INTO notifications (user_id, project_id, type, title, message, action_url, action_label, metadata, is_read, read_at, created_at) VALUES
(1, 1, 'delivery', 'Nueva entrega registrada', 'María Fernanda subió el Informe final v3 para revisión.', 'index.php?page=project-detail&id=1&tab=deliveries', 'Ver entrega', JSON_OBJECT('project_name', 'Sistema de Gestión Documental Académica'), 0, NULL, NOW() - INTERVAL 20 MINUTE),
(1, 1, 'observation', 'Se registraron observaciones', 'Tu tutor agregó observaciones en el capítulo de metodología.', 'index.php?page=project-detail&id=1&tab=observations', 'Revisar', JSON_OBJECT('project_name', 'Sistema de Gestión Documental Académica'), 0, NULL, NOW() - INTERVAL 2 HOUR),
(1, 2, 'status_change', 'Proyecto aprobado', 'El perfil del proyecto superó la etapa de revisión académica.', 'index.php?page=project-detail&id=2&tab=summary', 'Ver proyecto', JSON_OBJECT('project_name', 'Aplicación móvil de apoyo al aprendizaje inclusivo'), 0, NULL, NOW() - INTERVAL 3 HOUR),
(1, 4, 'repository', 'Repositorio actualizado', 'Los documentos públicos del proyecto ya están disponibles.', 'index.php?page=repository-detail&id=3', 'Abrir repositorio', JSON_OBJECT('project_name', 'Portal comunitario para alfabetización digital'), 1, NOW() - INTERVAL 4 HOUR, NOW() - INTERVAL 4 HOUR),
(1, 1, 'review', 'Requiere correcciones', 'La entrega fue devuelta con ajustes pendientes antes de continuar.', 'index.php?page=project-detail&id=1&tab=observations', 'Revisar', JSON_OBJECT('project_name', 'Sistema de Gestión Documental Académica'), 0, NULL, NOW() - INTERVAL 1 DAY),
(1, 2, 'comment', 'Nuevo comentario', 'El tutor dejó una recomendación general para el equipo.', 'index.php?page=project-detail&id=2&tab=comments', 'Ver comentario', JSON_OBJECT('project_name', 'Aplicación móvil de apoyo al aprendizaje inclusivo'), 1, NOW() - INTERVAL 1 DAY, NOW() - INTERVAL 1 DAY),
(1, 3, 'tribunal', 'Tribunal asignado', 'Se confirmaron los tres docentes que evaluarán tu proyecto.', 'index.php?page=project-detail&id=3&tab=participants', 'Ver tribunal', JSON_OBJECT('project_name', 'Plataforma para seguimiento de prácticas preprofesionales'), 1, NOW() - INTERVAL 3 DAY, NOW() - INTERVAL 3 DAY),
(1, 4, 'reminder', 'Recordatorio de entrega', 'Faltan 3 días para cargar la versión corregida del documento.', NULL, NULL, JSON_OBJECT('project_name', 'Análisis predictivo de permanencia estudiantil'), 0, NULL, NOW() - INTERVAL 4 DAY),
(1, 3, 'delivery', 'Nueva versión subida', 'La versión 2.1 quedó registrada correctamente en el historial.', 'index.php?page=project-detail&id=3&tab=deliveries', 'Ver entrega', JSON_OBJECT('project_name', 'Plataforma para seguimiento de prácticas preprofesionales'), 1, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY);
