<div class="projects-publish-modal" data-project-publish-modal hidden>
    <section class="projects-publish-dialog" role="dialog" aria-modal="true" aria-labelledby="studentPublishTitle" aria-describedby="studentPublishMessage" tabindex="-1">
        <header class="projects-publish-header"><div><span>Repositorio Académico</span><h2 id="studentPublishTitle">Publicar proyecto</h2><p id="studentPublishMessage">Revisa los archivos que formarán parte de la publicación definitiva en el Repositorio Académico.</p></div><button type="button" class="projects-publish-close" data-project-publish-close aria-label="Cerrar publicación"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></header>
        <p class="sr-only" aria-hidden="true">Este proyecto está listo para incorporarse al Repositorio Académico.</p>
        <div class="projects-publish-body" data-project-publish-ui>
            <section class="projects-publish-available"><div><strong>Archivos aprobados disponibles</strong><b data-publish-ui-count>0 archivos</b></div><ul data-publish-ui-preview></ul><button type="button" class="projects-publish-text-action" data-publish-ui-toggle-files hidden>Ver lista completa</button></section>
            <section data-publish-ui-choice><p class="projects-publish-question">¿Deseas mantener estos archivos o actualizar alguno antes de publicar?</p><div class="projects-publish-options" role="group" aria-label="Cómo preparar los archivos"><button type="button" class="projects-publish-option is-selected" data-publish-ui-keep aria-pressed="true"><i class="fa-solid fa-file-circle-check" aria-hidden="true"></i><span><strong>Mantener archivos actuales</strong><small>Publica los archivos aprobados sin realizar cambios.</small></span></button><button type="button" class="projects-publish-option" data-publish-ui-update aria-pressed="false"><i class="fa-solid fa-file-pen" aria-hidden="true"></i><span><strong>Actualizar archivos</strong><small>Agrega, reemplaza o quita archivos antes de publicar.</small></span></button></div></section>
            <section class="projects-publish-manage" data-publish-ui-manage hidden><div class="projects-publish-section-head"><div><h3>Archivos de la publicación</h3><p>Agrega, reemplaza o quita archivos. Las versiones anteriores permanecerán en el historial.</p></div><strong data-publish-ui-live-count>0 archivos se publicarán</strong></div><ul data-publish-ui-files></ul><div class="projects-publish-excluded" data-publish-ui-excluded hidden></div><div class="projects-publish-add"><input type="file" data-publish-ui-add-file aria-label="Archivos para agregar a la publicación" multiple><button type="button" data-publish-ui-add><i class="fa-solid fa-plus" aria-hidden="true"></i> Agregar archivos</button></div><p class="projects-publish-error" data-publish-ui-empty role="alert" hidden>Debes incluir al menos un archivo para publicar el proyecto.</p></section>
            <section class="projects-publish-summary" data-publish-ui-summary hidden><i class="fa-solid fa-circle-check" aria-hidden="true"></i><div><h3>Publicación lista</h3><p data-publish-ui-summary-count></p></div><ul data-publish-ui-summary-files></ul><button type="button" class="projects-publish-text-action" data-publish-ui-summary-toggle>Ver archivos incluidos</button><p class="projects-publish-warning">Al confirmar, los archivos seleccionados pasarán a formar parte de la publicación definitiva del proyecto.</p></section>
            <section class="projects-publish-remove-confirm" data-publish-ui-remove-confirm hidden role="alertdialog" aria-labelledby="publishRemoveTitle"><h3 id="publishRemoveTitle">Quitar de la publicación</h3><p>Este archivo no formará parte de la publicación final. Su versión anterior permanecerá guardada en el historial.</p><div><button type="button" data-publish-ui-remove-cancel>Cancelar</button><button type="button" data-publish-ui-remove-confirm>Quitar</button></div></section><p class="projects-publish-error" data-publish-ui-error role="alert" hidden></p>
            <section class="projects-publish-final-confirm" data-publish-ui-final-confirm hidden role="alertdialog" aria-labelledby="publishFinalTitle" aria-describedby="publishFinalText"><h3 id="publishFinalTitle">Confirmar publicación</h3><p id="publishFinalText" data-publish-ui-final-text>Se publicarán 0 archivos en el Repositorio Académico.</p><p>Al confirmar, el proyecto pasará a estado Publicado y estará disponible en el Repositorio Académico.</p><div><button type="button" data-publish-ui-final-cancel>Cancelar</button><button type="button" data-publish-ui-final-accept>Sí, publicar</button></div></section>
        </div>
        <footer class="projects-publish-footer"><button type="button" data-publish-ui-cancel>Cancelar</button><button type="button" data-publish-ui-back hidden>Volver</button><button type="button" class="projects-publish-next" data-publish-ui-next>Continuar</button><button type="button" class="projects-publish-confirm" data-publish-ui-confirm hidden>Publicar proyecto</button></footer>
    </section>
</div>
<div data-student-project-publish-config data-endpoint="<?= e((string) ($studentProjectPublishEndpoint ?? '')) ?>" data-csrf="<?= e((string) ($studentProjectPublishCsrf ?? '')) ?>"></div>
