<div class="project-detail project-workspace-v2" data-project-workspace data-project-status="<?=e((string)($project['status_key']??''))?>">
<?php if ($project === null): ?>
    <section class="detail-empty detail-not-found"><span><i class="fa-regular fa-folder-open"></i></span><h1>Proyecto no encontrado</h1><p>El expediente no existe o no tienes permiso para consultarlo.</p><a href="<?= e(route('projects')) ?>">Volver a Mis proyectos</a></section>
<?php else:
    $url = static function (string $tab, array $params = []) use ($project): string {
        return route('project-detail') . '&' . http_build_query(['id' => (int) $project['id'], 'tab' => $tab] + $params);
    };
    $can = static fn (string $permission): bool => in_array('*', $projectPermissions, true) || in_array($permission, $projectPermissions, true);
    $primary = ['label' => 'Ver expediente', 'url' => $url('summary')];
    if ($project['status_key'] === 'published' && !empty($project['repository_id'])) $primary = ['label' => 'Abrir ficha institucional', 'url' => route('repository-detail') . '&id=' . (int) $project['repository_id']];
    elseif ($project['status_key'] === 'review' && $can('observation.address')) $primary = ['label' => 'Atender observaciones', 'url' => $url('review')];
    elseif ($project['status_key'] === 'review' && $can('delivery.review')) $primary = ['label' => 'Revisar entrega', 'url' => $url('review')];
    elseif ($project['status_key'] === 'defense') $primary = ['label' => 'Consultar evaluación', 'url' => $url('information')];
    elseif ($project['status_key'] === 'tribunal_approved') $primary = ['label' => 'Preparar publicación', 'url' => $url('documents')];
    elseif ($project['status_key'] === 'approved') $primary = ['label' => 'Preparar documentos finales', 'url' => $url('documents')];
    elseif ($can('delivery.create')) $primary = ['label' => 'Registrar entrega', 'url' => $url('documents')];
    $statusKey = static function (string $status): string { $value = mb_strtolower($status, 'UTF-8'); return str_contains($value, 'atendida') ? 'addressed' : (str_contains($value, 'resuelta') ? 'resolved' : 'pending'); };
    $pendingObservations = array_values(array_filter($project['observations'], static fn (array $item): bool => $statusKey($item['status']) === 'pending'));
    $filteredObservations = $observationFilter === 'all' ? $project['observations'] : array_values(array_filter($project['observations'], static fn (array $item): bool => $statusKey($item['status']) === $observationFilter));
    $selectedObservation = null;
    foreach ($filteredObservations as $item) if ((int) $item['id'] === (int) $selectedObservationId) $selectedObservation = $item;
    $selectedObservation ??= $filteredObservations[0] ?? null;
?>
    <nav class="detail-breadcrumb" aria-label="Migas de pan"><a href="<?= e(route('projects')) ?>">Mis proyectos</a><i class="fa-solid fa-chevron-right"></i><span aria-current="page"><?= e($project['title']) ?></span></nav>

    <header class="workspace-header">
        <div class="workspace-heading"><div class="detail-badges"><span><?= e($project['type']) ?></span><strong><?= e($project['status']) ?></strong></div><h1><?= e($project['title']) ?></h1><div class="workspace-meta"><span><i class="fa-solid fa-chalkboard-user"></i><?= e($project['tutor'] ?: 'Tutor por asignar') ?></span><span><i class="fa-regular fa-calendar"></i><?= e($project['period']) ?></span><span><i class="fa-solid fa-users"></i><?= count($project['participants']) ?> integrantes</span></div></div>
        <div class="workspace-header-actions"><?php if (!empty($isAdministrator)): ?><a class="workspace-main-action" href="<?= e($projectEditUrl) ?>"><i class="fa-regular fa-pen-to-square"></i> Editar proyecto</a><?php endif; ?><a class="workspace-main-action" href="<?= e($primary['url']) ?>"><?= e($primary['label']) ?> <i class="fa-solid fa-arrow-right"></i></a><div class="detail-more-menu" data-project-more-menu><button type="button" aria-label="Más acciones" aria-haspopup="menu" aria-expanded="false"><i class="fa-solid fa-ellipsis"></i></button><div role="menu" hidden><a role="menuitem" href="<?= e($url('information')) ?>">Información del proyecto</a><a role="menuitem" href="<?= e($url('activity')) ?>">Consultar actividad</a><?php if (!empty($project['repository_id'])): ?><a role="menuitem" href="<?= e(route('repository-detail')) ?>&id=<?= (int) $project['repository_id'] ?>">Ficha institucional</a><?php endif; ?></div></div></div>
    </header>

    <nav class="workspace-tabs" aria-label="Secciones del proyecto"><?php foreach ($tabs as $key => $tab): ?><a class="<?= $activeTab === $key ? 'is-active' : '' ?>" <?= $activeTab === $key ? 'aria-current="page"' : '' ?> href="<?= e($url($key)) ?>"><i class="fa-solid <?= e($tab['icon']) ?>"></i><span><?= e($tab['label']) ?></span></a><?php endforeach; ?></nav>

    <main class="workspace-content">
    <?php if ($activeTab === 'summary'): ?>
        <div class="summary-v2">
            <section class="summary-situation"><span>Situación actual</span><h2><?php if ($pendingObservations): ?>La <?= e($project['latest_delivery']['version'] ?? 'última entrega') ?> necesita <?= count($pendingObservations) ?> <?= count($pendingObservations) === 1 ? 'corrección' : 'correcciones' ?> antes del <?= e($project['key_dates'][2]['value'] ?? 'próximo hito') ?>.<?php else: ?>El proyecto está al día y puede continuar con la siguiente etapa académica.<?php endif; ?></h2></section>
            <section class="summary-facts"><div><i class="fa-solid fa-file-lines"></i><span><small>Última entrega</small><strong><?= e($project['latest_delivery']['title'] ?? 'Sin entregas') ?></strong><em><?= e($project['latest_delivery']['date'] ?? 'No registrada') ?></em></span></div><div><i class="fa-regular fa-calendar"></i><span><small>Próxima fecha</small><strong><?= e($project['key_dates'][2]['value'] ?? 'Por definir') ?></strong><em><?= e($project['key_dates'][2]['label'] ?? 'Próximo hito') ?></em></span></div></section>
            <section class="summary-recent"><header><h2>Actividad reciente</h2></header><?php if ($project['activities']): ?><ol><?php foreach (array_slice($project['activities'], 0, 3) as $activity): ?><li><i class="fa-solid fa-check"></i><strong><?= e($activity['title']) ?></strong><time><?= e($activity['date']) ?></time></li><?php endforeach; ?></ol><?php else: ?><p class="workspace-empty-inline">No existe actividad reciente.</p><?php endif; ?></section>
        </div>

    <?php elseif ($activeTab === 'documents'): ?>
        <section class="workspace-page-heading"><div><span>Documentos</span><h2>Entregas y versiones</h2><p>Selecciona el nombre de un archivo para visualizarlo. Usa la flecha de cada fila para consultar su trazabilidad.</p></div></section>
        <script type="application/json" id="projectDeliveriesData"><?= json_encode(array_map(static fn (array $delivery): array => ['file'=>$delivery['file'],'path'=>$delivery['preview_path'],'format'=>strtoupper(pathinfo($delivery['file'], PATHINFO_EXTENSION))], $project['deliveries']), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE) ?></script>
        <?php if ($project['deliveries']): ?><div class="document-rows"><?php foreach ($project['deliveries'] as $index => $delivery): ?><details class="document-row" <?= $index === 0 ? 'open' : '' ?>><summary><span class="document-version"><?= e($delivery['version']) ?></span><span class="document-name"><strong><?= e($delivery['title']) ?></strong><small><?= e($delivery['file']) ?></small></span><span class="document-author"><small><?= e($delivery['author']) ?></small><time><?= e($delivery['date']) ?></time></span><span class="workspace-status"><?= e($delivery['status']) ?></span><button type="button" disabled aria-label="Abrir <?= e($delivery['file']) ?>">Abrir</button><i class="fa-solid fa-chevron-down"></i></summary><div class="document-expanded"><p><?= e($delivery['comment']) ?></p><dl><div><dt>Etapa</dt><dd><?= e($delivery['stage']) ?></dd></div><div><dt>Tamaño</dt><dd><?= e($delivery['size']) ?></dd></div><div><dt>Revisión</dt><dd><?= e($delivery['status']) ?></dd></div><div><dt>Observaciones vinculadas</dt><dd><?= $index === 0 ? count($project['observations']) : 0 ?></dd></div></dl></div></details><?php endforeach; ?></div><?php else: ?><div class="workspace-empty"><i class="fa-solid fa-file-circle-plus"></i><h3>Aún no existen entregas</h3><p>Las versiones registradas aparecerán aquí.</p></div><?php endif; ?>
        <?php if ($project['final_documents']): ?><section class="final-documents-v2"><header><span>Documentos finales</span><h2>Archivos para publicación</h2></header><div class="final-document-list"><?php foreach ($project['final_documents'] as $document): ?><article><i class="fa-solid <?= $document['format'] === 'ZIP' ? 'fa-file-zipper' : 'fa-file-pdf' ?>"></i><div><small><?= e($document['label']) ?></small><strong><?= e($document['file']) ?></strong></div><span><?= e($document['format']) ?></span><b><?= e($document['status']) ?></b></article><?php endforeach; ?></div></section><?php endif; ?>

    <?php elseif ($activeTab === 'review'): ?>
        <nav class="workspace-subtabs" aria-label="Vistas de revisión"><a class="<?= $reviewView === 'observations' ? 'is-active' : '' ?>" href="<?= e($url('review', ['view' => 'observations'])) ?>">Observaciones</a><a class="<?= $reviewView === 'conversation' ? 'is-active' : '' ?>" href="<?= e($url('review', ['view' => 'conversation'])) ?>">Conversación</a></nav>
        <script type="application/json" id="projectObservationsData"><?= json_encode($project['observations'], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE) ?></script>
        <?php if ($reviewView === 'observations'): ?><div class="review-master-detail"><aside class="observation-master"><header><h2>Observaciones</h2><nav aria-label="Filtrar observaciones"><?php foreach (['pending'=>'Pendientes','addressed'=>'Atendidas','resolved'=>'Resueltas','all'=>'Todas'] as $key=>$label): ?><a class="<?= $observationFilter === $key ? 'is-active' : '' ?>" href="<?= e($url('review', ['view'=>'observations','filter'=>$key])) ?>"><?= e($label) ?></a><?php endforeach; ?></nav></header><?php if ($project['observations'] && in_array($observationFilter, ['pending','all'], true)): ?><div class="observation-master-list"><?php foreach ($project['observations'] as $observation): ?><a class="<?= (int) $selectedObservation['id'] === (int) $observation['id'] ? 'is-selected' : '' ?>" href="<?= e($url('review', ['view'=>'observations','filter'=>$observationFilter,'observation'=>$observation['id']])) ?>"><span><?= e($observation['category']) ?></span><strong><?= e($observation['title']) ?></strong><small><?= e($observation['date']) ?></small></a><?php endforeach; ?></div><?php else: ?><p class="workspace-empty-inline">No hay observaciones en este estado.</p><?php endif; ?></aside><section class="observation-detail"><?php if ($selectedObservation && in_array($observationFilter, ['pending','all'], true)): ?><header><div><span class="workspace-status"><?= e($selectedObservation['status']) ?></span><small><?= e($selectedObservation['category']) ?></small></div><time><?= e($selectedObservation['date']) ?></time></header><h2><?= e($selectedObservation['title']) ?></h2><p><?= e($selectedObservation['text']) ?></p><dl><div><dt>Entrega</dt><dd><?= e($selectedObservation['delivery']) ?></dd></div><div><dt>Ubicación</dt><dd><?= e($selectedObservation['location']) ?></dd></div><div><dt>Autor</dt><dd><?= e($selectedObservation['author']) ?></dd></div></dl><?php if ($selectedObservation['responses']): ?><div class="observation-followup"><strong>Seguimiento</strong><?php foreach ($selectedObservation['responses'] as $response): ?><article><b><?= e($response['author']) ?></b><time><?= e($response['date']) ?></time><p><?= e($response['text']) ?></p></article><?php endforeach; ?></div><?php endif; ?><?php else: ?><div class="workspace-empty"><i class="fa-regular fa-circle-check"></i><h3>Selecciona una observación</h3></div><?php endif; ?></section></div>
        <?php else: ?><section class="conversation-view"><header><span>Conversación general</span><h2>Mensajes del proyecto</h2><p>Este espacio es independiente de las observaciones formales.</p></header><div class="conversation-messages"><?php foreach ($project['comments'] as $comment): ?><article><b><?= e(mb_substr($comment['author'], 0, 1, 'UTF-8')) ?></b><div><header><strong><?= e($comment['author']) ?></strong><time><?= e($comment['date']) ?></time></header><p><?= e($comment['text']) ?></p></div></article><?php endforeach; ?></div><form class="conversation-composer"><label for="projectComment">Nuevo comentario</label><textarea id="projectComment" rows="3" disabled placeholder="Escribe un comentario general..."></textarea><footer><small>La publicación se habilitará al conectar persistencia.</small><button type="button" disabled>Publicar comentario</button></footer></form></section><?php endif; ?>

    <?php elseif ($activeTab === 'activity'): ?>
        <nav class="workspace-subtabs" aria-label="Vistas de actividad"><a class="<?= $activityView === 'history' ? 'is-active' : '' ?>" href="<?= e($url('activity', ['view'=>'history'])) ?>">Historial</a><a class="<?= $activityView === 'calendar' ? 'is-active' : '' ?>" href="<?= e($url('activity', ['view'=>'calendar'])) ?>">Calendario</a></nav>
        <?php if ($activityView === 'history'): ?><section class="activity-view"><header><div><span>Historial</span><h2>Actividad del expediente</h2></div><label>Tipo <select disabled><option>Todas las actividades</option></select></label></header><ol class="activity-timeline"><?php foreach ($project['history'] as $entry): ?><li><i class="fa-solid <?= e($entry['icon']) ?>"></i><div><strong><?= e($entry['action']) ?></strong><p><?= e($entry['detail']) ?></p><?php if(!empty($entry['changes'])):?><ul class="activity-change-list"><?php foreach($entry['changes'] as $change):?><li><strong><?=e($change['field'])?></strong> <?=e($change['verb']??'cambiado')?> de “<?=e($change['from'])?>” a “<?=e($change['to'])?>”.</li><?php endforeach;?></ul><?php endif;?><small><?= e($entry['user']) ?> · <?= e($entry['role']) ?></small></div><time><?= e($entry['date']) ?></time></li><?php endforeach; ?></ol></section>
        <?php else: ?><section class="activity-view"><header><div><span>Calendario</span><h2>Eventos del proyecto</h2></div><a class="secondary-action" href="<?= e(route('calendar')) ?>&project_id=<?= (int) $project['id'] ?>">Ver calendario completo</a></header><?php if ($projectEvents): ?><div class="project-events-v2"><?php foreach ($projectEvents as $event): ?><article><i class="fa-regular fa-calendar"></i><div><strong><?= e((string) $event['title']) ?></strong><p><?= e((string) ($event['description'] ?? '')) ?></p></div><time><?= e((string) $event['date']) ?></time></article><?php endforeach; ?></div><?php else: ?><div class="workspace-empty"><i class="fa-regular fa-calendar-xmark"></i><h3>No hay eventos vinculados</h3></div><?php endif; ?></section><?php endif; ?>

    <?php else: ?>
        <div class="information-layout"><section class="information-section"><header><i class="fa-solid fa-graduation-cap"></i><div><span>Información académica</span><h2>Datos del proyecto</h2></div></header><dl><?php foreach ($project['academic_info'] as $item): ?><div><dt><?= e($item['label']) ?></dt><dd><?= e($item['value']) ?></dd></div><?php endforeach; ?></dl></section><section class="information-section"><header><i class="fa-solid fa-users"></i><div><span>Equipo</span><h2>Participantes</h2></div></header><div class="information-team"><?php foreach ($project['participant_groups'] as $group): ?><div><h3><?= e($group['label']) ?> <small><?= count($group['members']) ?></small></h3><?php foreach ($group['members'] as $member): ?><article><b><?= e($member['initial']) ?></b><span><strong><?= e($member['name']) ?></strong><small><?= e($member['role']) ?></small></span></article><?php endforeach; ?></div><?php endforeach; ?></div></section><section class="information-section administration-section"><header><i class="fa-solid fa-shield-halved"></i><div><span>Administración</span><h2>Gestión del expediente</h2></div></header><div class="administration-list"><div><span>Publicación</span><?php if (!empty($project['repository_id'])): ?><a href="<?= e(route('repository-detail')) ?>&id=<?= (int) $project['repository_id'] ?>">Abrir repositorio</a><?php else: ?><small>No disponible en esta etapa</small><?php endif; ?></div><div><span>Configuración</span><small><?= $can('status.manage') ? 'Disponible según permisos' : 'Solo para coordinación' ?></small></div></div><?php if ($can('participant.manage')): ?><button type="button" class="secondary-action" disabled>Administrar participantes</button><?php endif; ?><?php if (in_array('*', $projectPermissions, true)): ?><aside class="risk-zone"><div><strong>Zona de riesgo</strong><p>Acciones sensibles reservadas para administración.</p></div><button type="button" disabled>Archivar expediente</button></aside><?php endif; ?></section></div>
    <?php endif; ?>
    </main>
<?php endif; ?>
</div>
