<div class="project-detail">
<?php if ($project === null): ?>
    <section class="detail-empty detail-not-found"><span><i class="fa-regular fa-folder-open"></i></span><h1>Proyecto no encontrado</h1><p>El expediente no existe o no tienes permiso para consultarlo.</p><a href="<?= e(route('projects')) ?>">Volver a Mis proyectos</a></section>
<?php else: ?>
    <nav class="detail-breadcrumb" aria-label="Migas de pan"><a href="<?= e(route('projects')) ?>">Mis proyectos</a><i class="fa-solid fa-chevron-right"></i><span aria-current="page"><?= e($project['title']) ?></span></nav>
    <header class="detail-hero">
        <div class="detail-hero-main"><div class="detail-badges"><span><?= e($project['type']) ?></span><strong class="is-<?= e($project['status_key']) ?>"><?= e($project['status']) ?></strong></div><h1><?= e($project['title']) ?></h1><p><?= e($project['subtitle']) ?></p><ul><li><i class="fa-solid fa-graduation-cap"></i><?= e($project['career']) ?></li><li><i class="fa-regular fa-calendar"></i><?= e($project['period']) ?></li><li><i class="fa-solid fa-user-shield"></i><?= e($project['role']) ?></li></ul></div>
        <div class="detail-hero-side"><span>Tutor académico</span><strong><?= e($project['tutor'] ?: 'Por asignar') ?></strong><small><?= e($project['last_activity']) ?></small><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=deliveries"><i class="fa-solid fa-plus"></i> Nueva entrega</a></div>
    </header>

    <section class="detail-kpis" aria-label="Resumen ejecutivo">
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=summary"><span><i class="fa-solid fa-route"></i> Etapa actual</span><strong><?= e($project['stage']) ?></strong><small><?= (int) $project['progress'] ?>% del proceso</small></a>
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=deliveries"><span><i class="fa-solid fa-file-arrow-up"></i> Última entrega</span><strong><?= e($project['latest_delivery']['version'] ?? 'Sin entregas') ?></strong><small><?= e($project['latest_delivery']['status'] ?? 'No registrada') ?></small></a>
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=observations"><span><i class="fa-solid fa-list-check"></i> Observaciones</span><strong><?= count($project['observations']) ?> pendientes</strong><small>Consulta y atiende correcciones</small></a>
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=calendar"><span><i class="fa-regular fa-calendar-check"></i> Próxima acción</span><strong><?= e($project['next_action']) ?></strong><small>Ver planificación</small></a>
    </section>

    <nav class="detail-tabs" role="tablist" aria-label="Secciones del proyecto">
        <?php foreach ($tabs as $key => $tab): ?><a role="tab" aria-selected="<?= $activeTab === $key ? 'true' : 'false' ?>" class="<?= $activeTab === $key ? 'is-active' : '' ?>" href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=<?= e($key) ?>"><i class="fa-solid <?= e($tab['icon']) ?>"></i><?= e($tab['label']) ?></a><?php endforeach; ?>
    </nav>

    <main class="detail-panel" role="tabpanel" tabindex="0">
        <?php if ($activeTab === 'summary'): ?>
            <div class="detail-summary-grid"><div class="detail-summary-main">
                <section class="detail-section"><header><div><span>Progreso académico</span><h2>Etapas del proyecto</h2></div><strong><?= (int) $project['progress'] ?>%</strong></header><progress value="<?= (int) $project['progress'] ?>" max="100"></progress><ol class="detail-stepper"><li class="is-done">Registro</li><li class="is-done">Desarrollo</li><li class="<?= $project['progress'] >= 55 ? 'is-current' : '' ?>">Revisión</li><li class="<?= $project['progress'] >= 80 ? 'is-current' : '' ?>">Evaluación</li><li class="<?= $project['progress'] === 100 ? 'is-done' : '' ?>">Cierre</li></ol></section>
                <section class="detail-section"><header><div><span>Actividad reciente</span><h2>Últimos movimientos</h2></div><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=history">Ver historial</a></header><?php if ($project['activities']): ?><ul class="detail-activity"><?php foreach ($project['activities'] as $activity): ?><li><i class="fa-solid fa-circle-check"></i><div><strong><?= e($activity['title']) ?></strong><small><?= e($activity['date']) ?></small></div></li><?php endforeach; ?></ul><?php else: ?><p class="detail-inline-empty">Las actividades del proyecto aparecerán aquí.</p><?php endif; ?></section>
            </div><aside class="detail-summary-side"><section><span>Siguiente acción</span><h2><?= e($project['next_action']) ?></h2><p>La recomendación se adapta al estado actual del expediente.</p></section><section><span>Participantes</span><h2><?= count($project['participants']) ?> integrantes</h2><div class="detail-avatars"><?php foreach ($project['participants'] as $member): ?><span title="<?= e($member['name']) ?>"><?= e($member['initial']) ?></span><?php endforeach; ?></div><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=participants">Ver participantes</a></section><section><span>Información académica</span><dl><div><dt>Periodo</dt><dd><?= e($project['period']) ?></dd></div><div><dt>Tipo</dt><dd><?= e($project['type']) ?></dd></div></dl></section></aside></div>
        <?php elseif ($activeTab === 'comments'): ?>
            <section class="detail-section detail-comments"><header><div><span>Comunicación general</span><h2>Comentarios del proyecto</h2><p>Conversaciones generales, con o sin relación a una entrega, archivo u observación.</p></div></header><div class="detail-notice"><i class="fa-solid fa-circle-info"></i> La publicación de comentarios se habilitará al conectar la persistencia. Esta vista no simula guardados.</div><?php if ($project['comments']): ?><?php foreach ($project['comments'] as $comment): ?><article><span><?= e(substr($comment['author'], 0, 1)) ?></span><div><header><strong><?= e($comment['author']) ?></strong><time><?= e($comment['date']) ?></time></header><p><?= e($comment['text']) ?></p><small><?= $comment['relation'] ? e($comment['relation']) : 'Comentario general' ?></small></div></article><?php endforeach; ?><?php else: ?><p class="detail-inline-empty">Aún no hay comentarios en este proyecto.</p><?php endif; ?></section>
        <?php elseif ($activeTab === 'deliveries' && $project['latest_delivery']): ?>
            <section class="detail-section"><header><div><span>Trazabilidad documental</span><h2>Entregas del proyecto</h2></div></header><article class="detail-delivery"><i class="fa-solid fa-file-pdf"></i><div><strong><?= e($project['latest_delivery']['title']) ?> · <?= e($project['latest_delivery']['version']) ?></strong><p><?= e($project['latest_delivery']['date']) ?> · <?= e($project['latest_delivery']['status']) ?></p></div></article><div class="detail-notice"><i class="fa-solid fa-circle-info"></i> La carga real de nuevas versiones se implementará con validación backend, permisos y archivos privados.</div></section>
        <?php elseif ($activeTab === 'observations' && $project['observations']): ?>
            <section class="detail-section"><header><div><span>Revisión académica</span><h2>Observaciones y correcciones</h2></div></header><div class="detail-observations"><?php foreach ($project['observations'] as $observation): ?><article><span><?= e($observation['status']) ?></span><h3><?= e($observation['title']) ?></h3><p><?= e($observation['text']) ?></p></article><?php endforeach; ?></div></section>
        <?php else: $emptyMessages = ['deliveries'=>'Aún no existen entregas para este proyecto.','observations'=>'No existen observaciones registradas.','history'=>'Las actividades del proyecto aparecerán aquí.','participants'=>'No se han asignado participantes.','calendar'=>'No hay actividades programadas para este proyecto.','final-documents'=>'Los documentos definitivos aparecerán cuando el proyecto alcance la etapa final.']; ?>
            <section class="detail-empty"><span><i class="fa-solid <?= e($tabs[$activeTab]['icon']) ?>"></i></span><h2><?= e($tabs[$activeTab]['label']) ?></h2><p><?= e($emptyMessages[$activeTab] ?? 'Esta sección se encuentra en preparación.') ?></p><small>La estructura está preparada para incorporarse progresivamente sin simular operaciones.</small></section>
        <?php endif; ?>
    </main>
<?php endif; ?>
</div>
