<div class="project-detail">
<?php if ($project === null): ?>
    <section class="detail-empty detail-not-found"><span><i class="fa-regular fa-folder-open"></i></span><h1>Proyecto no encontrado</h1><p>El expediente no existe o no tienes permiso para consultarlo.</p><a href="<?= e(route('projects')) ?>">Volver a Mis proyectos</a></section>
<?php else: ?>
    <nav class="detail-breadcrumb" aria-label="Migas de pan"><a href="<?= e(route('projects')) ?>">Mis proyectos</a><i class="fa-solid fa-chevron-right"></i><span aria-current="page"><?= e($project['title']) ?></span></nav>
    <header class="detail-hero">
        <div class="detail-hero-main"><div class="detail-badges"><span><?= e($project['type']) ?></span><strong class="is-<?= e($project['status_key']) ?>"><?= e($project['status']) ?></strong></div><h1><?= e($project['title']) ?></h1><p><?= e($project['subtitle']) ?></p><ul><li><i class="fa-solid fa-graduation-cap"></i><?= e($project['career']) ?></li><li><i class="fa-regular fa-calendar"></i><?= e($project['period']) ?></li><li><i class="fa-solid fa-user-shield"></i><?= e($project['role']) ?></li></ul></div>
        <div class="detail-hero-side"><span>Tutor académico</span><strong><?= e($project['tutor'] ?: 'Por asignar') ?></strong><small><?= e($project['last_activity']) ?></small><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=deliveries"><i class="fa-solid fa-plus"></i> Nueva entrega</a></div>
    </header>

    <section class="detail-kpis" aria-label="Resumen ejecutivo">
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=summary"><span><i class="fa-solid fa-route"></i> Etapa actual</span><strong><?= e($project['stage']) ?></strong><small><?= (int) $project['progress'] ?>% del proceso</small></a>
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=deliveries"><span><i class="fa-solid fa-file-arrow-up"></i> Última entrega</span><strong><?= e($project['latest_delivery']['version'] ?? 'Sin entregas') ?></strong><small><?= e($project['latest_delivery']['status'] ?? 'No registrada') ?></small></a>
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=observations"><span><i class="fa-solid fa-list-check"></i> Observaciones</span><strong><?= count($project['observations']) ?> pendientes</strong><small>Consulta y atiende correcciones</small></a>
        <a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=calendar"><span><i class="fa-regular fa-calendar-check"></i> Próxima acción</span><strong><?= e($project['next_action']) ?></strong><small>Ver planificación</small></a>
    </section>

    <nav class="detail-tabs" role="tablist" aria-label="Secciones del proyecto">
        <?php foreach ($tabs as $key => $tab): ?><a role="tab" aria-selected="<?= $activeTab === $key ? 'true' : 'false' ?>" class="<?= $activeTab === $key ? 'is-active' : '' ?>" href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=<?= e($key) ?>"><i class="fa-solid <?= e($tab['icon']) ?>"></i><?= e($tab['label']) ?></a><?php endforeach; ?>
    </nav>

    <main class="detail-panel" role="tabpanel" tabindex="0">
        <?php if ($activeTab === 'summary'): ?>
            <div class="detail-summary-grid">
                <div class="detail-summary-main">
                    <section class="detail-section summary-stages">
                        <header><div><span>Ruta académica</span><h2>Etapas del proyecto</h2><p>El avance se obtiene de la etapa actual del expediente.</p></div><strong><?= e($project['stage']) ?></strong></header>
                        <ol class="summary-stage-list">
                            <?php foreach ($project['stages'] as $index => $stage): ?><li class="is-<?= e($stage['state']) ?>"><span><?= $stage['state'] === 'completed' ? '<i class="fa-solid fa-check"></i>' : (string) ($index + 1) ?></span><div><strong><?= e($stage['label']) ?></strong><small><?= $stage['state'] === 'completed' ? 'Completada' : ($stage['state'] === 'current' ? 'Etapa actual' : 'Próxima etapa') ?></small></div></li><?php endforeach; ?>
                        </ol>
                    </section>

                    <div class="summary-two-columns">
                        <section class="detail-section summary-delivery"><header><div><span>Trazabilidad</span><h2>Última entrega</h2></div><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=deliveries">Ver entregas</a></header><?php if ($project['latest_delivery']): ?><div class="summary-delivery-file"><i class="fa-solid fa-file-pdf"></i><div><strong><?= e($project['latest_delivery']['title']) ?> · <?= e($project['latest_delivery']['version']) ?></strong><p><?= e($project['latest_delivery']['date']) ?></p><span><?= e($project['latest_delivery']['status']) ?></span></div></div><?php else: ?><p class="detail-inline-empty">Aún no existen entregas para este proyecto.</p><?php endif; ?></section>
                        <section class="detail-section summary-observations"><header><div><span>Revisión</span><h2>Observaciones prioritarias</h2></div><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=observations">Ver todas</a></header><?php if ($project['observations']): ?><ul><?php foreach (array_slice($project['observations'], 0, 2) as $observation): ?><li><span><?= e($observation['status']) ?></span><strong><?= e($observation['title']) ?></strong><p><?= e($observation['text']) ?></p></li><?php endforeach; ?></ul><?php else: ?><p class="detail-inline-empty">No existen observaciones registradas.</p><?php endif; ?></section>
                    </div>

                    <section class="detail-section"><header><div><span>Trazabilidad reciente</span><h2>Actividad del proyecto</h2></div><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=history">Ver historial completo</a></header><?php if ($project['activities']): ?><ul class="detail-activity"><?php foreach ($project['activities'] as $activity): ?><li><i class="fa-solid fa-circle-check"></i><div><strong><?= e($activity['title']) ?></strong><small><?= e($activity['date']) ?></small></div></li><?php endforeach; ?></ul><?php else: ?><p class="detail-inline-empty">Las actividades del proyecto aparecerán aquí.</p><?php endif; ?></section>
                </div>

                <aside class="detail-summary-side">
                    <section class="summary-next-action"><span>Acción recomendada</span><i class="fa-solid fa-compass"></i><h2><?= e($project['next_action']) ?></h2><p>Esta recomendación corresponde al estado actual del expediente.</p><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=<?= $project['status_key'] === 'review' ? 'observations' : 'calendar' ?>">Continuar proceso <i class="fa-solid fa-arrow-right"></i></a></section>
                    <section><span>Participantes</span><h2><?= count($project['participants']) ?> integrantes</h2><div class="summary-participants"><?php foreach (array_slice($project['participants'], 0, 4) as $member): ?><div><b><?= e($member['initial']) ?></b><p><strong><?= e($member['name']) ?></strong><small><?= e($member['role']) ?></small></p></div><?php endforeach; ?></div><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=participants">Ver equipo completo</a></section>
                    <section><span>Fechas clave</span><dl class="summary-key-dates"><?php foreach ($project['key_dates'] as $date): ?><div><dt><?= e($date['label']) ?></dt><dd><?= e($date['value']) ?></dd></div><?php endforeach; ?></dl><a href="<?= e(route('project-detail')) ?>&id=<?= (int) $project['id'] ?>&tab=calendar">Abrir calendario</a></section>
                    <section><span>Información académica</span><dl><?php foreach ($project['academic_info'] as $item): ?><div><dt><?= e($item['label']) ?></dt><dd><?= e($item['value']) ?></dd></div><?php endforeach; ?></dl></section>
                </aside>
            </div>
        <?php elseif ($activeTab === 'deliveries'): ?>
            <section class="detail-section workspace-section"><header><div><span>Control de versiones</span><h2>Entregas del proyecto</h2><p>Cada entrega conserva su archivo, autor, etapa y retroalimentación sin reemplazar versiones anteriores.</p></div><button type="button" class="workspace-primary" disabled title="Disponible al conectar persistencia"><i class="fa-solid fa-plus"></i> Nueva entrega</button></header><div class="detail-notice"><i class="fa-solid fa-shield-halved"></i> La carga se habilitará con validación backend, permisos, CSRF y almacenamiento privado.</div><?php if ($project['deliveries']): ?><div class="delivery-list"><?php foreach ($project['deliveries'] as $index => $delivery): ?><article class="delivery-version"><div class="delivery-version-marker"><strong><?= e($delivery['version']) ?></strong><span><?= $index === 0 ? 'Actual' : 'Anterior' ?></span></div><div class="delivery-version-body"><header><div><small><?= e($delivery['stage']) ?></small><h3><?= e($delivery['title']) ?></h3></div><span class="workspace-status"><?= e($delivery['status']) ?></span></header><div class="delivery-file"><i class="fa-solid fa-file-pdf"></i><div><strong><?= e($delivery['file']) ?></strong><small><?= e($delivery['size']) ?> · Subido por <?= e($delivery['author']) ?></small></div></div><p><?= e($delivery['comment']) ?></p><footer><time><i class="fa-regular fa-calendar"></i> <?= e($delivery['date']) ?></time><span>Versión inmutable</span></footer></div></article><?php endforeach; ?></div><?php else: ?><div class="workspace-empty"><i class="fa-solid fa-file-circle-plus"></i><h3>Aún no existen entregas</h3><p>Las versiones enviadas aparecerán aquí sin reemplazar documentos anteriores.</p></div><?php endif; ?></section>
        <?php elseif ($activeTab === 'observations'): ?>
            <section class="detail-section workspace-section"><header><div><span>Revisión académica</span><h2>Observaciones y correcciones</h2><p>Consulta cada indicación, su contexto documental y el seguimiento de las respuestas.</p></div><div class="workspace-filter"><i class="fa-solid fa-filter"></i><select aria-label="Filtrar observaciones" disabled><option>Todas las observaciones</option></select></div></header><?php if ($project['observations']): ?><div class="observation-list"><?php foreach ($project['observations'] as $observation): ?><article class="observation-item"><header><div><span class="workspace-status"><?= e($observation['status']) ?></span><span><?= e($observation['category']) ?></span></div><time><?= e($observation['date']) ?></time></header><h3><?= e($observation['title']) ?></h3><p><?= e($observation['text']) ?></p><dl><div><dt>Autor</dt><dd><?= e($observation['author']) ?> · <?= e($observation['role']) ?></dd></div><div><dt>Entrega</dt><dd><?= e($observation['delivery']) ?></dd></div><div><dt>Ubicación</dt><dd><?= e($observation['location']) ?></dd></div></dl><?php if ($observation['responses']): ?><div class="observation-responses"><strong>Seguimiento</strong><?php foreach ($observation['responses'] as $response): ?><div><span><?= e(substr($response['author'], 0, 1)) ?></span><p><b><?= e($response['author']) ?></b><small><?= e($response['date']) ?></small><?= e($response['text']) ?></p></div><?php endforeach; ?></div><?php endif; ?><footer><button type="button" disabled>Responder</button><button type="button" disabled>Marcar como atendida</button></footer></article><?php endforeach; ?></div><p class="workspace-permission-note"><i class="fa-solid fa-circle-info"></i> Las acciones se activarán únicamente para usuarios autorizados cuando exista persistencia.</p><?php else: ?><div class="workspace-empty"><i class="fa-regular fa-circle-check"></i><h3>No existen observaciones registradas</h3><p>Las indicaciones del tutor o tribunal aparecerán aquí.</p></div><?php endif; ?></section>
        <?php elseif ($activeTab === 'comments'): ?>
            <section class="detail-section workspace-section detail-comments"><header><div><span>Comunicación general</span><h2>Comentarios del proyecto</h2><p>Conversaciones que pueden ser generales o relacionarse con una entrega, archivo u observación.</p></div></header><div class="comment-composer" aria-label="Publicación pendiente de habilitación"><div><span>U</span><textarea rows="3" disabled placeholder="Escribe un comentario general..."></textarea></div><footer><label>Relacionar opcionalmente con <select disabled><option>Sin relación específica</option><option>Una entrega</option><option>Un archivo</option><option>Una observación</option></select></label><button type="button" disabled>Publicar comentario</button></footer></div><div class="detail-notice"><i class="fa-solid fa-circle-info"></i> La publicación se habilitará al conectar persistencia. Esta pantalla no simula guardados.</div><?php if ($project['comments']): ?><div class="comment-thread"><?php foreach ($project['comments'] as $comment): ?><article><span><?= e(mb_substr($comment['author'], 0, 1, 'UTF-8')) ?></span><div><header><strong><?= e($comment['author']) ?></strong><time><?= e($comment['date']) ?></time></header><p><?= e($comment['text']) ?></p><small><i class="fa-solid <?= $comment['relation'] ? 'fa-link' : 'fa-message' ?>"></i> <?= $comment['relation'] ? e($comment['relation']) : 'Comentario general' ?></small><footer><button type="button" disabled>Responder</button></footer></div></article><?php endforeach; ?></div><?php else: ?><div class="workspace-empty"><i class="fa-regular fa-comments"></i><h3>Aún no hay comentarios</h3><p>Las conversaciones generales del proyecto aparecerán aquí.</p></div><?php endif; ?></section>
        <?php else: $emptyMessages = ['deliveries'=>'Aún no existen entregas para este proyecto.','observations'=>'No existen observaciones registradas.','history'=>'Las actividades del proyecto aparecerán aquí.','participants'=>'No se han asignado participantes.','calendar'=>'No hay actividades programadas para este proyecto.','final-documents'=>'Los documentos definitivos aparecerán cuando el proyecto alcance la etapa final.']; ?>
            <section class="detail-empty"><span><i class="fa-solid <?= e($tabs[$activeTab]['icon']) ?>"></i></span><h2><?= e($tabs[$activeTab]['label']) ?></h2><p><?= e($emptyMessages[$activeTab] ?? 'Esta sección se encuentra en preparación.') ?></p><small>La estructura está preparada para incorporarse progresivamente sin simular operaciones.</small></section>
        <?php endif; ?>
    </main>
<?php endif; ?>
</div>
