<?php
$v = static fn(string $key): string => e((string)($draft[$key] ?? ''));
$error = static fn(string $key): string => isset($errors[$key]) ? '<span class="wizard-field-error" id="error-' . e(str_replace('.', '-', $key)) . '">' . e($errors[$key]) . '</span>' : '';
$selected = static fn(string $key, string $value): string => (($draft[$key] ?? '') === $value) ? ' selected' : '';
$checkedMember = static fn(string $id): string => in_array($id, $draft['members'] ?? [], true) ? ' checked' : '';
?>
<main class="project-wizard" id="projectWizard" data-validated="<?= $draftValidated ? 'true' : 'false' ?>">
    <nav class="wizard-breadcrumb" aria-label="Migas de pan"><a href="<?= e(route('projects')) ?>">Mis proyectos</a><i class="fa-solid fa-chevron-right" aria-hidden="true"></i><span>Nuevo proyecto</span></nav>
    <?php if (!$creationPolicy['can_create']): ?>
        <section class="wizard-denied"><h1>No puedes crear proyectos</h1><p>Tu rol actual no tiene habilitado este permiso.</p><a href="<?= e(route('projects')) ?>">Volver a Mis proyectos</a></section>
    <?php elseif ($draftValidated): ?>
        <section class="wizard-result" tabindex="-1">
            <span class="wizard-result-icon"><i class="fa-solid fa-circle-check"></i></span><p class="wizard-eyebrow">Validación completada</p>
            <h1>Borrador validado</h1><p>La información es válida, pero el proyecto todavía no ha sido registrado.</p>
            <dl><div><dt>Código provisional</dt><dd><?= e($confirmation['provisional_code']) ?></dd></div><div><dt>Proyecto</dt><dd><?= e($confirmation['title']) ?></dd></div><div><dt>Tipo</dt><dd><?= e($confirmation['type_label']) ?></dd></div></dl>
            <p class="wizard-result-note"><i class="fa-solid fa-database"></i> No se escribió información en la base de datos ni se almacenaron archivos.</p>
            <p class="wizard-result-note"><i class="fa-regular fa-bookmark"></i> Los campos permanecerán guardados temporalmente en esta pestaña para que puedas editarlos después.</p>
            <div class="wizard-result-actions"><button type="button" class="wizard-primary" data-edit-draft>Volver a editar</button><a href="<?= e(route('projects')) ?>">Volver a Mis proyectos</a></div>
        </section>
    <?php else: ?>
        <header class="wizard-header"><div><p class="wizard-eyebrow">Nuevo expediente académico</p><h1>Crea un proyecto paso a paso</h1><p>Los campos se guardan automáticamente en esta pestaña. Los archivos deberán seleccionarse nuevamente si sales.</p></div><button type="button" class="wizard-text-action" data-discard-draft title="Elimina los campos guardados temporalmente y empieza de nuevo"><i class="fa-regular fa-trash-can"></i> Empezar de nuevo</button></header>
        <div class="wizard-shell">
            <section class="wizard-main">
                <div class="wizard-progress"><p id="wizardProgressText">Paso 1 de 5</p><ol aria-label="Progreso del formulario">
                    <?php foreach ([['type','Tipo'],['details','Datos'],['team','Equipo'],['files','Archivos'],['confirm','Confirmación']] as $i=>$step): ?><li data-step-indicator="<?= e($step[0]) ?>"<?= $i===0?' aria-current="step"':'' ?>><span><?= $i+1 ?></span><b><?= e($step[1]) ?></b></li><?php endforeach; ?>
                </ol></div>
                <?php if ($errors): ?><div class="wizard-error-summary" role="alert" tabindex="-1"><strong>Revisa la información señalada.</strong><p><?= count($errors) ?> campo(s) necesitan atención. Tus datos se conservaron.</p></div><?php else: ?><div class="wizard-error-summary" role="alert" tabindex="-1" hidden></div><?php endif; ?>
                <form method="post" enctype="multipart/form-data" id="projectWizardForm" novalidate>
                    <input type="hidden" name="_csrf" value="<?= e($projectDraftCsrf) ?>">
                    <section class="wizard-step is-active" data-step="type" aria-labelledby="step-type-title"><p class="wizard-step-kicker">Primero, lo esencial</p><h2 id="step-type-title" tabindex="-1">¿Qué tipo de proyecto vas a crear?</h2><p class="wizard-step-help">Esto adapta los siguientes pasos y sus campos.</p>
                        <fieldset class="wizard-type-options"><legend class="sr-only">Tipo de proyecto</legend><?php foreach($catalogs['types'] as $key=>$item): ?><label><input type="radio" name="type" value="<?= e($key) ?>"<?= ($draft['type']??'')===$key?' checked':'' ?> required><span><i class="fa-solid <?= $key==='thesis'?'fa-graduation-cap':($key==='thesis_profile'?'fa-file-signature':($key==='pis'?'fa-puzzle-piece':($key==='practice'?'fa-building':'fa-people-group'))) ?>"></i><b><?= e($item['label']) ?></b><small>Ver campos requeridos para este tipo</small></span></label><?php endforeach; ?></fieldset><?= $error('type') ?>
                    </section>
                    <section class="wizard-step" data-step="details" aria-labelledby="step-details-title" hidden><p class="wizard-step-kicker">Identificación</p><h2 id="step-details-title" tabindex="-1">Datos principales</h2><div class="wizard-fields two-columns">
                        <label class="wide"><span>Título del proyecto</span><input name="title" value="<?= $v('title') ?>" maxlength="180" required><small>Claro y específico; máximo 180 caracteres.</small><?= $error('title') ?></label>
                        <label class="wide" data-description-field><span>Descripción breve</span><textarea name="description" rows="5"><?= $v('description') ?></textarea><small>Explica objetivo, alcance y resultado esperado.</small><?= $error('description') ?></label>
                        <label><span>Periodo académico</span><select name="period" required><option value="">Selecciona un periodo</option><?php foreach($catalogs['periods'] as $item): ?><option<?= $selected('period',$item) ?>><?= e($item) ?></option><?php endforeach; ?></select><?= $error('period') ?></label>
                        <label data-thesis-only><span>Modalidad</span><select name="modality"><option value="">Selecciona</option><?php foreach($catalogs['modalities'] as $key=>$label): ?><option value="<?= e($key) ?>"<?= $selected('modality',$key) ?>><?= e($label) ?></option><?php endforeach; ?></select><?= $error('modality') ?></label>
                        <label data-conditional="research_line"><span>Línea de investigación</span><select name="research_line"><option value="">Selecciona una línea temporal</option><?php foreach($catalogs['research_lines'] as $item): ?><option<?= $selected('research_line',$item) ?>><?= e($item) ?></option><?php endforeach; ?></select><?= $error('research_line') ?></label>
                    </div></section>
                    <section class="wizard-step" data-step="team" aria-labelledby="step-team-title" hidden><p class="wizard-step-kicker">Responsables</p><h2 id="step-team-title" tabindex="-1">Tutor y equipo</h2><div class="wizard-fields two-columns">
                        <label><span><?= $creationPolicy['actor_type']==='student'?'Tutor propuesto':'Docente responsable / tutor' ?></span><select name="tutor_id" required><option value="">Pendiente de asignación</option><?php foreach($catalogs['teachers'] as $teacher): ?><option value="<?= e($teacher['id']) ?>"<?= $selected('tutor_id',$teacher['id']) ?>><?= e($teacher['name']) ?></option><?php endforeach; ?></select><small><?= $creationPolicy['actor_type']==='student'?'La propuesta no constituye una asignación institucional definitiva.':'Disponible según la política del tipo de proyecto.' ?></small><?= $error('tutor_id') ?></label>
                        <?php if($creationPolicy['must_select_leader']): ?><label><span>Estudiante líder</span><select name="leader_id"><option value="">Selecciona al líder</option><?php foreach($catalogs['students'] as $student): ?><option value="<?= e($student['id']) ?>"<?= $selected('leader_id',$student['id']) ?>><?= e($student['name']) ?></option><?php endforeach; ?></select><?= $error('leader_id') ?></label><?php else: ?><div class="wizard-auto-role"><i class="fa-solid fa-user-check"></i><div><b>Eres la persona líder</b><span>Se te añadió automáticamente al equipo.</span></div></div><?php endif; ?>
                        <fieldset class="wide wizard-members"><legend>Integrantes <small>(opcional)</small></legend><p>Puedes continuar solo. Si necesitas un equipo, busca estudiantes matriculados en el semestre seleccionado.</p><div class="wizard-member-tools"><label><span>Semestre</span><select id="memberSemester"><?php foreach($catalogs['semesters'] as $key=>$label): ?><option value="<?= e($key) ?>"<?= $key==='6'?' selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label><span>Buscar estudiante</span><input id="memberSearch" type="search" placeholder="Escribe un nombre..."></label></div><div class="wizard-student-results" data-student-results><?php foreach($catalogs['students'] as $student): ?><label data-semester="<?= e($student['semester']) ?>" data-student-name="<?= e(mb_strtolower($student['name'])) ?>"><input type="checkbox" name="members[]" value="<?= e($student['id']) ?>"<?= $checkedMember($student['id']) ?><?= $creationPolicy['auto_leader']&&$student['id']==='student-1'?' disabled':'' ?>><span><b><?= e($student['name']) ?></b><small><?= e($catalogs['semesters'][$student['semester']]) ?></small></span></label><?php if($creationPolicy['auto_leader']&&$student['id']==='student-1'): ?><input type="hidden" name="members[]" value="student-1"><?php endif; ?><?php endforeach; ?></div><p class="wizard-no-students" data-no-students hidden>No encontramos estudiantes con ese nombre en el semestre.</p><?= $error('members') ?></fieldset>
                        <label class="wide"><span>Etiquetas</span><div class="wizard-tag-entry"><input id="tagInput" placeholder="Ej. innovación"><button type="button" data-add-tag>Agregar</button></div><div class="wizard-tags" data-tag-list><?php foreach($draft['tags']??[] as $tag): ?><span><?= e($tag) ?><input type="hidden" name="tags[]" value="<?= e($tag) ?>"><button type="button" aria-label="Eliminar etiqueta <?= e($tag) ?>">×</button></span><?php endforeach; ?></div><small>Hasta 8 etiquetas. Pulsa Enter o Agregar.</small></label>
                    </div></section>
                    <section class="wizard-step" data-step="files" aria-labelledby="step-files-title" hidden><p class="wizard-step-kicker">Documentación inicial</p><h2 id="step-files-title" tabindex="-1">Archivos del proyecto</h2><p class="wizard-step-help">Son opcionales en el borrador y no se almacenarán todavía.</p><label class="wizard-dropzone" for="projectFiles"><i class="fa-solid fa-cloud-arrow-up"></i><b>Selecciona PDF, DOCX o ZIP</b><span>Máximo <?= (int)$fileLimits['max_mb'] ?> MB por archivo y <?= (int)$fileLimits['max_total_mb'] ?> MB en total</span><input id="projectFiles" type="file" name="files[]" accept=".pdf,.docx,.zip" multiple></label><div class="wizard-file-list" data-file-list><p>No hay archivos seleccionados.</p></div><?= $error('files') ?><p class="wizard-file-warning"><i class="fa-solid fa-triangle-exclamation"></i> Los archivos no se guardan en sessionStorage; deberás volver a seleccionarlos al restaurar el borrador.</p></section>
                    <section class="wizard-step" data-step="confirm" aria-labelledby="step-confirm-title" hidden><p class="wizard-step-kicker">Última revisión</p><h2 id="step-confirm-title" tabindex="-1">Confirma tu borrador</h2><p class="wizard-step-help">El servidor volverá a validar todos los campos y archivos. No registrará el proyecto.</p><div class="wizard-confirmation" data-confirmation></div><div class="wizard-code-preview"><span>Código provisional</span><strong data-code-preview>TIT-<?= date('Y') ?>-XXXX</strong><small>El código único se generará automáticamente al registrar el proyecto.</small></div></section>
                    <footer class="wizard-actions"><button type="button" class="wizard-secondary" data-previous hidden><i class="fa-solid fa-arrow-left"></i> Anterior</button><span class="wizard-autosave-status" aria-live="polite"><i class="fa-solid fa-check"></i> Cambios guardados temporalmente</span><button type="button" class="wizard-primary" data-next>Siguiente <i class="fa-solid fa-arrow-right"></i></button><button type="submit" class="wizard-primary" data-submit hidden>Validar borrador <i class="fa-solid fa-check"></i></button></footer>
                </form>
            </section>
            <aside class="wizard-preview" aria-label="Vista previa del expediente"><p>Vista previa</p><h2>Expediente</h2><dl data-preview></dl><small><i class="fa-solid fa-wand-magic-sparkles"></i> Se actualiza mientras completas el formulario.</small></aside>
        </div>
    <?php endif; ?>
</main>
<script type="application/json" id="wizardConfig"><?= json_encode(['policy'=>$creationPolicy,'contract'=>$fieldContract,'types'=>$catalogs['types'],'fileLimits'=>$fileLimits,'serverErrors'=>$errors], JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
