CREATE TABLE IF NOT EXISTS project_review_representations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  file_id BIGINT UNSIGNED NOT NULL,
  project_file_version_id BIGINT UNSIGNED NULL,
  checksum_sha256 CHAR(64) NOT NULL,
  representation_type ENUM('libreoffice_pdf','supplemental_pdf') NOT NULL,
  storage_name VARCHAR(190) NOT NULL,
  storage_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NOT NULL DEFAULT 'application/pdf',
  size_bytes BIGINT UNSIGNED NOT NULL,
  pdf_checksum_sha256 CHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_review_representation_revision (file_id,checksum_sha256,representation_type),
  UNIQUE KEY uq_review_representation_storage (storage_name),
  KEY idx_review_representation_project (project_id,file_id,checksum_sha256),
  KEY idx_review_representation_version (project_file_version_id),
  CONSTRAINT fk_review_representation_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_review_representation_file FOREIGN KEY (file_id) REFERENCES project_files(id) ON DELETE CASCADE,
  CONSTRAINT fk_review_representation_version FOREIGN KEY (project_file_version_id) REFERENCES project_file_versions(id) ON DELETE SET NULL,
  CONSTRAINT fk_review_representation_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_review_representation_checksum CHECK (checksum_sha256 REGEXP '^[a-f0-9]{64}$'),
  CONSTRAINT chk_review_representation_pdf_checksum CHECK (pdf_checksum_sha256 REGEXP '^[a-f0-9]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
