ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL AFTER updated_at;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL AFTER deleted_at;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deletion_reason VARCHAR(500) NULL AFTER deleted_by;
ALTER TABLE users ADD COLUMN IF NOT EXISTS purged_at DATETIME NULL AFTER deletion_reason;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL AFTER deleted_at;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deletion_reason VARCHAR(500) NULL AFTER deleted_by;
