<?php
declare(strict_types=1);
define('ROOT_PATH',dirname(__DIR__,2));define('APP_PATH',ROOT_PATH.'/app');require APP_PATH.'/helpers.php';require APP_PATH.'/Core/Autoloader.php';Autoloader::register();
const MARKER='[QA_THESIS_MANAGEMENT_9]';
$command=$argv[1]??'report';$db=Database::connection();
if($command==='report'){report($db);exit;}
if($command==='cleanup'){if(($argv[2]??'')!=='--confirm')throw new RuntimeException('Usa cleanup --confirm.');cleanup($db);exit;}
if($command!=='seed')throw new RuntimeException('Uso: php scripts/qa/thesis-management-fixtures.php seed|report|cleanup --confirm');
$teachers=$db->query("SELECT u.id,tp.can_tutor,tp.can_manage_thesis FROM users u JOIN teacher_profiles tp ON tp.user_id=u.id WHERE u.status='active' AND u.deleted_at IS NULL ORDER BY u.id LIMIT 8")->fetchAll();$student=(int)$db->query("SELECT u.id FROM users u JOIN student_profiles sp ON sp.user_id=u.id WHERE u.status='active' AND u.deleted_at IS NULL ORDER BY u.id LIMIT 1")->fetchColumn();$period=(int)$db->query("SELECT id FROM academic_periods WHERE status='active' ORDER BY id DESC LIMIT 1")->fetchColumn();$career=(int)$db->query("SELECT id FROM careers WHERE is_active=1 ORDER BY id LIMIT 1")->fetchColumn();if(count($teachers)<5||$student<1||$period<1||$career<1)throw new RuntimeException('Faltan cuentas QA o catálogos activos para sembrar fixtures.');
$manager=(int)$teachers[0]['id'];$db->prepare('UPDATE teacher_profiles SET can_manage_thesis=1 WHERE user_id=:id')->execute(['id'=>$manager]);$type=(int)$db->query("SELECT id FROM project_types WHERE code='thesis'")->fetchColumn();$cases=[['QA — Tesis pendiente de Tribunal','approved',0],['QA — Tesis con Tribunal mínimo','approved',3],['QA — Tesis con Tribunal ampliado','approved',5],['QA — Tesis en defensa sin información','defense',3],['QA — Tesis en defensa con información','defense',3],['QA — Tesis no aprobada por Tribunal','defense',3],['QA — Tesis aprobada por Tribunal','tribunal_approved',3],['QA — Flujo completo de Titulación','approved',0]];
foreach($cases as [$title,$status,$members]){ $find=$db->prepare('SELECT id FROM projects WHERE subtitle=:m AND title=:t LIMIT 1');$find->execute(['m'=>MARKER,'t'=>$title]);if($find->fetchColumn())continue;$id=(new AdminProjectModel())->save(['title'=>$title,'subtitle'=>MARKER,'summary'=>MARKER,'project_type_id'=>$type,'career_id'=>$career,'academic_period_id'=>$period,'tutor_id'=>$manager,'status'=>'development','keywords'=>[]],0,$manager,true);Database::transaction(function(PDO $c)use($id,$student,$manager,$members,$teachers,$status):void{(new ProjectAuthorService())->sync($c,$id,[$student],$student);(new ProjectTutoringService())->sync($c,$id,[$manager],$manager,null);foreach(array_slice($teachers,1,$members) as $teacher)$c->prepare("INSERT INTO project_participants(project_id,user_id,role_code,permission_level,is_leader,status) VALUES(:p,:u,'tribunal','review',0,'active')")->execute(['p'=>$id,'u'=>$teacher['id']]);$c->prepare('UPDATE projects SET status=:s WHERE id=:id')->execute(['s'=>$status,'id'=>$id]);(new ProjectAuditService($c))->record($id,$manager,'qa_fixture_created','project',$id,null,['marker'=>MARKER]);}); }
// Complementary QA states require a pre-existing outcome; services are used where their lifecycle permits it.
$lookup=$db->prepare('SELECT id FROM projects WHERE subtitle=:m AND title=:t');
$lookup->execute(['m'=>MARKER,'t'=>'QA — Tesis en defensa con información']);if($id=(int)$lookup->fetchColumn())(new ThesisDefenseService())->save($id,['defense_date'=>'2026-12-15','defense_time'=>'10:00','location'=>'Sala QA','modality'=>'presential'],$manager);
$lookup->execute(['m'=>MARKER,'t'=>'QA — Tesis no aprobada por Tribunal']);if($id=(int)$lookup->fetchColumn())try{(new ThesisDefenseResultService())->save($id,'defense','rejected','Resultado QA controlado.',$manager);}catch(ThesisDefenseResultException $e){}
$lookup->execute(['m'=>MARKER,'t'=>'QA — Tesis aprobada por Tribunal']);if($id=(int)$lookup->fetchColumn()){$q=$db->prepare("INSERT INTO project_defenses(project_id,result,result_notes,result_registered_by,result_registered_at) SELECT :insert_id,'approved','Fixture QA histórico',:actor,CURRENT_TIMESTAMP WHERE NOT EXISTS(SELECT 1 FROM project_defenses WHERE project_id=:exists_id)");$q->execute(['insert_id'=>$id,'exists_id'=>$id,'actor'=>$manager]);}
report($db);
function report(PDO $db):void{$q=$db->prepare("SELECT p.id,p.code,p.title,p.status,p.tutor_id,GROUP_CONCAT(DISTINCT CASE WHEN pp.role_code IN ('tribunal','jury') AND pp.status='active' AND pp.removed_at IS NULL THEN pp.user_id END) tribunal_ids,pd.id defense_id,pd.attempt_number,pd.result FROM projects p LEFT JOIN project_participants pp ON pp.project_id=p.id LEFT JOIN project_defenses pd ON pd.project_id=p.id AND pd.attempt_number=(SELECT MAX(pd2.attempt_number) FROM project_defenses pd2 WHERE pd2.project_id=p.id) WHERE p.subtitle=:m GROUP BY p.id,pd.id,pd.attempt_number,pd.result ORDER BY p.id");$q->execute(['m'=>MARKER]);echo json_encode($q->fetchAll(),JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT).PHP_EOL;}
function cleanup(PDO $db):void{$q=$db->prepare('SELECT id FROM projects WHERE subtitle=:m');$q->execute(['m'=>MARKER]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id)Database::transaction(function(PDO $c)use($id):void{foreach(['notifications','project_defenses','project_participants','project_audit_log','project_files','project_deliveries'] as $t)$c->prepare("DELETE FROM {$t} WHERE project_id=:id")->execute(['id'=>$id]);$c->prepare('DELETE FROM projects WHERE id=:id AND subtitle=:m')->execute(['id'=>$id,'m'=>MARKER]);});}
