<?php
/**
 * Mockup unificado del asistente.
 * Cambiar este valor permite revisar una sola variante visual por vez.
 */
$wizardVisualState = 'review';
$differenceVisualState = 'complete'; // complete | no-changes | partial | unavailable
$comparisonQualityState = 'partial'; // complete | partial
$reviewStateVariants = [
    'reviewed' => ['icon' => 'fa-solid fa-circle-check', 'label' => 'Revisada'],
    'partial' => ['icon' => 'fa-solid fa-circle-half-stroke', 'label' => 'Revisión parcial'],
    'pending' => ['icon' => 'fa-regular fa-circle', 'label' => 'Pendiente'],
];
$structuralChangeVariants = [
    'section-added' => ['icon' => 'fa-solid fa-folder-plus', 'label' => 'Sección añadida'],
    'section-removed' => ['icon' => 'fa-solid fa-folder-minus', 'label' => 'Sección eliminada'],
    'section-renamed' => ['icon' => 'fa-solid fa-pen', 'label' => 'Sección renombrada'],
    'section-moved' => ['icon' => 'fa-solid fa-arrow-right-arrow-left', 'label' => 'Sección reubicada'],
    'table-added' => ['icon' => 'fa-solid fa-table', 'label' => 'Nueva tabla'],
    'table-removed' => ['icon' => 'fa-solid fa-table', 'label' => 'Tabla eliminada'],
    'image-added' => ['icon' => 'fa-regular fa-image', 'label' => 'Imagen incorporada'],
    'image-replaced' => ['icon' => 'fa-regular fa-images', 'label' => 'Imagen reemplazada'],
];
$visibleStructuralChanges = ['section-renamed', 'table-added', 'image-added'];
$wizardStages = ['Selección','Revisión','Confirmación','Finalización'];
$wizardStep = match ($wizardVisualState) {
    'selection-empty','selection-ready','validating','validation-success','validation-error','analyzing','analyzing-long','analysis-error' => 1,
    'review','abandon' => 2,
    'confirmation','register-error' => 3,
    'success' => 4,
    default => 1,
};
?>
<style>
.ed-version-wizard{width:min(900px,100%);color:var(--text)}.ed-wizard-intro{padding-bottom:18px;border-bottom:1px solid var(--line)}.ed-wizard-intro small{color:var(--muted);font-size:var(--font-xs);font-weight:850;letter-spacing:.08em;text-transform:uppercase}.ed-wizard-intro h2{margin:6px 0;font-size:18px}.ed-wizard-intro p{margin:0;color:var(--muted);font-size:var(--font-xs);line-height:1.6}
.ed-wizard-progress{display:grid;grid-template-columns:repeat(4,1fr);margin:22px 0 26px;padding:0;list-style:none}.ed-wizard-progress li{position:relative;display:grid;justify-items:center;gap:7px;color:var(--muted);font-size:var(--font-xs);text-align:center}.ed-wizard-progress li:not(:last-child)::after{position:absolute;top:13px;left:calc(50% + 15px);width:calc(100% - 30px);height:1px;background:var(--line);content:""}.ed-wizard-progress b{position:relative;z-index:1;width:27px;height:27px;border:1px solid var(--line);border-radius:50%;background:var(--surface);display:grid;place-items:center;color:var(--muted);font-size:var(--font-xs)}.ed-wizard-progress .is-complete b{border-color:color-mix(in srgb,var(--primary) 28%,var(--line));color:var(--primary)}.ed-wizard-progress .is-current{color:var(--text);font-weight:800}.ed-wizard-progress .is-current b{border-color:var(--primary);background:var(--primary);color:#fff}
.ed-wizard-shell{min-height:420px;padding:22px;border:1px solid var(--line);border-radius:11px}.ed-wizard-state-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.ed-wizard-state-title{display:grid;gap:4px}.ed-wizard-state-title small{color:var(--muted);font-size:var(--font-xs);font-weight:850;text-transform:uppercase}.ed-wizard-state-title h3{margin:0;font-size:var(--font-lg)}.ed-state-chip{padding:4px 8px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:var(--font-xs)}
.ed-wizard-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ed-document-reference{padding:13px;border-left:2px solid var(--line);background:var(--surface-soft);display:grid;gap:6px}.ed-document-reference small{color:var(--muted);font-size:var(--font-xs);text-transform:uppercase}.ed-document-reference strong{font-size:var(--font-xs)}.ed-document-reference span{color:var(--muted);font-size:var(--font-xs)}.ed-document-reference-actions{display:flex;gap:7px;margin-top:3px}
.ed-upload-zone{grid-column:1/-1;min-height:118px;border:1px dashed var(--line);border-radius:9px;display:grid;place-items:center;align-content:center;gap:7px;color:var(--muted);text-align:center}.ed-upload-zone i{font-size:22px}.ed-upload-zone strong{color:var(--text);font-size:var(--font-xs)}.ed-upload-zone span{font-size:var(--font-xs)}
.ed-wizard-button{height:32px;padding:0 10px;border:1px solid var(--line);border-radius:8px;background:transparent;color:var(--muted);font:inherit;font-size:var(--font-xs);font-weight:750}.ed-wizard-button:disabled{opacity:1}.ed-wizard-button.is-primary{border-color:var(--primary);background:var(--primary);color:#fff}.ed-wizard-button.is-primary.is-disabled{opacity:.45}
.ed-wizard-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:20px}.ed-wizard-actions div{display:flex;gap:7px}
.ed-auto-state{min-height:270px;display:grid;place-items:center;align-content:center;gap:12px;text-align:center}.ed-auto-spinner{width:36px;height:36px;border:3px solid var(--line);border-top-color:var(--primary);border-radius:50%}.ed-auto-state>i{width:38px;height:38px;border-radius:50%;background:var(--surface-soft);color:var(--primary);display:grid;place-items:center}.ed-auto-state h3{margin:0;font-size:var(--font-md)}.ed-auto-state p{max-width:560px;margin:0;color:var(--muted);font-size:var(--font-xs);line-height:1.6}.ed-auto-list{display:flex;flex-wrap:wrap;justify-content:center;gap:7px}.ed-auto-list span{padding:5px 8px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:var(--font-xs)}.ed-auto-list .is-ok{color:var(--primary)}
.ed-document-evolution{display:grid;grid-template-columns:1fr 34px 1fr;align-items:stretch;gap:10px}.ed-document-evolution .ed-document-reference{border-left:0;border:1px solid var(--line);border-radius:9px}.ed-evolution-arrow{display:grid;place-items:center;color:var(--primary);font-size:13px}.ed-difference-summary{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;margin-top:16px;padding:14px;border:1px solid var(--line);border-radius:9px}.ed-summary-copy h4,.ed-section-heading h4{margin:0;font-size:var(--font-xs)}.ed-summary-copy p{margin:5px 0 0;color:var(--muted);font-size:var(--font-xs)}.ed-summary-metrics{display:flex;flex-wrap:wrap;gap:7px;margin-top:11px}.ed-summary-metrics span{padding:5px 8px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:var(--font-xs)}.ed-comparison-level{align-self:start;padding:5px 8px;border-radius:999px;background:color-mix(in srgb,var(--primary) 8%,transparent);color:var(--primary);font-size:var(--font-xs);font-weight:800;white-space:nowrap}
.ed-difference-legend{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0 0}.ed-change-label{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:var(--font-xs);font-weight:750}.ed-change-label i{width:12px;text-align:center}.ed-change-label.is-added{color:#28704c}.ed-change-label.is-removed{color:#9b3c3c}.ed-change-label.is-modified{color:#7b5b16}.ed-change-label.is-manual{color:var(--primary)}
.ed-difference-tools{display:grid;grid-template-columns:1fr auto;gap:10px;margin:17px 0 12px}.ed-difference-search{height:32px;padding:0 10px;border:1px solid var(--line);border-radius:8px;background:transparent;color:var(--muted);font:inherit;font-size:var(--font-xs)}.ed-difference-filters{display:flex;flex-wrap:wrap;gap:5px}.ed-filter-chip{height:32px;padding:0 9px;border:1px solid var(--line);border-radius:8px;background:transparent;color:var(--muted);font:inherit;font-size:var(--font-xs)}.ed-filter-chip.is-active{border-color:var(--primary);color:var(--primary);font-weight:800}
.ed-section-list{display:grid;gap:8px}.ed-difference-section{border:1px solid var(--line);border-radius:9px;overflow:hidden}.ed-difference-section.is-important{border-left:3px solid var(--primary)}.ed-difference-section.is-secondary{opacity:.72}.ed-section-heading{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;padding:12px 13px}.ed-section-heading p{margin:5px 0 0;color:var(--muted);font-size:var(--font-xs)}.ed-section-action{display:flex;align-items:center;gap:8px}.ed-review-status{font-size:var(--font-xs);color:var(--muted);white-space:nowrap}.ed-review-status i{margin-right:4px}.ed-review-status.is-partial{padding:4px 7px;border:1px solid color-mix(in srgb,var(--primary) 28%,var(--line));border-radius:999px;color:var(--primary);font-weight:800}.ed-section-detail{display:grid;gap:10px;padding:13px;border-top:1px solid var(--line);background:color-mix(in srgb,var(--surface-soft) 65%,transparent)}.ed-fragment-pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ed-difference-fragment{padding:11px;border:1px solid var(--line);border-radius:8px;background:var(--surface)}.ed-difference-fragment header{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.ed-difference-fragment strong{font-size:var(--font-xs);text-transform:uppercase}.ed-difference-fragment p{margin:0;color:var(--muted);font-size:var(--font-xs);line-height:1.65}.ed-difference-fragment mark{padding:1px 2px;border-radius:3px;background:color-mix(in srgb,var(--primary) 13%,transparent);color:var(--text)}.ed-single-change{padding:10px;border-left:2px solid var(--line);background:var(--surface);font-size:var(--font-xs)}.ed-single-change p{margin:6px 0 0;color:var(--muted);line-height:1.6}.ed-single-change.is-added{border-left-color:#4d8b69}.ed-single-change.is-removed{border-left-color:#b05b5b}.ed-structure-changes{display:flex;flex-wrap:wrap;gap:6px}.ed-structure-changes span{padding:5px 8px;border:1px solid var(--line);border-radius:7px;color:var(--muted);font-size:var(--font-xs)}.ed-manual-review{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:11px;border-left:2px solid var(--primary);background:var(--surface)}.ed-manual-review p{margin:4px 0 0;color:var(--muted);font-size:var(--font-xs);line-height:1.55}.ed-view-actions{display:flex;flex-wrap:wrap;gap:6px}.ed-empty-comparison{margin-top:16px;padding:30px 18px;border:1px dashed var(--line);border-radius:9px;text-align:center}.ed-empty-comparison i{color:var(--primary)}.ed-empty-comparison h4{margin:9px 0 5px;font-size:var(--font-sm)}.ed-empty-comparison p{max-width:560px;margin:0 auto;color:var(--muted);font-size:var(--font-xs);line-height:1.6}
.ed-accuracy-note{margin:14px 0 0;padding:10px;border-left:2px solid var(--line);background:var(--surface-soft);color:var(--muted);font-size:var(--font-xs);line-height:1.55}.ed-optional-note{display:grid;gap:6px;margin-top:14px}.ed-optional-note label{font-size:var(--font-xs);font-weight:800}.ed-optional-note textarea{min-height:64px;padding:10px;border:1px solid var(--line);border-radius:8px;resize:none;background:transparent;color:var(--muted);font:inherit;font-size:var(--font-xs);line-height:1.5}.ed-optional-note small{color:var(--muted);font-size:var(--font-xs)}
.ed-confirmation{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 28px}.ed-confirmation div{display:grid;grid-template-columns:115px 1fr;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.ed-confirmation dt{color:var(--muted);font-size:var(--font-xs)}.ed-confirmation dd{margin:0;font-size:var(--font-xs);font-weight:750}.ed-unregistered-note{margin-top:15px;padding:10px;border-left:2px solid var(--line);background:var(--surface-soft);color:var(--muted);font-size:var(--font-xs)}.ed-acceptance{display:flex;align-items:flex-start;gap:9px;margin-top:14px;color:var(--muted);font-size:var(--font-xs);line-height:1.5}.ed-acceptance span:first-child{width:15px;height:15px;border:1px solid var(--line);border-radius:3px;flex:0 0 auto}
.ed-abandon-box{max-width:560px;margin:40px auto;padding:20px;border:1px solid var(--line);border-radius:10px;text-align:center}.ed-abandon-box i{color:var(--muted);font-size:22px}.ed-abandon-box h3{margin:10px 0 7px;font-size:var(--font-md)}.ed-abandon-box p{margin:0;color:var(--muted);font-size:var(--font-xs);line-height:1.6}.ed-abandon-box .ed-wizard-actions{justify-content:center}
.ed-result{min-height:300px;display:grid;place-items:center;align-content:center;gap:9px;text-align:center}.ed-result>i{width:42px;height:42px;border-radius:50%;background:color-mix(in srgb,var(--primary) 10%,transparent);color:var(--primary);display:grid;place-items:center}.ed-result.is-error>i{color:var(--muted);background:var(--surface-soft)}.ed-result h3{margin:0;font-size:var(--font-lg)}.ed-result p{max-width:520px;margin:0;color:var(--muted);font-size:var(--font-xs);line-height:1.6}.ed-result-data{display:flex;flex-wrap:wrap;justify-content:center;gap:7px;margin-top:5px}.ed-result-data span{padding:5px 8px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:var(--font-xs)}
.ed-mobile-step{display:none;margin:0 0 18px;color:var(--muted);font-size:var(--font-xs);font-weight:800}
@media(max-width:700px){.ed-wizard-progress{display:none}.ed-mobile-step{display:block}.ed-wizard-grid,.ed-confirmation,.ed-difference-summary,.ed-difference-tools,.ed-fragment-pair{grid-template-columns:1fr}.ed-confirmation div{grid-template-columns:105px 1fr}.ed-wizard-shell{padding:18px}.ed-comparison-level{justify-self:start}.ed-section-heading{align-items:start}.ed-section-action{align-items:flex-end;flex-direction:column}.ed-manual-review{grid-template-columns:1fr}}
@media(max-width:520px){.ed-document-evolution{grid-template-columns:1fr}.ed-evolution-arrow{height:18px;transform:rotate(90deg)}}
@media(max-width:430px){.ed-wizard-state-head{flex-direction:column}.ed-wizard-actions{align-items:stretch;flex-direction:column-reverse}.ed-wizard-actions div{width:100%}.ed-wizard-actions .ed-wizard-button{flex:1}.ed-document-reference-actions{flex-wrap:wrap}}
</style>

<div class="ed-version-wizard">
 <header class="ed-wizard-intro"><small>Registro documental guiado</small><h2>Registrar una nueva versión</h2><p>El documento será revisado y confirmado antes de incorporarse a la Evolución Documental.</p></header>
 <ol class="ed-wizard-progress"><?php foreach($wizardStages as $index=>$stage):$number=$index+1;?><li class="<?=$number<$wizardStep?'is-complete':($number===$wizardStep?'is-current':'')?>"><b><?=$number<$wizardStep?'✓':$number?></b><span><?=e($stage)?></span></li><?php endforeach;?></ol>
 <p class="ed-mobile-step">Paso <?=$wizardStep?> de 4 · <?=e($wizardStages[$wizardStep-1])?></p>
 <main class="ed-wizard-shell">
 <?php if(in_array($wizardVisualState,['selection-empty','selection-ready'],true)): $ready=$wizardVisualState==='selection-ready';?>
  <header class="ed-wizard-state-head"><div class="ed-wizard-state-title"><small>Etapa 1 de 4</small><h3>Seleccionar nueva versión</h3></div><span class="ed-state-chip">Sin guardar</span></header>
  <div class="ed-wizard-grid"><article class="ed-document-reference"><small>Documento actual</small><strong>Informe_v3.docx</strong><span>Versión 3 · DOCX · 2,8 MB</span></article><article class="ed-document-reference"><small>Nueva versión</small><strong><?=$ready?'Informe_v4.docx':'Documento pendiente'?></strong><span><?=$ready?'DOCX · 3,1 MB':'Formatos permitidos: DOCX y PDF · máximo 20 MB'?></span><?php if($ready):?><div class="ed-document-reference-actions"><button class="ed-wizard-button" disabled>Sustituir</button><button class="ed-wizard-button" disabled>Retirar</button></div><?php endif;?></article><?php if(!$ready):?><div class="ed-upload-zone"><i class="fa-solid fa-cloud-arrow-up"></i><strong>Seleccionar nueva versión</strong><span>DOCX o PDF · hasta 20 MB</span></div><?php endif;?></div>
  <nav class="ed-wizard-actions"><button class="ed-wizard-button" disabled>Cancelar</button><button class="ed-wizard-button is-primary<?=$ready?'':' is-disabled'?>" disabled>Continuar</button></nav>
 <?php elseif($wizardVisualState==='validating'):?>
  <div class="ed-auto-state"><span class="ed-auto-spinner"></span><h3>Validando documento...</h3><div class="ed-auto-list"><span>Validando formato...</span><span>Comprobando compatibilidad...</span><span>Verificando que el archivo sea diferente...</span></div><p>La versión todavía no ha sido registrada.</p></div>
 <?php elseif($wizardVisualState==='validation-success'):?>
  <div class="ed-auto-state"><i class="fa-solid fa-check"></i><h3>Documento validado correctamente</h3><div class="ed-auto-list"><span class="is-ok">Formato válido</span><span class="is-ok">Documento compatible</span><span class="is-ok">Archivo diferente</span><span class="is-ok">Peso permitido</span></div><p>El análisis comenzará automáticamente. La versión todavía no ha sido registrada.</p></div>
 <?php elseif($wizardVisualState==='validation-error'):?>
  <div class="ed-auto-state"><i class="fa-solid fa-triangle-exclamation"></i><h3>No fue posible validar el documento</h3><div class="ed-auto-list"><span>Formato no permitido</span><span>El archivo coincide con la versión actual</span></div><p>Selecciona otro archivo para continuar con el registro.</p><div><button class="ed-wizard-button is-primary" disabled>Volver a seleccionar archivo</button> <button class="ed-wizard-button" disabled>Cancelar</button></div></div>
 <?php elseif(in_array($wizardVisualState,['analyzing','analyzing-long'],true)):?>
  <div class="ed-auto-state"><span class="ed-auto-spinner"></span><h3>Analizando documento...</h3><div class="ed-auto-list"><span>Comparando con la versión anterior...</span><span>Preparando el resumen de cambios...</span></div><p><?=$wizardVisualState==='analyzing-long'?'El análisis está tomando más tiempo de lo habitual. No cierres esta pantalla.':'El archivo todavía no ha sido registrado.'?></p></div>
 <?php elseif($wizardVisualState==='analysis-error'):?>
  <div class="ed-auto-state"><i class="fa-solid fa-triangle-exclamation"></i><h3>El análisis no pudo completarse</h3><p>No fue posible identificar todas las diferencias automáticamente. Aún puedes revisar y registrar la nueva versión.</p><div><button class="ed-wizard-button" disabled>Reintentar análisis</button> <button class="ed-wizard-button is-primary" disabled>Continuar sin comparación</button> <button class="ed-wizard-button" disabled>Cancelar</button></div></div>
 <?php elseif($wizardVisualState==='review'):?>
  <header class="ed-wizard-state-head"><div class="ed-wizard-state-title"><small>Etapa 2 de 4</small><h3>Revisar diferencias</h3></div><span class="ed-state-chip">Ayuda de revisión</span></header>
  <div class="ed-document-evolution"><article class="ed-document-reference"><small>Documento anterior</small><strong>Informe_v3.docx</strong><span>Versión 3 · DOCX · 2,8 MB</span></article><span class="ed-evolution-arrow" aria-hidden="true"><i class="fa-solid fa-arrow-right"></i></span><article class="ed-document-reference"><small>Documento nuevo</small><strong>Informe_v4.docx</strong><span>Versión 4 · DOCX · 3,1 MB</span></article></div>
  <?php if($differenceVisualState==='complete'):?>
   <section class="ed-difference-summary"><div class="ed-summary-copy"><h4>Resumen general</h4><p>Esta síntesis permite identificar primero el alcance de la nueva versión.</p><div class="ed-summary-metrics"><span>4 páginas añadidas</span><span>3 secciones modificadas</span><span>1 tabla incorporada</span><span>2 párrafos eliminados</span><span>8 cambios textuales</span></div></div><span class="ed-comparison-level"><i class="fa-solid <?=$comparisonQualityState==='complete'?'fa-circle-check':'fa-circle-half-stroke'?>"></i> <?=$comparisonQualityState==='complete'?'Comparación completa':'Comparación parcial'?></span></section>
   <div class="ed-difference-legend" aria-label="Tipos de cambio"><span class="ed-change-label is-added"><i class="fa-solid fa-plus"></i>Añadido</span><span class="ed-change-label is-removed"><i class="fa-solid fa-minus"></i>Eliminado</span><span class="ed-change-label is-modified"><i class="fa-solid fa-pen"></i>Modificado</span><span class="ed-change-label"><i class="fa-solid fa-equals"></i>Sin cambios relevantes</span><span class="ed-change-label is-manual"><i class="fa-solid fa-eye"></i>Revisión manual</span></div>
   <div class="ed-difference-tools"><input class="ed-difference-search" type="text" placeholder="Buscar dentro de los cambios..." disabled><div class="ed-difference-filters"><button class="ed-filter-chip is-active" disabled>Todos</button><button class="ed-filter-chip" disabled>Añadidos</button><button class="ed-filter-chip" disabled>Eliminados</button><button class="ed-filter-chip" disabled>Modificados</button><button class="ed-filter-chip" disabled>Requieren revisión</button></div></div>
   <div class="ed-section-list">
    <section class="ed-difference-section"><header class="ed-section-heading"><div><h4>Planteamiento del problema</h4><p>2 cambios detectados · Predominan modificaciones</p></div><div class="ed-section-action"><span class="ed-review-status"><i class="fa-regular fa-circle"></i>Pendiente</span><button class="ed-wizard-button" disabled>Ver cambios</button></div></header></section>
    <section class="ed-difference-section is-important"><header class="ed-section-heading"><div><h4>Metodología</h4><p>5 cambios detectados · 2 añadidos · 1 eliminado · 2 modificados</p></div><div class="ed-section-action"><span class="ed-review-status is-partial"><i class="<?=e($reviewStateVariants['partial']['icon'])?>"></i><?=e($reviewStateVariants['partial']['label'])?></span><button class="ed-wizard-button" disabled>Ocultar detalle</button></div></header>
     <div class="ed-section-detail">
      <div class="ed-fragment-pair"><article class="ed-difference-fragment"><header><strong>Contenido anterior</strong><span class="ed-change-label is-removed"><i class="fa-solid fa-minus"></i>Anterior</span></header><p>La investigación utilizará un enfoque descriptivo.</p></article><article class="ed-difference-fragment"><header><strong>Contenido nuevo</strong><span class="ed-change-label is-modified"><i class="fa-solid fa-pen"></i>Modificado</span></header><p>La investigación utilizará un enfoque descriptivo <mark>y analítico</mark>.</p></article></div>
      <article class="ed-single-change is-added"><span class="ed-change-label is-added"><i class="fa-solid fa-plus"></i>Contenido añadido</span><p>“Se aplicará una entrevista dirigida a los docentes de la carrera.” Este fragmento no aparecía en la versión anterior.</p></article>
      <article class="ed-single-change is-removed"><span class="ed-change-label is-removed"><i class="fa-solid fa-minus"></i>Contenido eliminado</span><p>“La población estará conformada exclusivamente por estudiantes.” Este contenido ya no aparece en la nueva versión.</p></article>
      <div class="ed-structure-changes" aria-label="Cambios estructurales detectados"><?php foreach($visibleStructuralChanges as $changeKey):$structuralChange=$structuralChangeVariants[$changeKey];?><span><i class="<?=e($structuralChange['icon'])?>"></i> <?=e($structuralChange['label'])?></span><?php endforeach;?></div>
      <div class="ed-manual-review"><div><span class="ed-change-label is-manual"><i class="fa-solid fa-eye"></i>Revisión manual requerida</span><p>Se detectó una modificación en un bloque extenso, pero no fue posible identificar todos los cambios. Se muestra únicamente un fragmento representativo.</p></div><div class="ed-view-actions"><button class="ed-wizard-button" disabled>Ver fragmento completo</button><button class="ed-wizard-button" disabled>Ver versión anterior</button><button class="ed-wizard-button" disabled>Ver versión nueva</button></div></div>
     </div>
    </section>
    <section class="ed-difference-section is-secondary"><header class="ed-section-heading"><div><h4>Resultados</h4><p>Sin cambios textuales relevantes</p></div><div class="ed-section-action"><span class="ed-review-status"><i class="fa-solid fa-check"></i>Revisada</span><button class="ed-wizard-button" disabled>Ver sección</button></div></header></section>
    <section class="ed-difference-section"><header class="ed-section-heading"><div><h4>Conclusiones</h4><p>1 cambio detectado · Sección renombrada</p></div><div class="ed-section-action"><span class="ed-review-status"><i class="fa-regular fa-circle"></i>Pendiente</span><button class="ed-wizard-button" disabled>Ver cambios</button></div></header></section>
   </div>
  <?php elseif($differenceVisualState==='no-changes'):?>
   <section class="ed-empty-comparison"><i class="fa-solid fa-equals"></i><h4>No se detectaron cambios textuales relevantes</h4><p>Pueden existir diferencias de formato, imágenes o metadatos que no forman parte de esta comparación.</p></section>
  <?php elseif($differenceVisualState==='partial'):?>
   <section class="ed-empty-comparison"><i class="fa-solid fa-eye"></i><h4>Comparación parcial</h4><p>Se identificaron diferencias en parte del documento. Recomendamos consultar ambas versiones para verificar los cambios restantes.</p><div class="ed-view-actions" style="justify-content:center;margin-top:12px"><button class="ed-wizard-button" disabled>Ver versión anterior</button><button class="ed-wizard-button" disabled>Ver versión nueva</button></div></section>
  <?php else:?>
   <section class="ed-empty-comparison"><i class="fa-solid fa-file-circle-xmark"></i><h4>Comparación detallada no disponible</h4><p>No fue posible generar una comparación textual detallada porque el archivo puede estar escaneado, protegido o no contener texto extraíble. Puedes consultar ambas versiones y continuar con el registro.</p><div class="ed-view-actions" style="justify-content:center;margin-top:12px"><button class="ed-wizard-button" disabled>Ver versión anterior</button><button class="ed-wizard-button" disabled>Ver versión nueva</button></div></section>
  <?php endif;?>
  <p class="ed-accuracy-note"><i class="fa-solid fa-circle-info"></i> Los cambios fueron identificados automáticamente y pueden requerir verificación.</p>
  <div class="ed-optional-note"><label>Observación opcional</label><textarea disabled>Se incorporaron las correcciones solicitadas por el tutor.</textarea><small>No necesitas describir manualmente todos los cambios.</small></div>
  <nav class="ed-wizard-actions"><button class="ed-wizard-button" disabled>Volver</button><div><button class="ed-wizard-button" disabled>Cancelar</button><button class="ed-wizard-button is-primary" disabled>Continuar</button></div></nav>
 <?php elseif($wizardVisualState==='confirmation'):?>
  <header class="ed-wizard-state-head"><div class="ed-wizard-state-title"><small>Etapa 3 de 4</small><h3>Confirmar registro</h3></div><span class="ed-state-chip">Pendiente</span></header>
  <dl class="ed-confirmation"><div><dt>Versión anterior</dt><dd>Versión 3</dd></div><div><dt>Nueva versión</dt><dd>Versión 4</dd></div><div><dt>Documento</dt><dd>Informe_v4.docx</dd></div><div><dt>Formato y peso</dt><dd>DOCX · 3,1 MB</dd></div><div><dt>Estado</dt><dd>En revisión</dd></div><div><dt>Cambios</dt><dd>3 secciones modificadas</dd></div><div><dt>Observación</dt><dd>Correcciones solicitadas incorporadas</dd></div></dl>
  <p class="ed-unregistered-note">La nueva versión todavía no ha sido registrada.</p><label class="ed-acceptance"><span></span><span>He revisado la información y confirmo el registro de esta versión.</span></label>
  <nav class="ed-wizard-actions"><button class="ed-wizard-button" disabled>Volver</button><div><button class="ed-wizard-button" disabled>Cancelar</button><button class="ed-wizard-button is-primary" disabled>Registrar versión</button></div></nav>
 <?php elseif($wizardVisualState==='abandon'):?>
  <section class="ed-abandon-box"><i class="fa-solid fa-triangle-exclamation"></i><h3>¿Descartar esta versión?</h3><p>Esta versión todavía no se ha registrado. Si abandonas el proceso, la selección y el análisis serán descartados.</p><nav class="ed-wizard-actions"><button class="ed-wizard-button is-primary" disabled>Continuar revisando</button><button class="ed-wizard-button" disabled>Descartar versión</button></nav></section>
 <?php elseif($wizardVisualState==='success'):?>
  <section class="ed-result"><i class="fa-solid fa-check"></i><h3>Nueva versión registrada correctamente</h3><div class="ed-result-data"><span>Versión 4</span><span>Informe_v4.docx</span><span>En revisión</span></div><p>La Evolución Documental fue actualizada y la nueva versión quedó preparada para revisión.</p><div><button class="ed-wizard-button is-primary" disabled>Ver evolución documental</button> <button class="ed-wizard-button" disabled>Ver versión registrada</button></div></section>
 <?php else:?>
  <section class="ed-result is-error"><i class="fa-solid fa-triangle-exclamation"></i><h3>No fue posible registrar la nueva versión</h3><p>El documento no fue incorporado al expediente. Puedes intentarlo nuevamente o cancelar el proceso.</p><div><button class="ed-wizard-button is-primary" disabled>Intentar nuevamente</button> <button class="ed-wizard-button" disabled>Cancelar</button></div></section>
 <?php endif;?>
 </main>
</div>
