<?php
/** Simulación visual compartida de versiones académicas documentales. */
$documentVersions = [
 ['level'=>'initial','version'=>'Versión 1','date'=>'12 de mayo de 2026','time'=>'09:20','user'=>'María Torres','file'=>'Informe_v1.docx','format'=>'DOCX','status'=>'En revisión','observations'=>[['actor'=>'Tutor','text'=>'Precisar el planteamiento del problema y ampliar los antecedentes.']]],
 ['level'=>'intermediate','version'=>'Versión 2','date'=>'28 de mayo de 2026','time'=>'16:45','user'=>'María Torres','file'=>'Informe_v2.docx','format'=>'DOCX','status'=>'Requiere cambios','observations'=>[['actor'=>'Tutor','text'=>'Corregir la metodología y justificar la selección de la muestra.'],['actor'=>'Estudiante','text'=>'Correcciones metodológicas incorporadas para una nueva revisión.']]],
 ['level'=>'intermediate','version'=>'Versión 3','date'=>'18 de junio de 2026','time'=>'11:10','user'=>'María Torres','file'=>'Informe_v3.docx','format'=>'DOCX','status'=>'Aprobado','observations'=>[['actor'=>'Tutor','text'=>'Documento aprobado para preparar la versión final.']]],
 ['level'=>'published','version'=>'Versión final','date'=>'15 de julio de 2026','time'=>'14:30','user'=>'Repositorio Institucional','file'=>'Informe_Final.pdf','format'=>'PDF','status'=>'Publicado','observations'=>[]],
];
?>
<style>
.ed-evolution{width:min(900px,100%);color:var(--text)}.ed-evolution-tools{display:flex;align-items:center;justify-content:space-between;gap:18px;padding-bottom:20px;border-bottom:1px solid var(--line)}
.ed-version-filters{display:flex;align-items:center;gap:6px;overflow-x:auto;scrollbar-width:none}.ed-version-filters::-webkit-scrollbar{display:none}.ed-version-filter{height:31px;padding:0 10px;border:1px solid var(--line);border-radius:999px;background:transparent;color:var(--muted);font:inherit;font-size:10px;font-weight:750;white-space:nowrap}.ed-version-filter:disabled{opacity:1}.ed-version-filter.is-active{border-color:color-mix(in srgb,var(--primary) 28%,var(--line));color:var(--text)}
.ed-version-search{width:min(250px,100%);height:33px;padding:0 10px;border:1px solid var(--line);border-radius:8px;display:flex;align-items:center;gap:8px;color:var(--muted)}.ed-version-search input{width:100%;border:0;outline:0;background:transparent;color:var(--muted);font:inherit;font-size:11px}
.ed-timeline{position:relative;display:grid;gap:20px;margin-top:24px;padding-left:38px}.ed-timeline::before{position:absolute;top:18px;bottom:18px;left:11px;width:2px;border-radius:2px;background:linear-gradient(to bottom,var(--line),color-mix(in srgb,var(--primary) 32%,var(--line)));content:""}.ed-version-node{position:relative}.ed-version-marker{position:absolute;top:17px;left:-34px;width:16px;height:16px;border:4px solid var(--surface);border-radius:50%;background:var(--muted);box-shadow:0 0 0 1px var(--line)}.ed-version-node.is-initial .ed-version-marker{background:var(--surface);box-shadow:0 0 0 2px var(--muted)}.ed-version-node.is-published .ed-version-marker{background:var(--primary);box-shadow:0 0 0 2px color-mix(in srgb,var(--primary) 24%,transparent)}
.ed-version-card{padding:17px 18px;border:1px solid var(--line);border-radius:11px;background:var(--surface)}.ed-version-node.is-initial .ed-version-card{border-style:dashed;background:transparent}.ed-version-node.is-published .ed-version-card{padding-top:18px;padding-bottom:18px;border-color:color-mix(in srgb,var(--primary) 34%,var(--line));background:color-mix(in srgb,var(--primary) 5%,var(--surface))}
.ed-version-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.ed-version-title{display:grid;gap:5px}.ed-version-title small{color:var(--muted);font-size:9px;font-weight:850;letter-spacing:.08em;text-transform:uppercase}.ed-version-title h2{margin:0;font-size:15px}.ed-version-date{color:var(--muted);font-size:10px;text-align:right;white-space:nowrap}
.ed-version-meta{display:flex;align-items:center;flex-wrap:wrap;gap:7px;margin-top:12px;color:var(--muted);font-size:10px}.ed-version-meta i{font-size:3px}.ed-version-status{padding:4px 8px;border:1px solid var(--line);border-radius:999px;font-weight:800}.ed-version-node.is-published .ed-version-status{border-color:color-mix(in srgb,var(--primary) 28%,var(--line));color:var(--primary)}
.ed-version-document{margin-top:14px;padding-top:13px;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:12px}.ed-version-file{min-width:0;display:flex;align-items:center;gap:9px}.ed-version-file i{color:var(--primary)}.ed-version-file span{min-width:0;display:grid;gap:3px}.ed-version-file strong{overflow:hidden;font-size:11px;text-overflow:ellipsis;white-space:nowrap}.ed-version-file small{color:var(--muted);font-size:9px}.ed-version-file-action{height:29px;padding:0 9px;border:1px solid var(--line);border-radius:7px;background:transparent;color:var(--muted);font:inherit;font-size:9px;font-weight:750}.ed-version-file-action:disabled{opacity:1}
.ed-version-observations{position:relative;display:grid;gap:8px;margin-top:13px}.ed-version-observation{position:relative;display:grid;grid-template-columns:72px 1fr;gap:10px;padding:9px 10px;border-left:2px solid var(--line);background:var(--surface-soft)}.ed-version-observation+ .ed-version-observation{border-left-color:color-mix(in srgb,var(--primary) 28%,var(--line))}.ed-version-observation+ .ed-version-observation::before{position:absolute;top:-9px;left:-2px;width:2px;height:9px;background:var(--line);content:""}.ed-version-observation strong{font-size:10px}.ed-version-observation p{margin:0;color:var(--muted);font-size:10px;line-height:1.55}
.ed-evolution-empty{margin-top:28px;padding:30px 18px;border-top:1px solid var(--line);color:var(--muted);display:grid;justify-items:center;gap:8px;text-align:center}.ed-evolution-empty i{font-size:18px}.ed-evolution-empty strong{color:var(--text);font-size:12px}.ed-evolution-empty p{margin:0;font-size:10px}
@media(max-width:680px){.ed-evolution-tools{align-items:stretch;flex-direction:column}.ed-version-search{width:100%}.ed-timeline{padding-left:28px}.ed-timeline::before{left:7px}.ed-version-marker{left:-26px}.ed-version-head{flex-direction:column}.ed-version-date{text-align:left}.ed-version-observation{grid-template-columns:1fr;gap:4px}}
</style>
<div class="ed-evolution">
 <header class="ed-evolution-tools"><nav class="ed-version-filters" aria-label="Filtrar versiones"><button class="ed-version-filter is-active" disabled>Todas</button><button class="ed-version-filter" disabled>En revisión</button><button class="ed-version-filter" disabled>Aprobadas</button><button class="ed-version-filter" disabled>Publicada</button></nav><label class="ed-version-search"><i class="fa-solid fa-magnifying-glass"></i><span class="sr-only">Buscar versión</span><input type="search" placeholder="Buscar versión..." readonly aria-disabled="true"></label></header>
 <section class="ed-timeline" aria-label="Evolución de versiones">
 <?php foreach($documentVersions as $version): ?><article class="ed-version-node is-<?=e($version['level'])?>"><span class="ed-version-marker"></span><div class="ed-version-card">
  <header class="ed-version-head"><div class="ed-version-title"><small><?=$version['level']==='initial'?'Versión inicial':($version['level']==='published'?'Versión publicada':'Versión intermedia')?></small><h2><?=e($version['version'])?></h2></div><time class="ed-version-date"><?=e($version['date'])?><br><?=e($version['time'])?></time></header>
  <div class="ed-version-meta"><span><?=e($version['user'])?></span><i class="fa-solid fa-circle"></i><span class="ed-version-status"><?=e($version['status'])?></span></div>
  <div class="ed-version-document"><div class="ed-version-file"><i class="fa-solid <?=$version['format']==='PDF'?'fa-file-pdf':'fa-file-word'?>"></i><span><strong><?=e($version['file'])?></strong><small><?=e($version['format'])?></small></span></div><button class="ed-version-file-action" disabled>Ver versión</button></div>
  <?php if($version['observations']!==[]):?><div class="ed-version-observations"><?php foreach($version['observations'] as $observation):?><article class="ed-version-observation"><strong><?=e($observation['actor'])?></strong><p>“<?=e($observation['text'])?>”</p></article><?php endforeach;?></div><?php endif;?>
 </div></article><?php endforeach;?>
 </section>
 <section class="ed-evolution-empty" aria-label="Ejemplo sin versiones"><i class="fa-solid fa-clock-rotate-left"></i><strong>Aún no existen versiones registradas</strong><p>La evolución documental aparecerá cuando este expediente registre una nueva versión.</p></section>
</div>
