<style>
.sma-overlay{position:fixed;inset:0;z-index:14000;padding:18px;background:rgba(15,23,42,.65);display:grid;place-items:center}.sma-overlay[hidden]{display:none!important}.sma-dialog{width:min(520px,100%);max-height:calc(100dvh - 36px);border:1px solid var(--line);border-radius:15px;background:var(--surface);box-shadow:0 24px 70px rgba(15,23,42,.3);overflow:auto}.sma-dialog>header{padding:17px 19px;border-bottom:1px solid var(--line);display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.sma-dialog h2{margin:0;font-size:18px}.sma-dialog header p{margin:6px 0 0;color:var(--muted);font-size:13px;line-height:1.55}.sma-dialog header button{width:42px;height:42px;flex:0 0 auto;border:0;border-radius:9px;background:var(--surface-soft);color:var(--text)}.sma-body{padding:20px 19px}.sma-field{display:grid;gap:7px}.sma-field label{font-size:12px;font-weight:800}.sma-field select,.sma-field textarea{width:100%;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--surface-soft);color:var(--text);font:inherit}.sma-field textarea{resize:vertical}.sma-field[hidden],.sma-step[hidden]{display:none!important}.sma-confirm{display:grid;gap:12px}.sma-confirm>i{width:48px;height:48px;margin:auto;border-radius:13px;background:#fef2f2;color:#b91c1c;display:grid;place-items:center;font-size:18px}.sma-warning{margin:0;color:var(--muted);font-size:13px;line-height:1.6;text-align:center}.sma-summary{margin:0;display:grid;gap:8px}.sma-summary>div{padding:10px 11px;border:1px solid var(--line);border-radius:9px;background:var(--surface-soft)}.sma-summary dt{color:var(--muted);font-size:11px;font-weight:700}.sma-summary dd{margin:3px 0 0;font-size:13px;font-weight:750;overflow-wrap:anywhere}.sma-error{margin:12px 0 0;padding:9px;border-radius:8px;background:#fef2f2;color:#b91c1c;font-size:12px}.sma-dialog>footer{padding:13px 19px;border-top:1px solid var(--line);display:flex;justify-content:flex-end;gap:9px}.sma-button{min-height:42px;padding:0 15px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--text);font:inherit;font-size:13px;font-weight:800}.sma-button.is-danger{border-color:#b91c1c;background:#b91c1c;color:#fff}.sma-button:disabled{opacity:.5;cursor:not-allowed}html.sma-open,body.sma-open{overflow:hidden}
@media(max-width:620px){.sma-overlay{padding:12px}.sma-dialog>footer{display:grid;grid-template-columns:1fr}.sma-button{width:100%}}
/* El selector nativo debe escapar del recorte interno del diálogo. */
.sma-overlay{overflow-y:auto;overscroll-behavior:contain}
.sma-dialog{position:relative;z-index:1;max-height:none;overflow:visible;isolation:isolate}
.sma-dialog>header{position:relative;z-index:1;border-radius:15px 15px 0 0;background:var(--surface)}
.sma-body{position:relative;z-index:3;overflow:visible;background:var(--surface)}
.sma-step,.sma-field{position:relative;overflow:visible}
.sma-field{z-index:5}
.sma-field select{position:relative;z-index:7;max-width:100%}
.sma-dialog>footer{position:relative;z-index:1;border-radius:0 0 15px 15px;background:var(--surface)}
.sma-combobox{width:100%;min-height:42px;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--surface-soft);color:var(--text);display:flex;align-items:center;justify-content:space-between;gap:12px;text-align:left;font:inherit}.sma-combobox:focus-visible{border-color:var(--primary);outline:3px solid color-mix(in srgb,var(--primary) 20%,transparent)}.sma-combobox-list{position:fixed;z-index:15050;max-height:min(280px,45vh);padding:5px;border:1px solid var(--line);border-radius:10px;background:var(--surface);box-shadow:0 18px 44px rgba(15,23,42,.28);overflow-y:auto;overscroll-behavior:contain}.sma-combobox-list[hidden]{display:none!important}.sma-combobox-option{width:100%;min-height:42px;padding:8px 10px;border:0;border-radius:7px;background:transparent;color:var(--text);display:flex;align-items:center;font:inherit;font-size:13px;text-align:left}.sma-combobox-option:hover,.sma-combobox-option.is-active{background:var(--surface-soft);color:var(--primary)}.sma-combobox-option[aria-selected=true]{font-weight:850}
@media(max-width:620px){.sma-overlay{place-items:start center}.sma-dialog{width:100%;margin:auto 0}}
.sma-combobox-list{box-sizing:border-box;max-height:none;overflow-y:hidden;scrollbar-gutter:auto}
/* Los controles del diálogo comparten la escala funcional de los formularios administrativos. */
.sma-field label{font-size:13px}.sma-field select,.sma-field textarea,.sma-combobox{font-size:13px;line-height:1.45}.sma-summary dt{font-size:12px}.sma-summary dd{font-size:14px;line-height:1.45}.sma-error{font-size:13px;line-height:1.45}
.sma-dialog button:focus-visible,.sma-dialog textarea:focus-visible{outline:3px solid color-mix(in srgb,var(--primary) 28%,transparent);outline-offset:2px}
</style>
<div class="sma-overlay" data-sma-overlay hidden>
    <section class="sma-dialog" role="dialog" aria-modal="true" aria-labelledby="smaTitle" aria-describedby="smaDescription">
        <header><div><h2 id="smaTitle" data-sma-title>Acción administrativa</h2><p id="smaDescription" data-sma-description></p></div><button type="button" data-sma-close aria-label="Cerrar"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></header>
        <div class="sma-body">
            <div class="sma-step" data-sma-selection>
                <div class="sma-field"><label id="smaReasonLabel">Motivo</label><button class="sma-combobox" id="smaReason" type="button" role="combobox" aria-haspopup="listbox" aria-expanded="false" aria-controls="smaReasonListbox" aria-labelledby="smaReasonLabel smaReasonValue" data-sma-reason><span id="smaReasonValue" data-sma-reason-text>Selecciona un motivo</span><i class="fa-solid fa-chevron-down" aria-hidden="true"></i></button><input type="hidden" data-sma-reason-value></div>
                <div class="sma-field" data-sma-detail-wrap hidden><label for="smaDetail">Otro motivo</label><textarea id="smaDetail" data-sma-detail rows="3" minlength="5" maxlength="300"></textarea><small>Entre 5 y 300 caracteres.</small></div>
            </div>
            <div class="sma-step sma-confirm" data-sma-confirmation hidden><i class="fa-solid fa-triangle-exclamation" aria-hidden="true"></i><p class="sma-warning" data-sma-warning></p><dl class="sma-summary"><div data-sma-material-row hidden><dt>Material</dt><dd data-sma-material></dd></div><div><dt>Motivo</dt><dd data-sma-reason-label></dd></div><div data-sma-detail-row hidden><dt>Detalle</dt><dd data-sma-detail-label></dd></div></dl></div>
            <p class="sma-error" data-sma-error role="alert" hidden></p>
        </div>
        <footer><button type="button" class="sma-button" data-sma-back hidden>Volver</button><button type="button" class="sma-button" data-sma-cancel>Cancelar</button><button type="button" class="sma-button is-danger" data-sma-next disabled>Continuar</button><button type="button" class="sma-button is-danger" data-sma-submit hidden><span data-sma-submit-label>Confirmar</span></button></footer>
    </section>
</div>
