<?php

declare(strict_types=1);

define('ROOT_PATH',dirname(__DIR__));define('APP_PATH',ROOT_PATH.'/app');require APP_PATH.'/helpers.php';require APP_PATH.'/Core/Autoloader.php';Autoloader::register();$db=Database::connection();
if(in_array('--migrate',$argv,true)){foreach(array_filter(array_map('trim',explode(';',(string)file_get_contents(ROOT_PATH.'/database/migrations/20260824_project_document_archives.sql')))) as $sql)$db->exec($sql);}
$assert=static function(bool $ok,string $label):void{if(!$ok)throw new RuntimeException('FALLÓ: '.$label);echo "OK  $label\n";};$tables=(int)$db->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='project_file_version_archive_manifests'")->fetchColumn();if($tables!==1){fwrite(STDERR,"Falta ejecutar la migración FASE 4.\n");exit(2);}
$admin=(int)$db->query("SELECT id FROM users WHERE is_admin=1 AND status='active' AND deleted_at IS NULL AND purged_at IS NULL LIMIT 1")->fetchColumn();$source=null;$storageService=new ProjectDocumentFileService();foreach($db->query("SELECT * FROM project_files WHERE deleted_at IS NULL AND purged_at IS NULL ORDER BY id")->fetchAll() as $candidate){try{$sourcePath=$storageService->resolveStoredFile((int)$candidate['project_id'],(string)$candidate['storage_name']);$source=$candidate;break;}catch(Throwable){}}if($admin<1||!$source){fwrite(STDERR,"No existe administrador o binario fuente verificable.\n");exit(2);}
$tracked=['projects','project_files','project_file_versions','project_file_version_archive_manifests','project_audit_log'];$before=[];foreach($tracked as $table)$before[$table]=(int)$db->query("SELECT COUNT(*) FROM $table")->fetchColumn();$createdPaths=[];$createdDir=null;$db->beginTransaction();
try{
    $projectInsert=$db->prepare("INSERT INTO projects(code,project_type_id,career_id,academic_period_id,title,status,current_stage,published_at,is_available,created_by) SELECT :code,project_type_id,career_id,academic_period_id,'Proyecto temporal de archivo','published','publication',UTC_TIMESTAMP(),1,:actor FROM projects WHERE id=:source");$projectInsert->execute(['code'=>'ARCHIVE-'.strtoupper(bin2hex(random_bytes(5))),'actor'=>$admin,'source'=>(int)$source['project_id']]);$project=(int)$db->lastInsertId();$createdDir=ROOT_PATH.'/storage/private/projects/'.$project;if(!is_dir($createdDir)&&!mkdir($createdDir,0775,true))throw new RuntimeException('No fue posible crear directorio temporal.');
    $extension=(string)$source['extension'];$mime=(string)$source['mime_type'];$makeCopy=static function(string $label)use(&$createdPaths,$createdDir,$sourcePath,$extension):array{$name=bin2hex(random_bytes(32)).'.'.$extension;$path=$createdDir.DIRECTORY_SEPARATOR.$name;if(!copy($sourcePath,$path))throw new RuntimeException('No fue posible copiar fixture física.');$createdPaths[]=$path;return ['name'=>$name,'path'=>$path,'checksum'=>(string)hash_file('sha256',$path),'size'=>(int)filesize($path)];};
    $current=$makeCopy('current');$fileInsert=$db->prepare("INSERT INTO project_files(project_id,category,original_name,storage_name,storage_path,mime_type,extension,size_bytes,checksum_sha256,sort_order,uploaded_by) VALUES(:project,'repository','documento.{$extension}',:storage,:path,:mime,:extension,:size,:checksum,1,:actor)");$fileInsert->execute(['project'=>$project,'storage'=>$current['name'],'path'=>'logical/current/'.$current['name'],'mime'=>$mime,'extension'=>$extension,'size'=>$current['size'],'checksum'=>$current['checksum'],'actor'=>$admin]);$file=(int)$db->lastInsertId();
    $archive=new ProjectDocumentArchiveService();$empty=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert($empty['archived_count']===0,'proyecto con una sola versión no archiva');
    $versionInsert=$db->prepare("INSERT INTO project_file_versions(file_id,project_id,version_number,original_name,storage_name,storage_path,extension,mime_type,size_bytes,checksum_sha256,replaced_by,replacement_reason,physical_status) VALUES(:file,:project,:number,'documento.{$extension}',:storage,:path,:extension,:mime,:size,:checksum,:actor,'Sustitución','active')");
    $v1=$makeCopy('v1');$versionInsert->execute(['file'=>$file,'project'=>$project,'number'=>1,'storage'=>$v1['name'],'path'=>'logical/active/'.$v1['name'],'extension'=>$extension,'mime'=>$mime,'size'=>$v1['size'],'checksum'=>$v1['checksum'],'actor'=>$admin]);$v1id=(int)$db->lastInsertId();$v2=$makeCopy('v2');$versionInsert->execute(['file'=>$file,'project'=>$project,'number'=>2,'storage'=>$v2['name'],'path'=>'logical/active/'.$v2['name'],'extension'=>$extension,'mime'=>$mime,'size'=>$v2['size'],'checksum'=>$v2['checksum'],'actor'=>$admin]);$v2id=(int)$db->lastInsertId();
    $result=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin,'Publicación institucional de prueba.');$assert($result['archived_count']===2&&$result['physical_files_moved']===false,'solo versiones históricas pasan a archived');$assert(is_file($v1['path'])&&is_file($v2['path'])&&is_file($current['path']),'cero pérdida de archivos');
    $status=$archive->statusForVersion($v1id);$assert($status['physical_status']==='archived'&&$status['checksum_verified']&&$status['is_download_available']===false,'checksum correcto y descarga deshabilitada');$assert($result['current_versions_status']==='active','versión vigente permanece active');
    $verified=$archive->verifyArchivedVersion($v1id);$assert($verified['verified']&&$verified['physical_status']==='archived','verificación posterior confirma SHA-256, tamaño y MIME');$history=(new ProjectFileVersionHistoryService($db))->forFile($project,$file,$admin,'academic_management');$assert(end($history['versions'])['physical_status']==='active'&&count(array_filter($history['versions'],static fn(array $version):bool=>$version['physical_status']==='archived'))===2,'lector distingue vigente y archivadas');
    $manifests=(int)$db->query("SELECT COUNT(*) FROM project_file_version_archive_manifests WHERE project_id=$project")->fetchColumn();$assert($manifests===2,'manifiesto por versión archivada');
    $again=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert($again['archived_count']===0&&(int)$db->query("SELECT COUNT(*) FROM project_file_version_archive_manifests WHERE project_id=$project")->fetchColumn()===$manifests,'ejecución repetida idempotente');
    $missingName=bin2hex(random_bytes(32)).'.'.$extension;$versionInsert->execute(['file'=>$file,'project'=>$project,'number'=>3,'storage'=>$missingName,'path'=>'logical/active/'.$missingName,'extension'=>$extension,'mime'=>$mime,'size'=>12,'checksum'=>hash('sha256','missing'),'actor'=>$admin]);$missingId=(int)$db->lastInsertId();$missing=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert($missing['unavailable_count']===1&&$archive->statusForVersion($missingId)['physical_status']==='unavailable','binario inexistente queda unavailable');
    $bad=$makeCopy('bad');$versionInsert->execute(['file'=>$file,'project'=>$project,'number'=>4,'storage'=>$bad['name'],'path'=>'logical/active/'.$bad['name'],'extension'=>$extension,'mime'=>$mime,'size'=>$bad['size'],'checksum'=>str_repeat('0',64),'actor'=>$admin]);$badId=(int)$db->lastInsertId();$db->exec('SAVEPOINT checksum_failure');try{$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert(false,'checksum incorrecto');}catch(ProjectDocumentArchiveException){$db->exec('ROLLBACK TO SAVEPOINT checksum_failure');$assert($archive->statusForVersion($badId)['physical_status']==='active','checksum incorrecto rechazado sin cambio');}$db->prepare('DELETE FROM project_file_versions WHERE id=:id')->execute(['id'=>$badId]);
    $held=$makeCopy('held');$versionInsert->execute(['file'=>$file,'project'=>$project,'number'=>4,'storage'=>$held['name'],'path'=>'logical/active/'.$held['name'],'extension'=>$extension,'mime'=>$mime,'size'=>$held['size'],'checksum'=>$held['checksum'],'actor'=>$admin]);$heldId=(int)$db->lastInsertId();$db->prepare('UPDATE project_file_versions SET legal_hold=1 WHERE id=:id')->execute(['id'=>$heldId]);$holdResult=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert($holdResult['held_count']===1&&$archive->statusForVersion($heldId)['physical_status']==='active','legal hold bloquea archivado');
    $db->prepare('UPDATE project_file_versions SET legal_hold=0 WHERE id=:id')->execute(['id'=>$heldId]);$pending=$makeCopy('pending');$versionInsert->execute(['file'=>$file,'project'=>$project,'number'=>5,'storage'=>$pending['name'],'path'=>'logical/active/'.$pending['name'],'extension'=>$extension,'mime'=>$mime,'size'=>$pending['size'],'checksum'=>$pending['checksum'],'actor'=>$admin]);$pendingId=(int)$db->lastInsertId();$observation=$db->prepare("INSERT INTO project_observations(project_id,file_id,author_id,category,body,status) VALUES(:project,:file,:actor,'content','Pendiente de prueba','pending')");$observation->execute(['project'=>$project,'file'=>$file,'actor'=>$admin]);$observationId=(int)$db->lastInsertId();$pendingResult=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert($pendingResult['held_count']>=2&&$archive->statusForVersion($pendingId)['physical_status']==='active','observación pendiente evaluada como hold');$db->prepare("UPDATE project_observations SET status='addressed' WHERE id=:id")->execute(['id'=>$observationId]);$released=$archive->archiveHistoricalVersionsForProjectInTransaction($db,$project,$admin);$assert($released['archived_count']===2,'archivado continúa al liberar hold');
    $audit=$db->prepare("SELECT COUNT(*) FROM project_audit_log WHERE project_id=:project AND action='project_document_versions_archived'");$audit->execute(['project'=>$project]);$auditCount=(int)$audit->fetchColumn();$assert($auditCount===3,'una auditoría consolidada por operación efectiva');$timeline=(new ProjectAcademicTimelineService($db))->page($project,0,50);$archiveEvents=array_values(array_filter($timeline['events'],static fn(array $event):bool=>$event['event_type']==='document_version_archived'));$assert(count($archiveEvents)===$auditCount,'historial expone eventos consolidados');
    $manifestBefore=(int)$db->query("SELECT COUNT(*) FROM project_file_version_archive_manifests WHERE project_id=$project")->fetchColumn();$publishedAt=(string)$db->query("SELECT published_at FROM projects WHERE id=$project")->fetchColumn();(new ProjectPublicationReversionService())->revertInTransaction($db,$project,'published',$publishedAt,'Reversión institucional de prueba.',$admin);$manifestAfter=(int)$db->query("SELECT COUNT(*) FROM project_file_version_archive_manifests WHERE project_id=$project")->fetchColumn();$archivedAfter=(int)$db->query("SELECT COUNT(*) FROM project_file_versions WHERE project_id=$project AND physical_status='archived'")->fetchColumn();$assert($manifestBefore===$manifestAfter&&$archivedAfter===4,'reversión no duplica ni reactiva versiones');
    $manifestColumns=$db->query("SELECT GROUP_CONCAT(column_name) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='project_file_version_archive_manifests'")->fetchColumn();$assert(!str_contains((string)$manifestColumns,'storage_path'),'manifiesto no expone rutas físicas');
}finally{if($db->inTransaction())$db->rollBack();foreach($createdPaths as $path)if(is_file($path))unlink($path);if($createdDir&&is_dir($createdDir))@rmdir($createdDir);}
$after=[];foreach($tracked as $table)$after[$table]=(int)$db->query("SELECT COUNT(*) FROM $table")->fetchColumn();$assert($before===$after,'datos finales sin residuos');$assert(count(array_filter($createdPaths,'is_file'))===0,'fixtures físicas retiradas sin tocar archivos reales');echo "Pruebas de conservación documental finalizadas.\n";
