<?php

declare(strict_types=1);

define('ROOT_PATH',dirname(__DIR__));define('APP_PATH',ROOT_PATH.'/app');require APP_PATH.'/helpers.php';require APP_PATH.'/Core/Autoloader.php';Autoloader::register();$db=Database::connection();
if(in_array('--migrate',$argv,true)){foreach(array_filter(array_map('trim',explode(';',(string)file_get_contents(ROOT_PATH.'/database/migrations/20260822_project_file_version_changes.sql')))) as $sql)$db->exec($sql);}
$assert=static function(bool $ok,string $label):void{if(!$ok)throw new RuntimeException('FALLÓ: '.$label);echo "OK  $label\n";};
$tables=(int)$db->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('project_file_version_changes','project_file_version_addressed_observations')")->fetchColumn();if($tables!==2){fwrite(STDERR,"Falta ejecutar la migración de FASE 3.\n");exit(2);}
$fixture=$db->query("SELECT p.id project_id,p.status,p.tutor_id,pp.user_id student_id,f.id file_id,f.checksum_sha256 FROM projects p JOIN project_participants pp ON pp.project_id=p.id AND pp.role_code='student' AND pp.status='active' AND pp.removed_at IS NULL JOIN user_roles ur ON ur.user_id=pp.user_id JOIN roles r ON r.id=ur.role_id AND r.code='student' JOIN project_files f ON f.project_id=p.id AND f.deleted_at IS NULL AND f.purged_at IS NULL WHERE p.status='development' AND p.deleted_at IS NULL LIMIT 1")->fetch();if(!$fixture){fwrite(STDERR,"No existe proyecto en desarrollo con estudiante y archivo.\n");exit(2);}
$project=(int)$fixture['project_id'];$student=(int)$fixture['student_id'];$file=(int)$fixture['file_id'];$checksum=(string)$fixture['checksum_sha256'];$service=new ProjectFileVersionChangeService();
$tracked=['project_files','project_file_versions','project_file_version_changes','project_file_version_addressed_observations','project_file_review_states','project_observations','project_audit_log','notifications'];$before=[];foreach($tracked as $table)$before[$table]=(int)$db->query("SELECT COUNT(*) FROM $table")->fetchColumn();
$db->beginTransaction();
try{
    $copy=$db->prepare("INSERT INTO project_files(project_id,category,original_name,storage_name,storage_path,mime_type,extension,size_bytes,checksum_sha256,sort_order,uploaded_by) SELECT project_id,category,'otro.pdf',:storage,'tests/otro.pdf','application/pdf','pdf',1,:checksum,sort_order+100,:actor FROM project_files WHERE id=:file");$copy->execute(['storage'=>'phase3-other-'.bin2hex(random_bytes(8)).'.pdf','checksum'=>hash('sha256','other-'.$project),'actor'=>$student,'file'=>$file]);$otherFile=(int)$db->lastInsertId();
    $otherProject=(int)$db->query("SELECT id FROM projects WHERE id<>$project AND deleted_at IS NULL LIMIT 1")->fetchColumn();if($otherProject<1)$otherProject=$project;
    $obs=$db->prepare("INSERT INTO project_observations(project_id,file_id,author_id,category,body,status) VALUES(:project,:file,:actor,'content',:body,:status)");
    $obs->execute(['project'=>$project,'file'=>$file,'actor'=>$student,'body'=>'Observación pendiente propia','status'=>'pending']);$ownObservation=(int)$db->lastInsertId();
    $obs->execute(['project'=>$project,'file'=>$otherFile,'actor'=>$student,'body'=>'Observación de otro archivo','status'=>'pending']);$otherFileObservation=(int)$db->lastInsertId();
    $obs->execute(['project'=>$project,'file'=>$file,'actor'=>$student,'body'=>'Observación resuelta','status'=>'resolved']);$resolvedObservation=(int)$db->lastInsertId();
    if($otherProject!==$project){$obs->execute(['project'=>$otherProject,'file'=>null,'actor'=>$student,'body'=>'Observación de otro proyecto','status'=>'pending']);$otherProjectObservation=(int)$db->lastInsertId();}else{$otherProjectObservation=PHP_INT_MAX;}
    $state=$db->prepare("INSERT INTO project_file_review_states(project_id,file_id,checksum_sha256,status,reviewed_by) VALUES(:project,:file,:checksum,'approved',:actor) ON DUPLICATE KEY UPDATE status='approved',reviewed_by=VALUES(reviewed_by)");$state->execute(['project'=>$project,'file'=>$file,'checksum'=>$checksum,'actor'=>$student]);
    $legacyNumber=(int)$db->query("SELECT COALESCE(MAX(version_number),0)+1 FROM project_file_versions WHERE file_id=$file")->fetchColumn();$legacy=$db->prepare("INSERT INTO project_file_versions(file_id,project_id,version_number,original_name,storage_name,storage_path,extension,mime_type,size_bytes,checksum_sha256,replaced_by,replacement_reason) SELECT id,project_id,:number,original_name,storage_name,storage_path,extension,mime_type,size_bytes,checksum_sha256,:actor,'Legado' FROM project_files WHERE id=:file");$legacy->execute(['number'=>$legacyNumber,'actor'=>$student,'file'=>$file]);
    $stored=['original_name'=>'documento-nuevo.pdf','storage_name'=>'phase3-new-'.bin2hex(random_bytes(8)).'.pdf','storage_path'=>'tests/documento-nuevo.pdf','extension'=>'pdf','mime_type'=>'application/pdf','size_bytes'=>123,'checksum_sha256'=>hash('sha256','new-'.$project)];
    $base=['reason'=>'Corrección solicitada por revisión','declared_summary'=>'Se corrigieron resultados, conclusiones y referencias del documento.','sections'=>['Resultados','Conclusiones'],'addressed_observation_ids'=>[$ownObservation]];
    $expect=static function(callable $call,string $contains,int $status=422)use($assert):void{try{$call();$assert(false,$contains);}catch(ProjectDocumentVersionException $e){$assert($e->httpStatus()===$status&&str_contains($e->getMessage(),$contains),$contains);}};
    $expect(fn()=>$service->replaceInTransaction($db,$project,$file,$checksum,$stored,$student,'academic',array_replace($base,['declared_summary'=>'   '])),'resumen de cambios');
    $expect(fn()=>$service->replaceInTransaction($db,$project,$file,$checksum,$stored,$student,'academic',array_replace($base,['sections'=>['Resultados','resultados']])),'No repitas secciones');
    $expect(fn()=>$service->replaceInTransaction($db,$project,$file,str_repeat('0',64),$stored,$student,'academic',$base),'documento fue actualizado',409);
    $identical=$stored;$identical['checksum_sha256']=$checksum;$expect(fn()=>$service->replaceInTransaction($db,$project,$file,$checksum,$identical,$student,'academic',$base),'mismo contenido');
    $expect(fn()=>$service->replaceInTransaction($db,$project,$file,$checksum,$stored,$student,'academic',array_replace($base,['addressed_observation_ids'=>[$otherFileObservation]])),'otro archivo');
    $expect(fn()=>$service->replaceInTransaction($db,$project,$file,$checksum,$stored,$student,'academic',array_replace($base,['addressed_observation_ids'=>[$resolvedObservation]])),'ya fue resuelta');
    if($otherProject!==$project)$expect(fn()=>$service->replaceInTransaction($db,$project,$file,$checksum,$stored,$student,'academic',array_replace($base,['addressed_observation_ids'=>[$otherProjectObservation]])),'otro proyecto');
    $result=$service->replaceInTransaction($db,$project,$file,$checksum,$stored,$student,'academic',$base);$change=(int)$result['change_id'];
    $assert($result['previous_document_status']==='approved'&&$result['new_document_status']==='development','nueva versión pierde aprobación');
    $assert($result['sections']===['Resultados','Conclusiones'],'secciones normalizadas');
    $q=$db->prepare('SELECT status FROM project_observations WHERE id=:id');$q->execute(['id'=>$ownObservation]);$assert($q->fetchColumn()==='addressed','observación marcada atendida, no resuelta');
    $q=$db->prepare('SELECT status FROM project_file_review_states WHERE file_id=:file AND checksum_sha256=:checksum');$q->execute(['file'=>$file,'checksum'=>$checksum]);$assert($q->fetchColumn()==='approved','estado histórico anterior conservado');$q->execute(['file'=>$file,'checksum'=>$stored['checksum_sha256']]);$assert($q->fetchColumn()==='development','estado del checksum nuevo reiniciado');
    $q=$db->prepare("SELECT COUNT(*) FROM project_audit_log WHERE action='project_document_version_created' AND entity_id=:id");$q->execute(['id'=>$change]);$assert((int)$q->fetchColumn()===1,'auditoría técnica única');
    $q=$db->prepare("SELECT COUNT(*) FROM notifications WHERE deduplication_key=:dedup");$q->execute(['dedup'=>'document-version:'.$change.':'.(int)$fixture['tutor_id']]);$assert((int)$q->fetchColumn()===((int)$fixture['tutor_id']>0?1:0),'notificación consolidada al Tutor');
    $timeline=(new ProjectAcademicTimelineService($db))->page($project,0,50);$events=array_values(array_filter($timeline['events'],static fn(array $event):bool=>$event['event_type']==='document_version_uploaded'&&(int)$event['source_id']===$change));$assert(count($events)===1&&$events[0]['description']===$base['declared_summary'],'evento académico document_version_uploaded');
    $history=(new ProjectFileVersionHistoryService($db))->forFile($project,$file,$student,'academic');$current=end($history['versions']);$assert($current['summary']===$base['declared_summary']&&$current['is_download_available']===false,'lector histórico seguro');$assert(count(array_filter($history['versions'],static fn(array $version):bool=>$version['summary']==='Resumen de cambios no disponible para esta versión histórica.'))>=1,'compatibilidad con versión histórica sin resumen');
    $outsider=$db->prepare("INSERT INTO users(email,password_hash,full_name,status) VALUES(:email,'test-only','Persona ajena','active')");$outsider->execute(['email'=>'phase3-'.bin2hex(random_bytes(5)).'@example.invalid']);$outsiderId=(int)$db->lastInsertId();$role=$db->prepare("INSERT INTO user_roles(user_id,role_id) SELECT :user,id FROM roles WHERE code='student'");$role->execute(['user'=>$outsiderId]);try{(new ProjectFileVersionHistoryService($db))->forFile($project,$file,$outsiderId,'academic');$assert(false,'lector rechaza usuario ajeno');}catch(InvalidArgumentException){$assert(true,'lector rechaza usuario ajeno');}
    $savepoint='phase3_intermediate';$db->exec("SAVEPOINT $savepoint");$countsBefore=[(int)$db->query('SELECT COUNT(*) FROM project_file_version_changes')->fetchColumn(),(int)$db->query('SELECT COUNT(*) FROM project_audit_log')->fetchColumn()];$second=$stored;$second['checksum_sha256']=hash('sha256','second-'.$project);$second['storage_name']='phase3-second-'.bin2hex(random_bytes(8)).'.pdf';try{$service->replaceInTransaction($db,$project,$file,$stored['checksum_sha256'],$second,$student,'academic',array_replace($base,['addressed_observation_ids'=>[]]));throw new RuntimeException('fallo intermedio');}catch(RuntimeException $e){$db->exec("ROLLBACK TO SAVEPOINT $savepoint");$assert($e->getMessage()==='fallo intermedio','error intermedio revertido');}$countsAfter=[(int)$db->query('SELECT COUNT(*) FROM project_file_version_changes')->fetchColumn(),(int)$db->query('SELECT COUNT(*) FROM project_audit_log')->fetchColumn()];$assert($countsBefore===$countsAfter,'rollback intermedio sin residuos');
}finally{if($db->inTransaction())$db->rollBack();}
$after=[];foreach($tracked as $table)$after[$table]=(int)$db->query("SELECT COUNT(*) FROM $table")->fetchColumn();$assert($before===$after,'cero residuos finales');
$foreignKeys=(int)$db->query("SELECT COUNT(*) FROM information_schema.referential_constraints WHERE constraint_schema=DATABASE() AND table_name IN ('project_file_version_changes','project_file_version_addressed_observations')")->fetchColumn();$assert($foreignKeys>=6,'claves foráneas instaladas');echo "Pruebas de cambios documentales finalizadas.\n";
