<?php

declare(strict_types=1);

define('ROOT_PATH', dirname(__DIR__)); define('APP_PATH', ROOT_PATH.'/app');
require APP_PATH.'/helpers.php'; require APP_PATH.'/Core/Autoloader.php'; Autoloader::register();

$db=Database::connection(); $ok=0; $fail=0; $directories=[];
function checkSubmission(bool $value,string $message):void{if(!$value)throw new RuntimeException($message);}
function rejected(callable $call,int $status=422):void{try{$call();}catch(StudentProjectSubmissionException $e){checkSubmission($e->httpStatus()===$status,'HTTP inesperado: '.$e->httpStatus());return;}throw new RuntimeException('La operación debía rechazarse.');}
function testCase(PDO $db,string $name,callable $call):void{global $ok,$fail;static $n=0;$sp='submission_'.++$n;$db->exec("SAVEPOINT $sp");try{$call();echo "OK   $name\n";$ok++;}catch(Throwable $e){echo "FAIL $name: {$e->getMessage()}\n";$fail++;}finally{$db->exec("ROLLBACK TO SAVEPOINT $sp");$db->exec("RELEASE SAVEPOINT $sp");}}
function identities(PDO $db):array{$teacher=(int)$db->query("SELECT u.id FROM users u JOIN teacher_profiles tp ON tp.user_id=u.id JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.code='teacher' WHERE u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL AND tp.can_tutor=1 LIMIT 1")->fetchColumn();$students=$db->query("SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id AND r.code='student' WHERE u.status='active' AND u.deleted_at IS NULL AND u.purged_at IS NULL ORDER BY u.id LIMIT 2")->fetchAll(PDO::FETCH_COLUMN);checkSubmission($teacher>0&&count($students)>1,'Faltan identidades de prueba.');return ['teacher'=>$teacher,'student'=>(int)$students[0],'other'=>(int)$students[1]];}
function fixture(PDO $db,array $ids,int $n):array{$type=(int)$db->query('SELECT id FROM project_types WHERE is_active=1 ORDER BY id LIMIT 1')->fetchColumn();$career=(int)$db->query('SELECT id FROM careers ORDER BY id LIMIT 1')->fetchColumn();$period=(int)$db->query('SELECT id FROM academic_periods ORDER BY id LIMIT 1')->fetchColumn();$code='TST-SUBMIT-'.getmypid().'-'.$n.'-'.bin2hex(random_bytes(3));$q=$db->prepare("INSERT INTO projects(code,project_type_id,career_id,academic_period_id,title,summary,tutor_id,status,current_stage,created_by) VALUES(:code,:type,:career,:period,'Proyecto de envío de prueba','Resumen de prueba válido para el envío académico a revisión.',:tutor,'development','registration',:student)");$q->execute(['code'=>$code,'type'=>$type,'career'=>$career,'period'=>$period,'tutor'=>$ids['teacher'],'student'=>$ids['student']]);$project=(int)$db->lastInsertId();$participant=$db->prepare("INSERT INTO project_participants(project_id,user_id,role_code,permission_level,is_leader,status) VALUES(:project,:user,:role,:permission,:leader,'active')");$participant->execute(['project'=>$project,'user'=>$ids['teacher'],'role'=>'tutor','permission'=>'review','leader'=>0]);$participant->execute(['project'=>$project,'user'=>$ids['student'],'role'=>'student','permission'=>'manage','leader'=>1]);return ['project'=>$project,'code'=>$code]+$ids;}
function addPdf(PDO $db,array $f,int $sort=1,bool $physical=true):array{global $directories;$dir=ROOT_PATH.'/storage/private/projects/'.$f['project'];if(!is_dir($dir)){mkdir($dir,0775,true);$directories[]=$dir;}$name=bin2hex(random_bytes(32)).'.pdf';$path=$dir.DIRECTORY_SEPARATOR.$name;$content="%PDF-1.4\n1 0 obj\n<<>>\nendobj\ntrailer\n<<>>\n%%EOF\n";if($physical)file_put_contents($path,$content);$checksum=$physical?hash_file('sha256',$path):hash('sha256','missing-'.$name);$size=$physical?(int)filesize($path):10;$q=$db->prepare("INSERT INTO project_files(project_id,category,original_name,storage_name,storage_path,mime_type,extension,size_bytes,checksum_sha256,sort_order,uploaded_by) VALUES(:project,'delivery','documento.pdf',:storage,:path,'application/pdf','pdf',:size,:checksum,:sort,:actor)");$q->execute(['project'=>$f['project'],'storage'=>$name,'path'=>'storage/private/projects/'.$f['project'].'/'.$name,'size'=>$size,'checksum'=>$checksum,'sort'=>$sort,'actor'=>$f['student']]);return ['id'=>(int)$db->lastInsertId(),'checksum'=>$checksum,'path'=>$path];}
function state(PDO $db,array $f,array $file,string $status):void{(new ProjectDocumentReviewService($db))->recordCurrentStatus($f['project'],$file['id'],$file['checksum'],$status,$f['teacher']);}

$db->beginTransaction();
try{
    $ids=identities($db);$service=new StudentProjectSubmissionService();$case=0;
    testCase($db,'1 proyecto sin archivos es rechazado',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']));});
    testCase($db,'2 proyecto ajeno es rechazado con 403',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['other']),403);});
    testCase($db,'3 participante inactivo es rechazado',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f);$db->prepare("UPDATE project_participants SET status='inactive',removed_at=UTC_TIMESTAMP() WHERE project_id=:p AND user_id=:u AND role_code='student'")->execute(['p'=>$f['project'],'u'=>$f['student']]);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),403);});
    foreach(['under_review','approved'] as $status)testCase($db,"proyecto $status es rechazado",function()use($db,$ids,$service,&$case,$status){$f=fixture($db,$ids,++$case);addPdf($db,$f);$db->prepare('UPDATE projects SET status=:status WHERE id=:id')->execute(['status'=>$status,'id'=>$f['project']]);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),409);});
    testCase($db,'6 información académica incompleta es rechazada',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f);$db->prepare("UPDATE projects SET summary='' WHERE id=:id")->execute(['id'=>$f['project']]);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']));});
    testCase($db,'7 archivo sin representación válida es rechazado',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f,1,false);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']));});
    testCase($db,'9 un documento listo genera entrega y transición',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r['delivery_number']===1&&$r['submitted_file_count']===1,'Entrega inicial inválida.');checkSubmission($db->query("SELECT status FROM projects WHERE id={$f['project']}")->fetchColumn()==='under_review','Proyecto no pasó a revisión.');$q=$db->prepare('SELECT status,reviewed_by FROM project_file_review_states WHERE file_id=:file AND checksum_sha256=:checksum');$q->execute(['file'=>$file['id'],'checksum'=>$file['checksum']]);$row=$q->fetch();checkSubmission($row['status']==='under_review'&&(int)$row['reviewed_by']===$f['student'],'Estado documental incorrecto.');checkSubmission((int)$db->query("SELECT submitted_by FROM project_deliveries WHERE id={$r['delivery_id']}")->fetchColumn()===$f['student'],'Actor de entrega incorrecto.');});
    testCase($db,'10 varios development se envían juntos',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f);addPdf($db,$f,2);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r['submitted_file_count']===2,'No incluyó todos los pendientes.');});
    testCase($db,'11 approved y development solo envía development',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$approved=addPdf($db,$f);$pending=addPdf($db,$f,2);state($db,$f,$approved,'approved');$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r['submitted_file_count']===1&&(int)$r['submitted_files'][0]['id']===$pending['id'],'Incluyó archivo aprobado.');$q=$db->prepare('SELECT status FROM project_file_review_states WHERE file_id=:file AND checksum_sha256=:checksum');$q->execute(['file'=>$approved['id'],'checksum'=>$approved['checksum']]);checkSubmission($q->fetchColumn()==='approved','Alteró aprobación vigente.');});
    testCase($db,'12 corrections_requested entra sin alterar approved',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$approved=addPdf($db,$f);$corrected=addPdf($db,$f,2);state($db,$f,$approved,'approved');state($db,$f,$corrected,'corrections_requested');file_put_contents($corrected['path'],"%PDF-1.4\ncorreccion_reemplazada\n%%EOF\n");$new=hash_file('sha256',$corrected['path']);$db->prepare('UPDATE project_files SET checksum_sha256=:checksum WHERE id=:id')->execute(['checksum'=>$new,'id'=>$corrected['id']]);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r['submitted_file_count']===1&&(int)$r['submitted_files'][0]['id']===$corrected['id'],'No seleccionó la corrección pendiente.');});
    testCase($db,'12b reenvio sin modificaciones en observados es rechazado',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$approved=addPdf($db,$f);$corrected=addPdf($db,$f,2);state($db,$f,$approved,'approved');state($db,$f,$corrected,'corrections_requested');$db->prepare("INSERT INTO project_deliveries(project_id,version_number,title,comment,status,submitted_by) VALUES({$f['project']},1,'Entrega v1','v1','under_review',{$f['student']})")->execute();rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),422);});
    testCase($db,'12c reenvio parcial K de N observados es rechazado',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$c1=addPdf($db,$f);$c2=addPdf($db,$f,2);state($db,$f,$c1,'corrections_requested');state($db,$f,$c2,'corrections_requested');$db->prepare("INSERT INTO project_deliveries(project_id,version_number,title,comment,status,submitted_by) VALUES({$f['project']},1,'Entrega v1','v1','under_review',{$f['student']})")->execute();file_put_contents($c1['path'],"%PDF-1.4\ncorreccion_1\n%%EOF\n");$new1=hash_file('sha256',$c1['path']);$db->prepare('UPDATE project_files SET checksum_sha256=:checksum WHERE id=:id')->execute(['checksum'=>$new1,'id'=>$c1['id']]);rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),422);});
    testCase($db,'14 checksum reemplazado entra como pendiente',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);state($db,$f,$file,'approved');file_put_contents($file['path'],"%PDF-1.4\nreemplazo\n%%EOF\n");$new=hash_file('sha256',$file['path']);$db->prepare('UPDATE project_files SET checksum_sha256=:checksum WHERE id=:id')->execute(['checksum'=>$new,'id'=>$file['id']]);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r['submitted_file_count']===1,'El checksum nuevo no se trató como pendiente.');});
    testCase($db,'15 sin pendientes no crea entrega vacía',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);state($db,$f,$file,'approved');rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']));checkSubmission((int)$db->query("SELECT COUNT(*) FROM project_deliveries WHERE project_id={$f['project']}")->fetchColumn()===0,'Creó entrega vacía.');});
    testCase($db,'20 capacidades quedan bloqueadas y 22 historial registra entrega',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);$project=['id'=>$f['project'],'created_by'=>$f['student'],'tutor_id'=>$f['teacher'],'status'=>'under_review','deleted_at'=>null,'type_code'=>'pis','participants'=>[['user_id'=>$f['student'],'role_code'=>'student','status'=>'active','removed_at'=>null]]];$caps=(new ProjectCapabilityService())->resolve($project,'academic',$f['student'],['student'],false);checkSubmission(empty($caps['edit_information'])&&empty($caps['manage_workspace_files'])&&empty($caps['send_for_review'])&&empty($caps['register_delivery']),'Capacidades no bloqueadas.');$events=(new ProjectAcademicTimelineService($db))->page($f['project'],0,30)['events'];checkSubmission((bool)array_filter($events,fn(array $e)=>(string)$e['event_type']==='delivery_registered'&&(int)$e['source_id']===$r['delivery_id']),'El historial no muestra la entrega.');$audit=$db->prepare("SELECT COUNT(*) FROM project_audit_log WHERE project_id=:project AND action='project_submitted_for_review'");$audit->execute(['project'=>$f['project']]);checkSubmission((int)$audit->fetchColumn()===1,'Falta auditoría formal.');});
    testCase($db,'23 notifica a tutor y 24 doble envío crea una entrega',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);addPdf($db,$f);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);$q=$db->prepare("SELECT COUNT(*) FROM notifications WHERE deduplication_key=:key");$q->execute(['key'=>'project-submitted-for-review:'.$f['project'].':1:'.$f['teacher']]);checkSubmission((int)$q->fetchColumn()===1,'No notificó al tutor.');rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),409);checkSubmission((int)$db->query("SELECT COUNT(*) FROM project_deliveries WHERE project_id={$f['project']}")->fetchColumn()===1,'El doble envío duplicó la entrega.');});
    testCase($db,'25 rollback posterior no deja entrega ni estados',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);$db->exec('SAVEPOINT forced_submission_failure');try{$service->submitForReviewInTransaction($db,$f['project'],$f['student'],true);}catch(RuntimeException){}$db->exec('ROLLBACK TO SAVEPOINT forced_submission_failure');$db->exec('RELEASE SAVEPOINT forced_submission_failure');checkSubmission((int)$db->query("SELECT COUNT(*) FROM project_deliveries WHERE project_id={$f['project']}")->fetchColumn()===0,'Quedó una entrega huérfana.');$q=$db->prepare('SELECT COUNT(*) FROM project_file_review_states WHERE file_id=:file AND checksum_sha256=:checksum');$q->execute(['file'=>$file['id'],'checksum'=>$file['checksum']]);checkSubmission((int)$q->fetchColumn()===0,'Quedó estado documental parcial.');});
    testCase($db,'30 eliminar archivo antes de primera entrega es permitido',function()use($db,$ids,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);$docModel=new ProjectDocumentModel($db);$active=$docModel->findActiveFile($f['project'],$file['id'],true);checkSubmission(!empty($active),'Archivo no fue creado.');$removed=$docModel->retire($f['project'],[$file['id']],$f['student']);checkSubmission(count($removed)===1,'No eliminó archivo antes de primera entrega.');});
    testCase($db,'31 eliminar archivo despues de primera entrega es rechazado',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);$db->prepare("UPDATE projects SET status='development' WHERE id={$f['project']}")->execute();state($db,$f,$file,'corrections_requested');$reflection=new ReflectionClass('ProjectStudentDocumentController');$method=$reflection->getMethod('assertFileCanBeRemoved');$method->setAccessible(true);$docController=new ProjectStudentDocumentController();try{$method->invoke($docController,$db,$f['project'],['id'=>$file['id'],'delivery_id'=>$r['delivery_id']]);throw new RuntimeException('Debía rechazar eliminación de archivo entregado.');}catch(ProjectDocumentVersionException $e){checkSubmission($e->httpStatus()===422,'HTTP status inesperado en eliminación rechazada.');}});
    testCase($db,'32 reenvio con archivo requerido faltante es rechazado con 422',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file1=addPdf($db,$f,1);$file2=addPdf($db,$f,2);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);$db->prepare("UPDATE projects SET status='development' WHERE id={$f['project']}")->execute();state($db,$f,$file1,'corrections_requested');state($db,$f,$file2,'approved');$db->prepare("UPDATE project_files SET deleted_at=UTC_TIMESTAMP() WHERE id={$file1['id']}")->execute();rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),422);});
    testCase($db,'33 reemplazar archivo despues de primera entrega es permitido',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);$db->prepare("UPDATE projects SET status='development' WHERE id={$f['project']}")->execute();state($db,$f,$file,'corrections_requested');file_put_contents($file['path'],"%PDF-1.4\nreemplazo_valido\n%%EOF\n");$newChecksum=hash_file('sha256',$file['path']);$stored=['original_name'=>'documento.pdf','storage_name'=>basename($file['path']),'storage_path'=>'storage/private/projects/'.$f['project'].'/'.basename($file['path']),'mime_type'=>'application/pdf','extension'=>'pdf','size_bytes'=>filesize($file['path']),'checksum_sha256'=>$newChecksum];$res=(new ProjectFileVersionChangeService())->replaceWorkspaceInTransaction($db,$f['project'],$file['id'],$file['checksum'],$stored,$f['student'],'Corrección aplicada');checkSubmission(!empty($res['change_id']),'Falló reemplazo legítimo.');$r2=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r2['delivery_number']===2,'Reenvío post-reemplazo falló.');});
    testCase($db,'34 approved sin representación lista no bloquea reenvío si no forma parte del lote',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$approvedNoRep=addPdf($db,$f,1,false);$pendingDoc=addPdf($db,$f,2,true);state($db,$f,$approvedNoRep,'approved');$r=$service->submitForReviewInTransaction($db,$f['project'],$f['student']);checkSubmission($r['submitted_file_count']===1&&(int)$r['submitted_files'][0]['id']===$pendingDoc['id'],'Approved sin representación bloqueó el reenvío.');});
    testCase($db,'35 archivo aprobado reemplazado con checksum nuevo sí exige representación',function()use($db,$ids,$service,&$case){$f=fixture($db,$ids,++$case);$file=addPdf($db,$f);state($db,$f,$file,'approved');$db->prepare("UPDATE project_files SET checksum_sha256='checksum_nuevo_sin_rep',size_bytes=10 WHERE id={$file['id']}")->execute();rejected(fn()=>$service->submitForReviewInTransaction($db,$f['project'],$f['student']),422);});
}finally{$db->rollBack();foreach(array_unique($directories) as $dir){if(is_dir($dir)){foreach(glob($dir.DIRECTORY_SEPARATOR.'*')?:[] as $file)if(is_file($file))unlink($file);@rmdir($dir);}}}
echo "Resultado: $ok OK, $fail FAIL\n";exit($fail?1:0);
