<?php

declare(strict_types=1);

define('ROOT_PATH',dirname(__DIR__));define('APP_PATH',ROOT_PATH.'/app');require APP_PATH.'/helpers.php';require APP_PATH.'/Core/Autoloader.php';Autoloader::register();
$db=Database::connection();$assert=static function(bool $ok,string $label):void{if(!$ok)throw new RuntimeException('FALLÓ: '.$label);echo "OK  $label\n";};
$fixture=$db->query("SELECT p.id,p.status,u.id admin_id,pp.user_id student_id,(SELECT id FROM project_files f WHERE f.project_id=p.id LIMIT 1) file_id FROM projects p JOIN users u ON u.is_admin=1 AND u.status='active' JOIN project_participants pp ON pp.project_id=p.id AND pp.role_code='student' AND pp.status='active' AND pp.removed_at IS NULL WHERE p.deleted_at IS NULL LIMIT 1")->fetch();
if(!$fixture){fwrite(STDERR,"No existe una fixture apta.\n");exit(2);}
$project=(int)$fixture['id'];$admin=(int)$fixture['admin_id'];$student=(int)$fixture['student_id'];$file=(int)($fixture['file_id']??0);$status=(string)$fixture['status'];
$trackedTables=['projects','project_deliveries','project_observations','observation_responses','project_adjustment_requests','project_adjustment_request_responses','project_file_review_states','project_file_versions','project_audit_log','notifications'];$baseline=[];foreach($trackedTables as $table)$baseline[$table]=(int)$db->query("SELECT COUNT(*) FROM $table")->fetchColumn();$legacyBefore=(new ProjectRecordModel())->academicHistoryPage($project,0,15);
$db->beginTransaction();
try{
    $creator=$db->prepare('SELECT u.full_name FROM projects p LEFT JOIN users u ON u.id=p.created_by WHERE p.id=:project');$creator->execute(['project'=>$project]);$creatorName=(string)$creator->fetchColumn();
    $emptyCode='TIMELINE-'.strtoupper(bin2hex(random_bytes(5)));$q=$db->prepare("INSERT INTO projects(code,project_type_id,career_id,academic_period_id,title,status,current_stage,created_by) SELECT :code,project_type_id,career_id,academic_period_id,'Proyecto temporal de cronología','development','registration',:actor FROM projects WHERE id=:source");$q->execute(['code'=>$emptyCode,'actor'=>$admin,'source'=>$project]);$emptyProject=(int)$db->lastInsertId();
    $emptyPage=(new ProjectAcademicTimelineService($db))->page($emptyProject);$assert(count($emptyPage['events'])===1&&str_contains($emptyPage['events'][0]['description'],'sin una entrega'),'proyecto registrado sin entrega inicial');
    $q=$db->prepare("INSERT INTO project_deliveries(project_id,version_number,title,status,submitted_by) VALUES(:project,1,'Entrega inicial','submitted',:actor)");$q->execute(['project'=>$emptyProject,'actor'=>$student]);$withDelivery=(new ProjectAcademicTimelineService($db))->page($emptyProject);$assert(count($withDelivery['events'])===2&&!str_contains($withDelivery['events'][0]['description'],'junto con'),'proyecto registrado con entrega como evento real independiente');
    $deliveryVersion=(int)$db->query("SELECT COALESCE(MAX(version_number),0)+1 FROM project_deliveries WHERE project_id=$project")->fetchColumn();
    $q=$db->prepare("INSERT INTO project_deliveries(project_id,version_number,title,comment,status,submitted_by,submitted_at) VALUES(:project,:version,'Entrega de prueba','Contenido de entrega','under_review',:actor,'2026-08-01 10:00:01')");$q->execute(['project'=>$project,'version'=>$deliveryVersion,'actor'=>$student]);$delivery=(int)$db->lastInsertId();
    $q=$db->prepare("INSERT INTO project_observations(project_id,delivery_id,file_id,author_id,category,location_reference,body,status,created_at) VALUES(:project,:delivery,:file,:actor,'content','Sección 2','Texto exacto de observación','pending','2026-08-01 10:00:02')");$q->execute(['project'=>$project,'delivery'=>$delivery,'file'=>$file?:null,'actor'=>$admin]);$observation=(int)$db->lastInsertId();
    $q=$db->prepare("INSERT INTO observation_responses(observation_id,author_id,body,created_at) VALUES(:observation,:actor,'Respuesta leída desde body','2026-08-01 10:00:03')");$q->execute(['observation'=>$observation,'actor'=>$student]);
    $adjustment=(new ProjectAdjustmentRequestService())->createInTransaction($db,$project,$status,$admin,'academic_management',['request_type'=>'incorrect_data','message'=>'Ajuste administrativo de prueba.']);$request=(int)$adjustment['request']['id'];$version=(int)$adjustment['request']['lock_version'];
    $response=(new ProjectAdjustmentRequestService())->respondInTransaction($db,$project,$request,$version,$status,$student,'academic','Respuesta de ajuste.');$version=(int)$response['request']['lock_version'];
    $address=(new ProjectAdjustmentRequestService())->transitionInTransaction($db,$project,$request,$version,$status,$student,'academic','addressed');$version=(int)$address['request']['lock_version'];
    (new ProjectAdjustmentRequestService())->transitionInTransaction($db,$project,$request,$version,$status,$admin,'academic_management','closed');
    $audit=new ProjectAuditService($db);$audit->record($project,$admin,'project_document_review_completed','project_review',$project,['project_status'=>'under_review'],['project_status'=>'development','reviewed_documents'=>3,'approved'=>1,'under_review'=>1,'corrections_requested'=>1,'observation_count'=>1,'documents'=>[]]);
    $audit->record($project,$admin,'project_updated','project',$project,['status'=>'development'],['status'=>'under_review']);
    $audit->record($project,$admin,'project_corrections_requested','project',$project,['status'=>'under_review'],['status'=>'development','observation_count'=>1]);
    $audit->record($project,$admin,'project_approved','project',$project,['status'=>'under_review'],['status'=>'approved']);
    $audit->record($project,$admin,'tribunal_assigned','project',$project,null,['evidence'=>'test']);
    $audit->record($project,$admin,'project_tribunal_approved','project',$project,['status'=>'defense'],['status'=>'tribunal_approved']);
    $audit->record($project,$admin,'project_published','project',$project,['status'=>'approved'],['status'=>'published']);
    $audit->record($project,$admin,'project_publication_reverted','project',$project,['status'=>'published'],['status'=>'approved']);
    $postPublicationId=$audit->record($project,$admin,'project_updated','project',$project,['status'=>'approved'],['status'=>'under_review'],'Evento posterior a publicación');$q=$db->prepare('UPDATE project_audit_log SET created_at=DATE_ADD(created_at,INTERVAL 1 SECOND) WHERE id=:id');$q->execute(['id'=>$postPublicationId]);
    if($file>0){$checksum=hash('sha256','timeline-'.$project);$q=$db->prepare("INSERT INTO project_file_review_states(project_id,file_id,checksum_sha256,status,reviewed_by) VALUES(:project,:file,:checksum,'approved',:actor)");$q->execute(['project'=>$project,'file'=>$file,'checksum'=>$checksum,'actor'=>$admin]);$q->execute(['project'=>$project,'file'=>$file,'checksum'=>hash('sha256','timeline-corrections-'.$project),'actor'=>$admin]);$db->exec("UPDATE project_file_review_states SET status='corrections_requested' WHERE id=LAST_INSERT_ID()");
        $number=(int)$db->query("SELECT COALESCE(MAX(version_number),0)+1 FROM project_file_versions WHERE file_id=$file")->fetchColumn();$q=$db->prepare("INSERT INTO project_file_versions(file_id,project_id,version_number,original_name,storage_name,storage_path,extension,mime_type,size_bytes,checksum_sha256,replaced_by,replacement_reason,replaced_at) VALUES(:file,:project,:number,'timeline.pdf',:storage,'tests/timeline.pdf','pdf','application/pdf',1,:checksum,:actor,'Prueba','2026-08-01 10:00:04')");$q->execute(['file'=>$file,'project'=>$project,'number'=>$number,'storage'=>'timeline-'.$project.'-'.bin2hex(random_bytes(4)).'.pdf','checksum'=>$checksum,'actor'=>$admin]);}
    $service=new ProjectAcademicTimelineService($db);$all=[];$offset=0;$total=null;
    do{$page=$service->page($project,$offset,5);$total??=$page['total'];foreach($page['events'] as $event)$all[]=$event;$offset=$page['next_offset'];}while($page['has_more']);
    $keys=array_column($all,'event_key');$types=array_column($all,'event_type');
    $assert(count($keys)===count(array_unique($keys)),'cero claves duplicadas');$assert(count($all)===$total,'continuidad entre páginas');
    $reply=array_values(array_filter($all,static fn(array $event):bool=>$event['event_type']==='observation_responded'));
    $assert(count(array_filter($reply,static fn(array $event):bool=>$event['description']==='Respuesta leída desde body'))===1,'respuesta usa observation_responses.body');
    foreach(['adjustment_requested','adjustment_responded','adjustment_addressed','adjustment_closed','document_review_completed','delivery_registered','project_approved','tribunal_assigned','project_published','project_publication_reverted'] as $expected)$assert(in_array($expected,$types,true),'evento '.$expected);
    $reversionPosition=array_search('project_publication_reverted',$types,true);$lastStatusPosition=array_key_last(array_filter($types,static fn(string $type):bool=>$type==='project_updated'));$assert($reversionPosition!==false&&$lastStatusPosition!==null&&$lastStatusPosition>$reversionPosition,'evento posterior a publicación no truncado');
    $review=array_values(array_filter($all,static fn(array $event):bool=>$event['event_type']==='document_review_completed'))[0]??[];$assert(str_contains((string)($review['description']??''),'Aprobados: 1'),'revisión documental consolidada');
    $assert(count(array_filter($all,static fn(array $event):bool=>$event['event_type']==='file_version_registered'))>=($file>0?1:0),'nueva versión documental');
    if($file>0){$documentStates=array_values(array_filter($all,static fn(array $event):bool=>$event['event_type']==='document_status_recorded'));$stateLabels=array_column($documentStates,'description');$assert(in_array('Aprobado',$stateLabels,true),'documento aprobado');$assert(in_array('Correcciones solicitadas',$stateLabels,true),'documento con correcciones');}
    $assert(count(array_filter($all,static fn(array $event):bool=>str_contains($event['occurred_at_local'],'-05:00')))===count($all),'conversión America/Guayaquil');
    $required=['event_key','event_type','occurred_at_utc','occurred_at_local','source_type','source_id','actor','title','description','project_id','delivery','file','version','observation','adjustment','previous_state','new_state','badges','metadata','is_download_available'];
    $assert(array_diff($required,array_keys($all[0]??[]))===[],'contrato estable');
    $registration=array_values(array_filter($all,static fn(array $event):bool=>$event['event_type']==='project_registered'))[0]??[];$assert(!str_contains((string)($registration['description']??''),'junto con su primera entrega'),'registro no inventa entrega conjunta');$assert(($registration['actor']??'')===$creatorName,'registro usa projects.created_by');
    $d1=$db->prepare("INSERT INTO project_deliveries(project_id,version_number,title,comment,status,submitted_by,submitted_at) VALUES(:project,10,'Entrega 1','Contenido 1','under_review',:actor,'2026-08-01 10:10:00')");$d1->execute(['project'=>$emptyProject,'actor'=>$student]);$del1Id=(int)$db->lastInsertId();
    $d2=$db->prepare("INSERT INTO project_deliveries(project_id,version_number,title,comment,status,submitted_by,submitted_at) VALUES(:project,11,'Entrega 2','Contenido 2','under_review',:actor,'2026-08-01 10:20:00')");$d2->execute(['project'=>$emptyProject,'actor'=>$student]);$del2Id=(int)$db->lastInsertId();
    $audit->record($emptyProject,$student,'project_submitted_for_review','project_delivery',$del1Id,['status'=>'development'],['status'=>'under_review','delivery_id'=>$del1Id,'submitted_file_count'=>10]);
    $audit->record($emptyProject,$student,'project_submitted_for_review','project_delivery',$del2Id,['status'=>'development'],['status'=>'under_review','delivery_id'=>$del2Id,'submitted_file_count'=>14]);
    $historyHist=(new ProjectAcademicTimelineService($db))->page($emptyProject,0,50);
    $eventsHist=array_column($historyHist['events'],null,'event_key');
    $assert(isset($eventsHist['delivery:'.$del1Id])&&str_contains($eventsHist['delivery:'.$del1Id]['description'],'10 archivos enviados a revisión por el estudiante.'),'conteo histórico entrega 1 snapshot = 10');
    $assert(isset($eventsHist['delivery:'.$del2Id])&&str_contains($eventsHist['delivery:'.$del2Id]['description'],'14 archivos enviados a revisión por el estudiante.'),'conteo histórico entrega 2 snapshot = 14');

    $suffix=bin2hex(random_bytes(5));$q=$db->prepare("INSERT INTO users(email,password_hash,full_name,status) VALUES(:email,'test-only','Persona ajena','active')");$q->execute(['email'=>'timeline-'.$suffix.'@example.invalid']);$outsider=(int)$db->lastInsertId();
    $role=$db->prepare("INSERT INTO user_roles(user_id,role_id) SELECT :user,id FROM roles WHERE code='student'");$role->execute(['user'=>$outsider]);$assert(empty((new ProjectCapabilityService())->resolve(['id'=>$project,'created_by'=>$admin,'participants'=>[]],'academic',$outsider,['student'],false)['view_academic_history']),'usuario no relacionado sin acceso al historial');
}finally{if($db->inTransaction())$db->rollBack();}
$finalCounts=[];foreach($trackedTables as $table)$finalCounts[$table]=(int)$db->query("SELECT COUNT(*) FROM $table")->fetchColumn();$assert($baseline===$finalCounts,'escrituras revertidas y datos finales intactos');
$legacyAfter=(new ProjectRecordModel())->academicHistoryPage($project,0,15);$assert($legacyBefore===$legacyAfter,'Repositorio conserva su fuente sin regresión');
echo "Pruebas del historial académico finalizadas.\n";
