<?php
declare(strict_types=1);

final class AdminController
{
    public function settings():void{$model=new SystemSettingModel();$error=null;try{$settings=$model->all();}catch(Throwable $e){error_log('Admin settings: '.$e->getMessage());$error='No fue posible consultar la configuración.';$settings=$model->defaults();}$s=new AuthSessionService();View::render('admin/settings',['currentPage'=>'admin-settings','title'=>'Configuración | Administración','bodyClass'=>'admin-settings-page','pageStyles'=>[asset('css/admin-settings.css')],'pageScript'=>asset('js/admin-settings.js'),'settings'=>$settings,'settingsError'=>$error,'settingsCsrf'=>$s->csrfToken('admin_settings'),'settingsSaveEndpoint'=>route('admin-settings-save')]);}
    public function saveSettings():void{$this->requirePost();$s=new AuthSessionService();if(!$s->validateCsrf('admin_settings',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión venció.',[],419);try{(new SystemSettingModel())->save($_POST,(int)$s->userId());$this->json(true,'Configuración guardada y aplicada.');}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Save settings: '.$e->getMessage());$this->json(false,'No fue posible guardar la configuración.',[],500);}}
    public function reports():void{$from=$this->reportDate('from',date('Y-m-01'));$to=$this->reportDate('to',date('Y-m-d'));$model=new AdminReportModel();$error=null;try{$data=$model->dashboard($from,$to,PaginationService::request());}catch(Throwable $e){error_log('Admin reports: '.$e->getMessage());$error='No fue posible generar los reportes.';$data=['summary'=>['users'=>0,'projects'=>0,'deliveries'=>0,'actions'=>0],'roles'=>[],'statuses'=>[],'activity'=>[],'pagination'=>['total'=>0]];}View::render('admin/reports',['currentPage'=>'admin-reports','title'=>'Reportes | Administración','bodyClass'=>'admin-reports-page','pageStyles'=>[asset('css/admin-reports.css')],'reportData'=>$data,'pagePagination'=>$data['pagination'],'reportFrom'=>$from,'reportTo'=>$to,'reportError'=>$error]);}
    public function exportReport():never{$type=(string)($_GET['type']??'');$from=$this->reportDate('from',date('Y-m-01'));$to=$this->reportDate('to',date('Y-m-d'));if(!in_array($type,['users','projects','audit'],true)){http_response_code(422);exit('Reporte no válido.');}try{$report=(new AdminReportModel())->export($type,$from,$to);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="reporte-'.$type.'-'.$from.'-'.$to.'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');fputcsv($out,$report['headers'],';');foreach($report['rows'] as $row){$safe=array_map(static fn($cell):string=>preg_match('/^[=+\-@]/u',(string)$cell)?"'".(string)$cell:(string)$cell,array_values($row));fputcsv($out,$safe,';');}fclose($out);exit;}catch(Throwable $e){error_log('Export report: '.$e->getMessage());http_response_code(500);exit('No fue posible generar el reporte.');}}
    private function reportDate(string $key,string $fallback):string{$value=(string)($_GET[$key]??$fallback);$date=DateTimeImmutable::createFromFormat('Y-m-d',$value);return $date&&$date->format('Y-m-d')===$value?$value:$fallback;}
    public function trash():void{$model=new AdminTrashModel();$type=(string)($_GET['trash_type']??'users');$error=null;try{$data=$model->dashboard($type,PaginationService::request());}catch(Throwable $e){error_log('Admin trash: '.$e->getMessage());$error='No fue posible consultar la Papelera.';$data=['users'=>[],'projects'=>[],'pagination'=>['total'=>0],'active_type'=>'users','summary'=>['users'=>0,'projects'=>0,'expired'=>0]];}$s=new AuthSessionService();View::render('admin/trash',['currentPage'=>'admin-trash','title'=>'Papelera | Administración','bodyClass'=>'admin-trash-page','pageStyles'=>[asset('css/admin-trash.css')],'pageScript'=>asset('js/admin-trash.js'),'trashData'=>$data,'pagePagination'=>$data['pagination'],'trashError'=>$error,'trashCsrf'=>$s->csrfToken('admin_trash'),'trashEndpoints'=>['user'=>route('admin-trash-user'),'restore'=>route('admin-trash-restore'),'purge'=>route('admin-trash-purge')]]);}
    public function trashUser():void{$this->requirePost();$s=$this->trashSession();$id=(int)($_POST['id']??0);if($id===(int)$s->userId())$this->json(false,'No puedes eliminar tu propia cuenta.',[],422);try{(new AdminTrashModel())->trashUser($id,(string)($_POST['reason']??''),(int)$s->userId());$this->json(true,'Usuario enviado a la Papelera y acceso revocado.');}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Trash user: '.$e->getMessage());$this->json(false,'No fue posible eliminar el usuario.',[],500);}}
    public function restoreTrash():void{$this->requirePost();$s=$this->trashSession();try{(new AdminTrashModel())->restore((string)($_POST['entity']??''),(int)($_POST['id']??0),(int)$s->userId());$this->json(true,'Elemento restaurado correctamente.');}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){$this->json(false,'No fue posible restaurar el elemento.',[],500);}}
    public function purgeTrash():void{$this->requirePost();$s=$this->trashSession();try{$r=(new AdminTrashModel())->purgeExpired((int)$s->userId());$this->json(true,'Se procesaron '.$r['users'].' usuarios y '.$r['projects'].' proyectos vencidos.',$r);}catch(Throwable $e){error_log('Purge trash: '.$e->getMessage());$this->json(false,'No fue posible procesar los elementos vencidos.',[],500);}}
    private function trashSession():AuthSessionService{$s=new AuthSessionService();if(!$s->validateCsrf('admin_trash',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión venció.',[],419);return $s;}
    public function notifications():void{$model=new AdminNotificationModel();$error=null;try{$data=$model->dashboard(PaginationService::request());}catch(Throwable $e){error_log('Admin notifications: '.$e->getMessage());$error='No fue posible consultar el centro de notificaciones.';$data=['users'=>[],'projects'=>[],'sent'=>[],'pagination'=>['total'=>0],'summary'=>['sent'=>0,'recipients'=>0,'today'=>0]];}$s=new AuthSessionService();View::render('admin/notifications',['currentPage'=>'notifications','title'=>'Notificaciones | Administración','bodyClass'=>'admin-notifications-page','pageStyles'=>[asset('css/admin-notifications.css')],'pageScript'=>asset('js/admin-notifications.js'),'adminNotifications'=>$data,'pagePagination'=>$data['pagination'],'adminNotificationsError'=>$error,'adminNotificationCsrf'=>$s->csrfToken('admin_notifications'),'adminNotificationSendEndpoint'=>route('admin-notification-send')]);}
    public function sendNotification():void{$this->requirePost();$s=new AuthSessionService();if(!$s->validateCsrf('admin_notifications',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión venció.',[],419);try{$result=(new AdminNotificationModel())->send($_POST,(int)$s->userId());$this->json(true,'Notificación enviada a '.$result['recipients'].' destinatarios.',$result);}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Admin send notification: '.$e->getMessage());$this->json(false,'No fue posible enviar la notificación.',[],500);}}
    public function repository():void{$model=new AdminRepositoryModel();$filter=(string)($_GET['status']??'');$error=null;try{$result=$model->listing($filter,PaginationService::request());$projects=$result['items'];$pagination=$result['pagination'];$summary=$model->summary();}catch(Throwable $e){error_log('Admin repository: '.$e->getMessage());$error='No fue posible consultar las publicaciones.';$projects=[];$pagination=['total'=>0];$summary=['eligible'=>0,'published'=>0,'incomplete'=>0];}$s=new AuthSessionService();View::render('admin/repository',['currentPage'=>'repository','title'=>'Repositorio | Administración','bodyClass'=>'admin-repository-page','pageStyles'=>[asset('css/admin-repository.css')],'pageScript'=>asset('js/admin-repository.js'),'repositoryProjects'=>$projects,'pagePagination'=>$pagination,'repositorySummary'=>$summary,'repositoryFilter'=>$filter,'repositoryError'=>$error,'repositoryCsrf'=>$s->csrfToken('admin_repository'),'repositoryPublishEndpoint'=>route('admin-repository-publish')]);}
    public function publishProject():void{$this->requirePost();$s=new AuthSessionService();if(!$s->validateCsrf('admin_repository',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión venció.',[],419);try{$publish=($_POST['action']??'publish')==='publish';(new AdminRepositoryModel())->setPublished((int)($_POST['id']??0),$publish,(int)$s->userId());$this->json(true,$publish?'Proyecto publicado correctamente.':'Publicación retirada; el expediente permanece conservado.');}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Publish project: '.$e->getMessage());$this->json(false,'No fue posible actualizar la publicación.',[],500);}}
    public function academic():void{$model=new AdminAcademicModel();$error=null;try{$data=$model->dashboard();}catch(Throwable $e){error_log('Admin academic: '.$e->getMessage());$error='No fue posible consultar la configuración académica.';$data=['periods'=>[],'careers'=>[],'types'=>[],'lines'=>[],'subjects'=>[],'teachers'=>[],'promotion'=>['source'=>null,'targets'=>[],'students'=>0]];}$s=new AuthSessionService();View::render('admin/academic',['currentPage'=>'admin-academic','title'=>'Gestión académica | Administración','bodyClass'=>'admin-academic-page','pageStyles'=>[asset('css/admin-academic.css')],'pageScript'=>asset('js/admin-academic.js'),'academic'=>$data,'academicError'=>$error,'academicCsrf'=>$s->csrfToken('admin_academic'),'academicEndpoints'=>['save'=>route('admin-academic-save'),'promote'=>route('admin-academic-promote')]]);}
    public function saveAcademic():void{$this->requirePost();$s=new AuthSessionService();if(!$s->validateCsrf('admin_academic',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión venció.',[],419);try{(new AdminAcademicModel())->save((string)($_POST['entity']??''),$_POST,(int)$s->userId());$this->json(true,'Información académica guardada correctamente.');}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Save academic: '.$e->getMessage());$this->json(false,'No fue posible guardar la información.',[],500);}}
    public function promoteAcademicPeriod():void{$this->requirePost();$s=new AuthSessionService();if(!$s->validateCsrf('admin_academic',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión venció.',[],419);try{$result=(new AdminAcademicModel())->promote((int)($_POST['target_period_id']??0),(int)$s->userId());$this->json(true,$result['promoted'].' estudiantes avanzaron de semestre y '.$result['completed'].' completaron su último nivel.',$result);}catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Promote academic: '.$e->getMessage());$this->json(false,'No fue posible realizar el cambio de periodo.',[],500);}}
    public function projects(): void
    {
        $model=new AdminProjectModel();$filters=['search'=>mb_substr(trim((string)($_GET['search']??'')),0,100),'status'=>(string)($_GET['status']??''),'type_id'=>(int)($_GET['type_id']??0),'period_id'=>(int)($_GET['period_id']??0),'group'=>(string)($_GET['group']??''),'attention'=>(string)($_GET['attention']??'')];$error=null;
        try{$result=$model->listing($filters,PaginationService::request());$projects=$result['items'];$pagination=$result['pagination'];$summary=$model->summary();$catalogs=$model->catalogs();}catch(Throwable $exception){error_log('Admin projects: '.$exception->getMessage());$error='No fue posible consultar los proyectos.';$projects=[];$pagination=['total'=>0];$summary=['total'=>0,'development'=>0,'review'=>0,'approved'=>0,'defense'=>0];$catalogs=['types'=>[],'careers'=>[],'periods'=>[],'teachers'=>[]];}
        $session=new AuthSessionService();View::render('admin/projects',['currentPage'=>'projects','title'=>'Proyectos | Administración','bodyClass'=>'admin-projects-page','pageStyles'=>[asset('css/admin-projects.css')],'pageScript'=>asset('js/admin-projects.js'),'projects'=>$projects,'pagePagination'=>$pagination,'projectSummary'=>$summary,'catalogs'=>$catalogs,'filters'=>$filters,'projectError'=>$error,'projectCsrf'=>$session->csrfToken('admin_projects'),'projectEndpoints'=>['save'=>route('admin-project-save'),'trash'=>route('admin-project-trash')]]);
    }
    public function saveProject():void{$this->requirePost();$session=new AuthSessionService();if(!$session->validateCsrf('admin_projects',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión del formulario venció.',[],419);try{$id=(int)($_POST['id']??0);$payload=['title'=>trim((string)($_POST['title']??'')),'subtitle'=>trim((string)($_POST['subtitle']??'')),'project_type_id'=>(int)($_POST['project_type_id']??0),'career_id'=>(int)($_POST['career_id']??0),'academic_period_id'=>(int)($_POST['academic_period_id']??0),'tutor_id'=>(int)($_POST['tutor_id']??0),'status'=>(string)($_POST['status']??'development')];$saved=(new AdminProjectModel())->save($payload,$id,(int)$session->userId());$this->json(true,$id?'Proyecto actualizado correctamente.':'Proyecto creado correctamente.',['id'=>$saved]);}catch(InvalidArgumentException $exception){$this->json(false,$exception->getMessage(),[],422);}catch(Throwable $exception){error_log('Admin save project: '.$exception->getMessage());$this->json(false,'No fue posible guardar el proyecto.',[],500);}}
    public function trashProject():void{$this->requirePost();$session=new AuthSessionService();if(!$session->validateCsrf('admin_projects',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión del formulario venció.',[],419);try{(new AdminProjectModel())->trash((int)($_POST['id']??0),(string)($_POST['reason']??''),(int)$session->userId());$this->json(true,'Proyecto enviado a la Papelera. Se conservará para restauración.');}catch(InvalidArgumentException $exception){$this->json(false,$exception->getMessage(),[],422);}catch(Throwable $exception){error_log('Admin trash project: '.$exception->getMessage());$this->json(false,'No fue posible enviar el proyecto a la Papelera.',[],500);}}
    public function users(): void
    {
        $model = new AdminUserModel();
        $filters = ['search'=>mb_substr(trim((string)($_GET['search']??'')),0,100),'role'=>(string)($_GET['role']??''),'status'=>(string)($_GET['status']??'')];
        $error = null;
        try { $result=$model->listing($filters,PaginationService::request());$users=$result['items'];$pagination=$result['pagination']; $summary=$model->summary(); $catalogs=$model->catalogs(); }
        catch(Throwable $exception){ error_log('Admin users error: '.$exception->getMessage());$error='No fue posible consultar los usuarios.';$users=[];$pagination=['total'=>0];$summary=['total'=>0,'active'=>0,'blocked'=>0,'students'=>0,'teachers'=>0,'administrators'=>0];$catalogs=['career'=>null,'period'=>null]; }
        $session=new AuthSessionService();
        View::render('admin/users',['currentPage'=>'admin-users','title'=>'Usuarios | Administración','bodyClass'=>'admin-users-page','pageStyles'=>[asset('css/admin-users.css'),asset('css/admin-user-import.css')],'pageScript'=>asset('js/admin-users.js'),'pageScripts'=>[asset('js/admin-user-import.js')],'users'=>$users,'pagePagination'=>$pagination,'userSummary'=>$summary,'catalogs'=>$catalogs,'filters'=>$filters,'adminUserCsrf'=>$session->csrfToken('admin_users'),'adminUserEndpoints'=>['save'=>route('admin-user-save'),'status'=>route('admin-user-status'),'password'=>route('admin-user-password'),'import'=>route('admin-users-import')],'adminUsersError'=>$error]);
    }

    public function saveUser(): void
    {
        $this->requirePost(); $session=$this->sessionAndCsrf();
        try {
            $id=(int)($_POST['id']??0);$payload=$this->userPayload();
            if($id===(int)$session->userId()&&($payload['role']!=='administrator'||$payload['status']!=='active'))throw new InvalidArgumentException('No puedes retirar tu propio acceso administrativo.');
            $saved=(new AdminUserModel())->save($payload,$id,(int)$session->userId());
            $this->json(true,$id>0?'Usuario actualizado correctamente.':'Usuario creado correctamente.',['user'=>$saved]);
        } catch(InvalidArgumentException $exception){$this->json(false,$exception->getMessage(),[],422);}
        catch(Throwable $exception){error_log('Save admin user: '.$exception->getMessage());$this->json(false,'No fue posible guardar el usuario.',[],500);}
    }

    public function changeUserStatus(): void
    {
        $this->requirePost();$session=$this->sessionAndCsrf();$id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'');
        if($id===(int)$session->userId())$this->json(false,'No puedes bloquear o desactivar tu propia cuenta.',[],422);
        try{(new AdminUserModel())->changeStatus($id,$status,(int)$session->userId());$this->json(true,'Estado de acceso actualizado.');}
        catch(InvalidArgumentException $exception){$this->json(false,$exception->getMessage(),[],422);}
        catch(Throwable $exception){error_log('Admin user status: '.$exception->getMessage());$this->json(false,'No fue posible actualizar el acceso.',[],500);}
    }

    public function resetUserPassword(): void
    {
        $this->requirePost();$session=$this->sessionAndCsrf();$id=(int)($_POST['id']??0);
        try{(new AdminUserModel())->resetPassword($id,'Istel2026+',(int)$session->userId());$this->json(true,'Contraseña temporal restablecida. El usuario deberá cambiarla.');}
        catch(InvalidArgumentException $exception){$this->json(false,$exception->getMessage(),[],422);}
        catch(Throwable $exception){error_log('Admin password reset: '.$exception->getMessage());$this->json(false,'No fue posible restablecer la contraseña.',[],500);}
    }

    public function importUsers(): void
    {
        $this->requirePost();$session=$this->sessionAndCsrf();$content=trim((string)($_POST['content']??''));
        if(isset($_FILES['file'])&&($_FILES['file']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$file=$_FILES['file'];if(($file['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK)$this->json(false,'No fue posible leer el archivo.',[],422);$extension=mb_strtolower(pathinfo((string)$file['name'],PATHINFO_EXTENSION));if(!in_array($extension,['csv','txt'],true))$this->json(false,'Utiliza un archivo CSV o TXT.',[],422);if((int)$file['size']>1048576)$this->json(false,'El archivo no puede superar 1 MB.',[],422);$content=(string)file_get_contents((string)$file['tmp_name']);}
        try{$model=new AdminUserModel();$config=['role'=>(string)($_POST['role']??''),'career_id'=>(int)($_POST['career_id']??0),'academic_period_id'=>(int)($_POST['academic_period_id']??0),'semester'=>(int)($_POST['semester']??0),'can_tutor'=>isset($_POST['can_tutor'])?1:0];$preview=$model->previewImport($content,$config);if(($_POST['mode']??'preview')==='import'){$result=$model->bulkImport($content,$config,(int)$session->userId());$this->json(true,$result['created'].' usuarios fueron creados correctamente.',$result);} $this->json(true,'Vista previa generada.',$preview);}
        catch(InvalidArgumentException $exception){$this->json(false,$exception->getMessage(),[],422);}
        catch(Throwable $exception){error_log('Admin bulk import: '.$exception->getMessage());$this->json(false,'No fue posible procesar la lista.',[],500);}
    }

    public function module(string $section): void
    {
        $modules=['academic'=>['Gestión académica','fa-graduation-cap','Periodos, matrículas y catálogos se habilitarán en la Fase 4.'],'reports'=>['Reportes','fa-chart-column','Los reportes administrativos se habilitarán al completar los módulos de datos.'],'settings'=>['Configuración','fa-gear','Los parámetros institucionales se incorporarán en la Fase 6.'],'trash'=>['Papelera','fa-trash-can','La restauración y purga a 60 días se incorporará en la Fase 7.']];
        if(!isset($modules[$section])){$this->users();return;}$item=$modules[$section];
        View::render('admin/module-pending',['currentPage'=>'admin-'.$section,'title'=>$item[0].' | Administración','bodyClass'=>'admin-page','pageStyles'=>[asset('css/admin-access.css')],'moduleTitle'=>$item[0],'moduleIcon'=>$item[1],'moduleMessage'=>$item[2]]);
    }

    private function userPayload(): array
    {
        return ['full_name'=>trim((string)($_POST['full_name']??'')),'email'=>mb_strtolower(trim((string)($_POST['email']??''))),'username'=>trim((string)($_POST['username']??'')),'role'=>(string)($_POST['role']??''),'status'=>(string)($_POST['status']??'active'),'institutional_code'=>trim((string)($_POST['institutional_code']??'')),'career_id'=>(int)($_POST['career_id']??0),'academic_period_id'=>(int)($_POST['academic_period_id']??0),'semester'=>(int)($_POST['semester']??0),'academic_title'=>trim((string)($_POST['academic_title']??'')),'can_tutor'=>isset($_POST['can_tutor'])?1:0];
    }
    private function sessionAndCsrf(): AuthSessionService{$session=new AuthSessionService();if(!$session->validateCsrf('admin_users',(string)($_POST['_csrf']??'')))$this->json(false,'La sesión del formulario venció.',[],419);return $session;}
    private function requirePost(): void{if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST'){$this->json(false,'Método no permitido.',[],405);}}
    private function json(bool $success,string $message,array $data=[],int $status=200): never{$status=$status===419?403:$status;http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode(['success'=>$success,'message'=>$message,'data'=>$data],JSON_UNESCAPED_UNICODE);exit;}
}
