<?php
declare(strict_types=1);
final class ProjectDocumentController
{
    public function change():void
    {
        $this->post();$session=new AuthSessionService();if(!$session->validateCsrf('admin_repository',(string)($_POST['_csrf']??'')))$this->json(false,'La solicitud contiene un token CSRF inválido.',[],419);
        $projectId=(int)($_POST['project_id']??$_POST['material_id']??0);$action=(string)($_POST['action']??'');$actor=(int)$session->userId();$model=new ProjectDocumentModel();$storage=new ProjectDocumentFileService();$stored=[];
        try{
            if($projectId<1)throw new InvalidArgumentException('El proyecto no es válido.');
            if($action==='list_restorable'){$files=$model->restorable($projectId);$this->json(true,'Archivos retirados consultados correctamente.',['files'=>$files,'count'=>count($files),'restore_hours'=>24]);}
            if($action==='inspect_restore'){$result=Database::transaction(fn(PDO $db)=>$model->inspectRestore($projectId,(int)($_POST['file_id']??0)));$this->json(true,'Archivo disponible para restaurar.',$result);}
            if($action==='add'){
                $uploads=$this->uploads($_FILES['files']??[]);$limits=$storage->limits();if($uploads===[])$this->json(false,'Selecciona al menos un archivo.',[],422);if(count($uploads)>(int)$limits['max_operation_files'])$this->json(false,'Puedes agregar hasta '.$limits['max_operation_files'].' archivos por operación.',[],422);if(array_sum(array_map(static fn(array $upload):int=>(int)($upload['size']??0),$uploads))>(int)$limits['max_operation_bytes'])$this->json(false,'La selección completa supera el límite de 35 MB por operación.',[],422);
                $added=[];$failed=[];foreach($uploads as $upload){$stored=[];try{$stored=$storage->storeUpload($projectId,$upload);$file=Database::transaction(function(PDO $db)use($model,$projectId,$stored,$actor){$model->lockProject($projectId);$conflict=$model->activeFileConflict($projectId,(string)$stored['original_name'],(int)$stored['size_bytes'],(string)$stored['checksum_sha256']);if($conflict!==null)throw new InvalidArgumentException(($conflict['conflict_type']??'')==='name_size'?'Ya existe un archivo activo con el mismo nombre y tamaño. Utiliza Reemplazar archivo para actualizarlo.':'Ya existe un archivo activo con el mismo contenido. Utiliza Reemplazar archivo para actualizarlo.');$file=$model->add($projectId,$stored,$actor);$this->audit($db,$actor,'project.file_added','Agregó un archivo al proyecto',$projectId,$file);$this->notifyAuthors($db,$projectId,'Se agregó un archivo al proyecto','El archivo '.$file['original_name'].' fue agregado al expediente.');return $file;});$added[]=$this->filePayload($file,$projectId);}catch(Throwable $e){$storage->discardStored($stored);$failed[]=['name'=>$upload['name']??'Archivo','message'=>$e instanceof InvalidArgumentException?$e->getMessage():'No fue posible procesar este archivo.'];}}
                $requested=count($uploads);$addedCount=count($added);$failedCount=count($failed);$data=['summary'=>['requested'=>$requested,'added'=>$addedCount,'failed'=>$failedCount],'added'=>$added,'failed'=>$failed,'package'=>$this->packageDescriptor($model,$projectId)];if($addedCount===0)$this->json(false,'No se pudo agregar ningún archivo.',$data,422);$message=$failedCount>0?$addedCount.($addedCount===1?' archivo agregado y ':' archivos agregados y ').$failedCount.($failedCount===1?' no pudo procesarse.':' no pudieron procesarse.'):$addedCount.($addedCount===1?' archivo agregado correctamente.':' archivos agregados correctamente.');$this->json(true,$message,$data,$failedCount>0?207:200);
            }
            if($action==='replace'){
                $fileId=(int)($_POST['file_id']??0);$stored=$storage->storeUpload($projectId,(array)($_FILES['file']??[]));
                try{$result=Database::transaction(function(PDO $db)use($model,$projectId,$fileId,$stored,$actor){$model->lockProject($projectId);$result=$model->replace($projectId,$fileId,$stored,$actor,trim((string)($_POST['reason']??'')));$this->audit($db,$actor,'project.file_replaced','Reemplazó un archivo del proyecto',$projectId,$result['file'],['version_number'=>$result['version_number'],'previous_name'=>$result['old']['original_name']]);$this->notifyAuthors($db,$projectId,'Se reemplazó un archivo del proyecto','El archivo '.$result['old']['original_name'].' tiene una nueva versión en el expediente.');return $result;});}catch(Throwable $e){$storage->discardStored($stored);throw $e;}
                $this->json(true,'Archivo reemplazado correctamente.',['file'=>$this->filePayload($result['file'],$projectId),'package'=>$this->packageDescriptor($model,$projectId)]);
            }
            if(in_array($action,['presentation','unpresentation'],true)){
                $fileId=(int)($_POST['file_id']??0);$target=$action==='presentation'?$fileId:null;$result=Database::transaction(function(PDO $db)use($model,$projectId,$target,$fileId,$actor,$action){$change=$model->setPresentation($projectId,$target,$actor);$file=$model->findActiveFile($projectId,$fileId);$this->audit($db,$actor,$action==='presentation'?'project.presentation_changed':'project.presentation_removed',$action==='presentation'?'Cambió el archivo de presentación':'Quitó el archivo de presentación',$projectId,$file,$change);$this->notifyAuthors($db,$projectId,'Se actualizó el archivo de presentación','La presentación documental del proyecto fue actualizada.');return $change;});
                $this->json(true,$action==='presentation'?'Archivo de presentación actualizado correctamente.':'Archivo de presentación eliminado correctamente.',['file_id'=>$fileId,'presentation'=>$target!==null]+$result);
            }
            if(in_array($action,['remove','remove_multiple'],true)){
                $ids=$action==='remove_multiple'?(array)($_POST['file_ids']??[]):[(int)($_POST['file_id']??0)];$removal=Database::transaction(function(PDO $db)use($model,$projectId,$ids,$actor){$project=$model->lockProject($projectId);$files=$model->retire($projectId,$ids,$actor);foreach($files as $file)$this->audit($db,$actor,'project.file_removed','Retiró un archivo del proyecto',$projectId,$file,['restore_hours'=>24]);$this->notifyAuthors($db,$projectId,'Se retiraron archivos del proyecto',count($files)===1?'El archivo '.$files[0]['original_name'].' fue retirado del expediente.':count($files).' archivos fueron retirados del expediente.');$removedIds=array_map(fn($file)=>(int)$file['id'],$files);$presentationId=$project['presentation_file_id']===null?null:(int)$project['presentation_file_id'];return ['files'=>$files,'presentation_removed'=>$presentationId!==null&&in_array($presentationId,$removedIds,true),'presentation_file_id'=>$presentationId!==null&&!in_array($presentationId,$removedIds,true)?$presentationId:null];});$files=$removal['files'];
                $this->json(true,count($files)===1?'Archivo retirado. Podrá recuperarse durante 24 horas.':'Archivos retirados. Podrán recuperarse durante 24 horas.',['removed_file_ids'=>array_map(fn($f)=>(int)$f['id'],$files),'presentation_removed'=>$removal['presentation_removed'],'presentation_file_id'=>$removal['presentation_file_id'],'restorable_count'=>count($model->restorable($projectId)),'package'=>$this->packageDescriptor($model,$projectId)]);
            }
            if($action==='restore'){
                $fileId=(int)($_POST['file_id']??0);$file=Database::transaction(function(PDO $db)use($model,$projectId,$fileId,$actor){$model->lockProject($projectId);$file=$model->restore($projectId,$fileId,$actor,(string)($_POST['final_name']??''));$this->audit($db,$actor,'project.file_restored','Restauró un archivo del proyecto',$projectId,$file);$this->notifyAuthors($db,$projectId,'Se restauró un archivo del proyecto','El archivo '.$file['original_name'].' volvió a estar disponible.');return $file;});
                $this->json(true,'Archivo restaurado correctamente.',['file'=>$this->filePayload($file,$projectId),'restorable_count'=>count($model->restorable($projectId)),'package'=>$this->packageDescriptor($model,$projectId)]);
            }
            if($action==='purge_restorable'){
                $ids=(array)($_POST['file_ids']??[]);$db=Database::connection();$staged=[];
                try{$db->beginTransaction();$model->lockProject($projectId);$files=$model->purge($projectId,$ids,$actor);foreach($files as $file){$path=$storage->resolveStoredFile($projectId,$file['storage_name']);$temporary=$path.'.purge-'.bin2hex(random_bytes(6));if(!rename($path,$temporary))throw new RuntimeException('No fue posible preparar la eliminación física del archivo.');$staged[]=['source'=>$path,'temporary'=>$temporary];$this->audit($db,$actor,'project.file_purged','Eliminó definitivamente un archivo retirado',$projectId,$file);}$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();foreach(array_reverse($staged) as $item)if(is_file($item['temporary'])&&!is_file($item['source']))@rename($item['temporary'],$item['source']);throw $e;}
                foreach($staged as $item)if(is_file($item['temporary']))@unlink($item['temporary']);
                $this->json(true,count($files)===1?'Archivo eliminado definitivamente.':'Archivos eliminados definitivamente.',['purged_file_ids'=>array_map(fn($f)=>(int)$f['id'],$files),'restorable_count'=>count($model->restorable($projectId))]);
            }
            throw new InvalidArgumentException('La acción documental no es válida.');
        }catch(InvalidArgumentException $e){$this->json(false,$e->getMessage(),[],422);}catch(Throwable $e){error_log('Project documents: '.$e->getMessage());$this->json(false,'No fue posible completar la operación documental. No se realizaron cambios.',[],500);}
    }
    public function package():void
    {
        $projectId=(int)($_GET['project_id']??0);try{$access=new ProjectAccessService();$administrator=(new AuthSessionService())->hasAdminAccess();$repositoryScope=(string)($_GET['scope']??'')==='repository';$project=$projectId>0&&$access->can('project.view')?(new ProjectRecordModel())->find($projectId,$access->currentUserId(),$administrator,$repositoryScope):null;if($project===null){http_response_code(404);exit('El proyecto solicitado no está disponible.');}$model=new ProjectDocumentModel();$package=(new ProjectPackageService())->prepare($projectId,$model->activeFiles($projectId));if(!empty($package['temporary'])){$temporaryPath=(string)$package['path'];register_shutdown_function(static function()use($temporaryPath):void{if(is_file($temporaryPath))@unlink($temporaryPath);});}$stream=fopen($package['path'],'rb');$size=filesize($package['path']);if(!$stream||$size===false||$size<1)throw new RuntimeException();header('Content-Type: application/zip');header('Content-Length: '.$size);header('Content-Disposition: attachment; filename="expediente-proyecto-'.$projectId.'.zip"');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store, max-age=0');session_write_close();fpassthru($stream);fclose($stream);if(!empty($package['temporary']))@unlink((string)$package['path']);exit;}catch(Throwable $error){error_log('Project package: '.$error->getMessage());http_response_code(422);exit('No fue posible generar el paquete completo porque uno o más archivos no están disponibles. No se descargó un paquete incompleto.');}
    }
    private function packageDescriptor(ProjectDocumentModel $model,int $id):array{return (new ProjectPackageService())->describe($id,$model->activeFiles($id));}
    private function filePayload(array $f,int $projectId):array{$ext=strtolower((string)$f['extension']);$query='&project_id='.$projectId.'&file_id='.(int)$f['id'].'&scope=repository';$version=!empty($f['checksum_sha256'])?'&v='.rawurlencode(substr((string)$f['checksum_sha256'],0,16)):'';return ['id'=>(int)$f['id'],'name'=>$f['original_name'],'extension'=>$ext,'type'=>strtoupper($ext),'size_label'=>ArchiveService::formatBytes((int)$f['size_bytes']),'size_bytes'=>(int)$f['size_bytes'],'sort_order'=>(int)$f['sort_order'],'is_archive'=>$ext==='zip','preview_supported'=>in_array($ext,['pdf','docx','png','jpg','jpeg','webp','txt'],true),'preview_type'=>in_array($ext,['jpg','jpeg','png','webp'],true)?'image':$ext,'preview_url'=>route('project-file-preview').$query.$version,'download_url'=>route('project-file-download').$query,'zip_url'=>'','zip_entry_preview_url'=>'','zip_entry_download_url'=>''];}
    private function audit(PDO $db,int $actor,string $action,string $label,int $projectId,array $file,array $extra=[]):void
    {
        $details=['file_id'=>(int)($file['id']??0),'name'=>$file['original_name']??'','size_bytes'=>(int)($file['size_bytes']??0)]+$extra;
        (new AdminActivityService($db))->record($actor,$action,$label,'Repositorio','project',$projectId,(string)($file['original_name']??'Archivo'),'correct',$details);
        (new ProjectAuditService($db))->record($projectId,$actor,$action,'project_file',(int)($file['id']??0),null,$details,$label);
    }
    private function notifyAuthors(PDO $db,int $projectId,string $title,string $message):void{$q=$db->prepare("INSERT INTO notifications(user_id,project_id,type,title,message,action_url,metadata) SELECT DISTINCT pp.user_id,:project,'repository',:title,:message,:url,:metadata FROM project_participants pp JOIN student_profiles sp ON sp.user_id=pp.user_id WHERE pp.project_id=:project2 AND pp.role_code='student' AND pp.status='active' AND pp.removed_at IS NULL");$q->execute(['project'=>$projectId,'title'=>$title,'message'=>$message,'url'=>route('project-detail').'&id='.$projectId.'&context=repository&tab=files','metadata'=>json_encode(['purpose'=>'project_document_change'],JSON_UNESCAPED_UNICODE),'project2'=>$projectId]);}
    private function uploads(array $bag):array{if(!is_array($bag['name']??null))return $bag?[$bag]:[];$out=[];foreach($bag['name'] as $i=>$name)$out[]=['name'=>$name,'type'=>$bag['type'][$i]??'','tmp_name'=>$bag['tmp_name'][$i]??'','error'=>$bag['error'][$i]??UPLOAD_ERR_NO_FILE,'size'=>$bag['size'][$i]??0];return $out;}
    private function post():void{if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')$this->json(false,'Método no permitido.',[],405);}
    private function json(bool $success,string $message,array $data=[],int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode(['success'=>$success,'message'=>$message,'data'=>$data],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
}
