<?php
declare(strict_types=1);
final class AdminTrashModel
{
 public function dashboard(string $type='users',array $pagination=[]):array{$d=Database::connection();$type=in_array($type,['users','projects'],true)?$type:'users';$candidates=$d->query("SELECT id,full_name,email FROM users WHERE deleted_at IS NULL AND purged_at IS NULL AND status<>'inactive' ORDER BY full_name LIMIT 200")->fetchAll();$userCount=(int)$d->query("SELECT COUNT(*) FROM users WHERE deleted_at IS NOT NULL AND purged_at IS NULL")->fetchColumn();$projectCount=(int)$d->query("SELECT COUNT(*) FROM projects WHERE deleted_at IS NOT NULL")->fetchColumn();$expired=(int)$d->query("SELECT (SELECT COUNT(*) FROM users WHERE deleted_at<DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 60 DAY) AND purged_at IS NULL)+(SELECT COUNT(*) FROM projects WHERE deleted_at<DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 60 DAY))")->fetchColumn();if($type==='projects'){$from=" FROM projects p LEFT JOIN users u ON u.id=p.deleted_by WHERE p.deleted_at IS NOT NULL";$data="SELECT p.id,p.code,p.title,p.deleted_at,p.deletion_reason,u.full_name deleted_by_name,GREATEST(0,60-DATEDIFF(CURRENT_DATE,DATE(p.deleted_at))) days_left".$from.' ORDER BY p.deleted_at DESC';}else{$from=" FROM users u LEFT JOIN users a ON a.id=u.deleted_by WHERE u.deleted_at IS NOT NULL AND u.purged_at IS NULL";$data="SELECT u.id,u.full_name,u.email,u.deleted_at,u.deletion_reason,a.full_name deleted_by_name,GREATEST(0,60-DATEDIFF(CURRENT_DATE,DATE(u.deleted_at))) days_left".$from.' ORDER BY u.deleted_at DESC';}$result=PaginationService::run($d,'SELECT COUNT(*)'.$from,$data,[],$pagination?:PaginationService::request());return ['candidates'=>$candidates,'users'=>$type==='users'?$result['items']:[],'projects'=>$type==='projects'?$result['items']:[],'pagination'=>$result['pagination'],'active_type'=>$type,'summary'=>['users'=>$userCount,'projects'=>$projectCount,'expired'=>$expired]];}
 public function trashUser(int $id,string $reason,int $actor):void{if($id<1||mb_strlen(trim($reason))<5)throw new InvalidArgumentException('Indica un motivo de al menos cinco caracteres.');Database::transaction(function(PDO $d)use($id,$reason,$actor):void{$read=$d->prepare('SELECT id,status,is_admin,is_initial_admin FROM users WHERE id=:id AND deleted_at IS NULL AND purged_at IS NULL FOR UPDATE');$read->execute(['id'=>$id]);$user=$read->fetch();if(!$user)throw new InvalidArgumentException('El usuario ya no está disponible.');if((bool)$user['is_admin']&&$user['status']==='active'){$admins=$d->prepare("SELECT COUNT(*) FROM users WHERE is_admin=1 AND status='active' AND deleted_at IS NULL AND purged_at IS NULL AND id<>:id");$admins->execute(['id'=>$id]);if((int)$admins->fetchColumn()<1)throw new InvalidArgumentException(AdminUserModel::LAST_ADMIN_MESSAGE);}$q=$d->prepare('UPDATE users SET status=\'inactive\',deleted_at=CURRENT_TIMESTAMP,deleted_by=:actor,deletion_reason=:reason,session_version=session_version+1 WHERE id=:id');$q->execute(['actor'=>$actor,'reason'=>trim($reason),'id'=>$id]);$this->audit($d,$actor,'user_trashed','user',$id,['reason'=>trim($reason)]);if((bool)$user['is_initial_admin'])$this->audit($d,$actor,'initial_admin_deactivated','user',$id,['reason'=>trim($reason),'via'=>'trash']);});}
 public function restore(string $entity,int $id,int $actor):void{if(!in_array($entity,['user','project'],true)||$id<1)throw new InvalidArgumentException('El elemento no es válido.');Database::transaction(function(PDO $d)use($entity,$id,$actor):void{$restoredAdmin=false;if($entity==='user'){$read=$d->prepare('SELECT is_admin FROM users WHERE id=:id AND deleted_at IS NOT NULL AND purged_at IS NULL FOR UPDATE');$read->execute(['id'=>$id]);$restoredAdmin=(bool)$read->fetchColumn();$q=$d->prepare("UPDATE users SET status='active',deleted_at=NULL,deleted_by=NULL,deletion_reason=NULL,session_version=session_version+1 WHERE id=:id AND deleted_at IS NOT NULL AND purged_at IS NULL");}else{$q=$d->prepare('UPDATE projects SET deleted_at=NULL,deleted_by=NULL,deletion_reason=NULL WHERE id=:id AND deleted_at IS NOT NULL');}$q->execute(['id'=>$id]);if($q->rowCount()!==1)throw new InvalidArgumentException('El elemento ya no puede restaurarse.');$this->audit($d,$actor,$entity.'_restored',$entity,$id,[]);if($restoredAdmin)$this->audit($d,$actor,'admin_access_reactivated','user',$id,['via'=>'trash_restore']);});}
 public function purgeExpired(int $actor):array{return Database::transaction(function(PDO $d)use($actor):array{$users=$d->query("SELECT id FROM users WHERE deleted_at<DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 60 DAY) AND purged_at IS NULL FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN);foreach($users as $id){$d->prepare('DELETE FROM student_enrollments WHERE student_id=:id')->execute(['id'=>$id]);$d->prepare('DELETE FROM student_profiles WHERE user_id=:id')->execute(['id'=>$id]);$d->prepare('DELETE FROM teacher_profiles WHERE user_id=:id')->execute(['id'=>$id]);$d->prepare('DELETE FROM user_roles WHERE user_id=:id')->execute(['id'=>$id]);$d->prepare("UPDATE users SET email=CONCAT('deleted-',id,'@invalid.local'),username=NULL,full_name='Usuario eliminado',password_hash=:hash,status='inactive',purged_at=CURRENT_TIMESTAMP,session_version=session_version+1 WHERE id=:id")->execute(['hash'=>password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT),'id'=>$id]);}$projects=$d->query("SELECT id FROM projects WHERE deleted_at<DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 60 DAY) FOR UPDATE")->fetchAll(PDO::FETCH_COLUMN);foreach($projects as $id)$d->prepare('DELETE FROM projects WHERE id=:id')->execute(['id'=>$id]);$this->audit($d,$actor,'trash_purged','trash',null,['users'=>count($users),'projects'=>count($projects)]);return ['users'=>count($users),'projects'=>count($projects)];});}
 private function audit(PDO $d,int $actor,string $action,string $type,?int $id,array $details):void
 {
  $element=$type==='trash'?'Elementos vencidos de la papelera':ucfirst($type).' #'.(int)$id;
  if($id&&in_array($type,['user','project'],true)){
   $column=$type==='user'?'full_name':'title';$table=$type==='user'?'users':'projects';
   $q=$d->prepare("SELECT $column FROM $table WHERE id=:id");$q->execute(['id'=>$id]);$element=(string)($q->fetchColumn()?:$element);
  }
  $labels=['user_trashed'=>'Envió un usuario a la papelera','user_restored'=>'Restauró un usuario desde la papelera','project_restored'=>'Restauró un proyecto desde la papelera','trash_purged'=>'Ejecutó la eliminación definitiva de elementos vencidos','initial_admin_deactivated'=>'Desactivó la cuenta administrativa inicial','admin_access_reactivated'=>'Reactivó una cuenta con acceso administrativo'];
  (new AdminActivityService($d))->record($actor,$action,$labels[$action]??$action,'Papelera',$type,$id,$element,'correct',$details);
 }
}
